Blog - Comparing Local Kubernetes Development Solutions
earthly/website pull request #196
Opened 2022-06-14 19:43 UTC by msali123

2022-06-14 20:14 UTC, jalletto requested changes
This is looking really great! I have a couple things. 

1. For images where the caption is just a description of the image like "Github Logo", you can add a`\` at the end. This keeps the caption as meta data, but it won't be visible when the site is deployed. For captions that actually offer something new like "Here you can see the output in the terminal" It's ok to leave the caption as is. Hopefully that makes sense.

2. Can you move the logos up to the section Overview of Each Tool?

3. Can you find generic images for the sections Complexity of Setup, Flexibility, and Support?

2022-06-14 20:14 UTC, jalletto commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![minikube logo]({{site.images}}{{page.slug}}/E51VHlu.png)
```suggestion
![minikube logo]({{site.images}}{{page.slug}}/E51VHlu.png)\
```

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![minikube logo]({{site.images}}{{page.slug}}/E51VHlu.png)
Done

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![Kind logo]({{site.images}}{{page.slug}}/9eE2wL1.png)
Done

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![K3s logo]({{site.images}}{{page.slug}}/NfeQXkM.png)
Done

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![Kubeadm logo]({{site.images}}{{page.slug}}/gikIAq7.png)
Done

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![Docker Desktop logo]({{site.images}}{{page.slug}}/kJMf8ZB.png)
Done

2022-06-15 05:53 UTC, msali123 commented on blog/_posts/2022-06-21-k8s-dev-solutions.md
> +![MicroK8s logo]({{site.images}}{{page.slug}}/kbvMYid.png)
Done

2022-06-15 06:50 UTC, msali123 commented
Done

2022-06-15 16:22 UTC, jalletto commented
@msali123 Looks like the build failed again do to a linting error.

BTW I set it up so that hopefully on your next pr the build will run right away without me needing to approve it. So you'll be able to see if it fails after you push instead of having to wait for me to run it.

2022-06-15 16:41 UTC, adamgordonbell commented
> @msali123 Looks like the build failed again do to a linting error.

I think it should be possible to run the linting in the code spaces as well. To find out faster if any problems are occurring. Just run `lint` or related commands.

2022-06-15 17:46 UTC, jalletto approved these changes
Looks great! Nice work.

2022-06-15 17:47 UTC, merged