Blog - How to Use MongoDB with Go
earthly/website pull request #209
Opened 2022-07-05 20:02 UTC by msali123

Done with all checks

2022-07-06 15:07 UTC, jalletto commented
Commit 6be996636819a24a2e9055a2f30148bcc96b67ea deployed to https://62c4a1bea8c7b828b112c4d7--ephemeral-narwhal-3ac3b2.netlify.app/

2022-07-06 15:24 UTC, jalletto requested changes
Requested a couple updates. Also waiting on a new image from the author.

2022-07-06 15:24 UTC, jalletto commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot 2022-06-01 at 20.45.31.png]({{site.images}}{{page.slug}}/sixth.png)\
All images from this point on can get <div class="wide">

2022-07-06 15:24 UTC, jalletto commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
For the code blocks, make sure the language matches the language in the block. In this case, go.
For the captions, it depends. Usually we want to put something about where the code is, often a file name. The `>_` is usually shorthand for something that gets run directly in the terminal, for example a `git checkout`. 

For this article, I don't think the author gives the file names, so we can just leave them blank or use main.go

2022-07-06 16:47 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot 2022-06-02 at 15.04.14.png]({{site.images}}{{page.slug}}/third.png)\
done

2022-07-06 16:49 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot 2022-05-30 at 21.41.56.png]({{site.images}}{{page.slug}}/fifth.png)\
Done

2022-07-06 16:49 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot 2022-06-01 at 20.45.31.png]({{site.images}}{{page.slug}}/sixth.png)\
wide?

2022-07-06 16:55 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
Done

2022-07-06 16:57 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot from 2022-05-13 15-16-12.png]({{site.images}}{{page.slug}}/first.png)\
Okay then i'll push the branch once the new image arrives.

2022-07-06 19:38 UTC, adamgordonbell requested changes

2022-07-06 19:38 UTC, adamgordonbell commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
caption=">_" should be for if you are running something at the command line. This is a file, so we need the filename, and also the format to use. 

Should be something like:
`~~~{.go caption="main.go"}`

2022-07-06 19:38 UTC, adamgordonbell commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
`~~~{.go caption="main.go"}`

2022-07-06 19:44 UTC, adamgordonbell commented
Probably no one has mentioned this, but the images for the header get cropped down to fit on social media, so it's important to keep the text in the center 2/3rds of the image.

You can view the cropped image by viewing source and you'll see a link like this:
```
<meta name="twitter:image" content="https://earthly.dev/blog/generated/assets/images/use-mongo-with-go/header-800-e6b8d0cd4.jpg">
```
You can see the cropping to fit twitter and facebook is not working out well:
![image](https://user-images.githubusercontent.com/3921401/177630067-0d4271e2-72ba-4700-b1d2-d632944f27ae.png)

2022-07-07 05:51 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +This tutorial will teach you how to use MongoDB databases with the Go programming language by connecting to your MongoDB Atlas cluster.
All images are changed to wide.

2022-07-07 05:51 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
Done it will be affected in next push.

2022-07-07 05:52 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +~~~{.bash caption=">_"}
Done it will be affected in next push.

2022-07-07 06:13 UTC, msali123 commented
@jalletto you can review every thing accept the : https://github.com/earthly/website/pull/209#discussion_r914964063

@adamgordonbell noted on your comment: https://github.com/earthly/website/pull/209#issuecomment-1176623949
I'll try to make the blog name in headers centered as you suggested, btw I've also updated the header of this article as well.

2022-07-07 06:22 UTC, msali123 commented
@adamgordonbell can we do the change of header for blog - Introduction to Pyscript at this moment?

2022-07-07 14:08 UTC, adamgordonbell commented
> @adamgordonbell can we do the change of header for blog - Introduction to Pyscript at this moment?

Sure, you can include it in this PR, or a separate one. Either is fine. I just noticed it now is all.

2022-07-07 15:30 UTC, msali123 commented
> > @adamgordonbell can we do the change of header for blog - Introduction to Pyscript at this moment?
> 
> Sure, you can include it in this PR, or a separate one. Either is fine. I just noticed it now is all.

Okay i'm changing the header image.

@jalletto did you got the image that we needed to change so that we could merge this PR?

2022-07-07 19:16 UTC, jalletto commented
@msali123 I attached the image to the email I sent you this morning.

2022-07-07 19:35 UTC, msali123 commented on blog/_posts/2022-07-22-use-mongo-with-go.md
> +![Screenshot from 2022-05-13 15-16-12.png]({{site.images}}{{page.slug}}/first.png)\
Done with the new image

2022-07-07 20:25 UTC, msali123 commented
Done

2022-07-08 15:45 UTC, jalletto approved these changes

2022-07-08 18:20 UTC, merged