Blog - Docker Slim
earthly/website pull request #210
Opened 2022-07-06 17:53 UTC by msali123

Done with all checks

2022-07-06 19:29 UTC, adamgordonbell requested changes

2022-07-06 19:29 UTC, adamgordonbell commented on blog/_posts/2022-07-25-docker-slim.md
> +~~~{.bash caption=">_"}
See how the caption is overlapping with the command and also how there is a scroll bar. 

Can we format this better somehow?

<img width="909" alt="Screen Shot 2022-07-06 at 3 26 01 PM" src="https://user-images.githubusercontent.com/3921401/177627423-2a6e8264-fe49-4432-990c-b1d17a40c6d9.png">

My suggestion would be to use line breaks and `\` to make it go across multiple lines:
```
curl -sL \
   https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh \
   | sudo -E bash -
```

2022-07-06 19:29 UTC, adamgordonbell commented on blog/_posts/2022-07-25-docker-slim.md
> +~~~{.bash caption=">_"}
Similar here. Maybe something like this:
```
docker run -it --rm -d -p 8080:80 \
--security-opt apparmor:nginx-apparmor-profile nginx.slim
```

2022-07-07 05:30 UTC, msali123 commented on blog/_posts/2022-07-25-docker-slim.md
> +~~~{.bash caption=">_"}
Resolved
Sorry for the inconvenience in future I'll break all the code block that have a scroll bar

2022-07-07 05:30 UTC, msali123 commented on blog/_posts/2022-07-25-docker-slim.md
> +~~~{.bash caption=">_"}
Resolved

2022-07-07 14:05 UTC, adamgordonbell commented on blog/_posts/2022-07-25-docker-slim.md
> +~~~{.bash caption=">_"}
That's great, Thank you. Not an inconvenience at all.

2022-07-07 14:06 UTC, adamgordonbell approved these changes

2022-07-07 18:27 UTC, msali123 commented
@jalletto done with review

2022-07-07 19:21 UTC, jalletto commented
Commit ffe7e884acd6e7d198c11729e3427668f8c87ea7 deployed to https://62c66d2acfa0bf3da9624ced--ephemeral-narwhal-3ac3b2.netlify.app/

2022-07-07 20:11 UTC, merged