Blog - How to validate and clean your YAML files using Kubeval and ValidKube
earthly/website pull request #215
Opened 2022-07-14 19:20 UTC by msali123

Please have a go through of code area's having the filenames.

2022-07-18 19:44 UTC, msali123 commented
@jalletto

2022-07-19 21:19 UTC, msali123 commented
Removed conflict.

2022-07-21 16:52 UTC, msali123 commented
@jalletto  can you please review

2022-07-22 17:50 UTC, msali123 commented
@jalletto can you please review

2022-07-22 18:35 UTC, jalletto commented
Commit 0eb0e8bb978878b1ba3fc59bcdddcde639c91b05 deployed to https://62d9840e16cbef00616c49ae--ephemeral-narwhal-3ac3b2.netlify.app/

2022-07-22 18:41 UTC, jalletto requested changes

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 18:41 UTC, jalletto commented on blog/_posts/2022-08-21-validate-&-clean-yaml.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-07-22 20:19 UTC, jalletto approved these changes

2022-07-22 20:19 UTC, merged