Terraform Import
earthly/website pull request #216
Opened 2022-07-14 20:05 UTC by adamgordonbell

See also this follow up:
https://github.com/earthly/website/pull/220

It didn't fit in the main article.

2022-07-19 16:34 UTC, jalletto requested changes
Looks good. Just a few little things.

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +  Tools exist that proport to take an existing cloud accounts and import them into Terraform state and generated the Terraform config for them. I did briefly try this approach.
```suggestion
  Tools exist that purport to take existing cloud accounts and import them into Terraform state and generate the Terraform config for them. I did briefly try this approach.
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +Let's pretend that I needed my repo to use KMS encryption and to scan image on push. I've already setup these options in AWS but I want to see how to do it AWS.
```suggestion
Let's pretend that I needed my repo to use KMS encryption and to scan an image on push. I've already setup these options in AWS but I want to see how to do it in Terraform.
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +This trick was instrumental in me getting my lambda integration ported over to terraform, but I'll refrain from focusing on it depth. Just remember, if you can't figure out how to configure something
```suggestion
This trick was instrumental in me getting my lambda integration ported over to terraform, but I'll refrain from focusing on it in depth. Just remember, if you can't figure out how to configure something in Terraform for some reason, one approach is to set it up in the UI first, and use `terraform import` and `terraform show` to extract a working config.
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +Imported is:
```suggestion
Imported with:
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +And then with the show trick I extracted the policy I was already using:
```suggestion
And then, with the `terraform show` trick I used above, I extracted the policy I was already using:
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +Then I need to set up the API, the API State and map it to the domain.
Should this be API stage?

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +Integrating the lambda with the API was by far the hardest part for me. In AWS, there is a single button click process to hook a lambda up to an API endpoint. Behind the scenes there are a number of
```suggestion
Integrating the lambda with the API was by far the hardest part for me. In AWS, there is a single button click process to hook a lambda up to an API endpoint. Behind the scenes there are a number of separate things happening. But once I figured out the name of all these little resources, it was easy to import and `terraform show` them to see how they should be configured.
```

2022-07-19 16:34 UTC, jalletto commented on blog/_posts/2022-07-12-terraform-lambda.md
> +In turns out that the lambda needs to have a container in place before being created. So I uncommented the lambda and did a docker push
```suggestion
It turns out that the lambda needs to have a container in place before being created. So I uncommented the lambda and did a docker push
```

2022-07-19 17:00 UTC, adamgordonbell commented on blog/_posts/2022-07-12-terraform-lambda.md
> +**Read this to learn about Terraform from a noob's perspective. The specifics of my infrastructure import may not be relevant to you, but hopefully my thinking process and take-aways will be.**
yeah, makes sense. 

There are probably less explicit ways to do it, but I think of it as saying "Here is why you should  (or shouldn't) read this" somewhere right at the beginning.

2022-07-19 18:04 UTC, adamgordonbell commented on blog/_posts/2022-07-12-terraform-lambda.md
> +Then I need to set up the API, the API State and map it to the domain.
Yes, nice catch.

2022-07-19 18:11 UTC, adamgordonbell commented on blog/_posts/2022-07-12-terraform-lambda.md
> +~~~{.groovy caption="main.tf"}
Somehow this wasn't happening once I made other changes. Hopefully it doesn't come back :)

2022-07-20 14:59 UTC, jalletto approved these changes

2022-07-21 10:40 UTC, merged