Blog Fix - Using gRPC with Golang, Python, and Ruby
earthly/website pull request #217
Opened 2022-07-15 16:46 UTC by msali123

http://localhost:4002/blog/protobufs-and-grpc/
-	Needs file names added where makes sense - Done with what I looked right
-	Also some command line commands need to be indicated - No idea about it
-	If possible break up any lines in code that are wrapping - Done

2022-07-19 13:00 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.bash caption="Earthfile"}
This isn't a bash file, best to use `dockerfile` like in the previous version. 
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2022-07-19 13:01 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.python caption="Eathfile"}
```suggestion
~~~{. dockerfile caption="Earthfile"}
```

2022-07-19 13:01 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.bash caption="Earthfile"}
```suggestion
~~~{.python caption="Earthfile"}
```

2022-07-19 13:01 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.python caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2022-07-19 13:02 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.ruby caption="Earthfile"}
```suggestion
~~~{. dockerfile caption="Earthfile"}
```

2022-07-19 13:02 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.ruby caption=">_"}
the caption should be the name of the ruby file

2022-07-20 16:08 UTC, adamgordonbell commented
@msali123  - see feedback

2022-07-20 18:01 UTC, msali123 commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> -    func (s *server) Set(ctx context.Context, in *kvapi.SetRequest) (*kvapi.SetReply, error) {
Done

2022-07-20 18:06 UTC, msali123 commented
> I've left comments explaining how to set the syntax highlighting and file name.
> 
> Let me know if that makes sense.

@adamgordonbell Thanks alot now i'm alot clear about the file names & hope dont repeat these mistakes in future.
Thanks

2022-07-22 18:00 UTC, adamgordonbell requested changes
@msali123  it doesn't look like you've fixed the items I highlighted? 

You'll have to checkout the PR branch, make the changes and push them.

2022-07-22 18:00 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +    // The key/value API contains two procedures for storing\
@msali123 This still need to be fixed

2022-07-22 18:00 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +    RUN wget -O protoc.zip https://github.com/protocolbuffers/protobuf/ \
still needs to be fixed

2022-07-22 18:00 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.bash caption="Earthfile"}
still needs to be fixed

2022-07-22 19:10 UTC, msali123 commented
@adamgordonbell  yes sorry I forgot to push from my side

2022-07-22 20:23 UTC, adamgordonbell requested changes
A couple more

2022-07-22 20:23 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.docker caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2022-07-22 20:23 UTC, adamgordonbell commented on blog/_posts/2020-11-13-protobufs-and-grpc.md
> +~~~{.bash caption="api.proto"}
```suggestion
~~~{. protobuf caption="api.proto"}
```

2022-07-25 17:17 UTC, msali123 commented
@adamgordonbell

2022-07-26 13:36 UTC, adamgordonbell approved these changes
Awesome!

2022-07-26 13:37 UTC, merged