Blog fix -  Encrypting Data With SSH Keys and Golang
earthly/website pull request #218
Opened 2022-07-15 19:06 UTC by msali123

http://localhost:4002/blog/encrypting-data-with-ssh-keys-and-golang/
-	Needs file names added where makes sense - Done
-	Remove `alex@earthly:~/$` prompts and use `$` instead - Done
-	Separate command line output from input – tried to separate one

2022-07-15 19:08 UTC, msali123 commented
Line 65 : 1z8l6QfFo9nTBlYI0k= alex@earthly

Please check if I have to remove this from the output code block as well?

2022-07-19 09:03 UTC, msali123 commented
@jalletto

2022-07-19 13:14 UTC, adamgordonbell requested changes
I couple small changes. Otherwise great!

2022-07-19 13:14 UTC, adamgordonbell commented on blog/_posts/2020-12-11-encrypting-data-with-ssh-keys-and-golang.md
> +    $:~/$ cat /tmp/testkey.pub
Prompt should but `$`
```suggestion
    $ cat /tmp/testkey.pub 
```

2022-07-19 13:14 UTC, adamgordonbell commented on blog/_posts/2020-12-11-encrypting-data-with-ssh-keys-and-golang.md
> +    $:~/$ cat /tmp/testkey
```suggestion
    $ cat /tmp/testkey
```

2022-07-19 15:36 UTC, msali123 commented on blog/_posts/2020-12-11-encrypting-data-with-ssh-keys-and-golang.md
> +    $:~/$ cat /tmp/testkey
Done

2022-07-19 15:37 UTC, msali123 commented on blog/_posts/2020-12-11-encrypting-data-with-ssh-keys-and-golang.md
> +    $:~/$ cat /tmp/testkey.pub
Done

2022-07-19 17:07 UTC, adamgordonbell approved these changes

2022-07-21 16:53 UTC, msali123 commented
@jalletto

2022-07-22 18:44 UTC, merged