Blog Fix - How to Setup and Use Amazon’s Elastic Container Registry
earthly/website pull request #221
Opened 2022-07-20 20:42 UTC by msali123

2022-07-22 19:30 UTC, msali123 commented
@jalletto

2022-07-22 19:56 UTC, jalletto commented
Commit d2eac7b0bf5ccbb6c4c881b624125671a6ee763e deployed to https://62d86a32164c7b1286735153--ephemeral-narwhal-3ac3b2.netlify.app/

2022-07-22 20:17 UTC, jalletto requested changes

2022-07-22 20:17 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.dockerfile caption="Dockerfile"}
```

2022-07-22 20:17 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.dockerfile caption="Dockerfile"}
```

2022-07-22 20:17 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.yaml caption=">_"}
```suggestion
~~~{.yaml caption=""}
```

2022-07-22 20:17 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.json caption=">_"}
```suggestion
~~~{.json caption=""}
```

2022-07-22 20:17 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.json caption=">_"}
If there's no file name I think we can just keep the caption blank.

2022-07-25 20:22 UTC, jalletto requested changes

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +          image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/
I'm not sure you can use the / here to break up the line. I don't think that works in a yaml file. Can you run this through a yml validator and double check? If it's not valid, you can look up how to break up a string in yaml.

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +      "image": "123456789012.dkr.ecr.us-west-2.amazonaws.com/
Same here. Not sure this you can break up json with the /.

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +docker pull <account-id>.dkr.ecr.<account-region>.amazonaws.com/
```suggestion
docker pull <account-id>.dkr.ecr.<account-region>.amazonaws.com\
```

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +FROM: <account-id>.dkr.ecr.<account-region>.amazonaws.com/
I don't think this will run with the /. This one will need to just be long. We may be able to prevent the overlap by putting an extra space between ~~~{.dockerfile caption="Dockerfile"} and the line of code.

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +~~~{.dockerfile caption="Dockerfile"}
```suggestion
~~~{.dockerfile caption="Dockerfile"}

```

2022-07-25 20:22 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +docker push <account-id>.dkr.ecr.<account-region>.amazonaws.com/
```suggestion
docker push <account-id>.dkr.ecr.<account-region>.amazonaws.com\
```

2022-07-25 21:05 UTC, msali123 commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +          image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/
https://stackoverflow.com/questions/67123929/how-to-deal-with-long-urls-in-ansibles-yaml-files

2022-07-25 21:06 UTC, msali123 commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +      "image": "123456789012.dkr.ecr.us-west-2.amazonaws.com/
Same option done \ added

2022-07-25 21:14 UTC, msali123 commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +FROM: <account-id>.dkr.ecr.<account-region>.amazonaws.com/
Lint isn't allowing to put an extra line between  ~~~{.dockerfile caption="Dockerfile"} and the code.

@jalletto

2022-07-25 21:37 UTC, msali123 commented
Please check now @jalletto

2022-07-27 15:57 UTC, jalletto commented on blog/_posts/2021-03-05-how-to-setup-and-use-amazons-elastic-container-registry.md
> +      aws-nodejs-sample:v1",
```suggestion
      "image": "123456789012.dkr.ecr.us-west-2.amazonaws.com/aws-nodejs-sample:v1",
```

2022-07-28 19:50 UTC, jalletto approved these changes

2022-07-28 19:51 UTC, merged