Blog - Creating and Deploying a Facial Recognition System with Jupyter Notebooks and Anvil
earthly/website pull request #240
Opened 2022-08-23 19:34 UTC by msali123

Done with all checks.

2022-08-25 15:23 UTC, jalletto requested changes
Please update the code examples.

2022-08-25 15:23 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption=""}
```

2022-08-25 15:23 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +~~~{.bash caption=">_"}
All of these that say `.bash` need to be changed to python. You can leave the caption blank.

2022-08-25 15:51 UTC, msali123 commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +~~~{.bash caption=">_"}
Done

2022-08-29 15:02 UTC, jalletto commented
Preview URL: https://6308bc0dea2ab01188b921c7--ephemeral-narwhal-3ac3b2.netlify.app/

2022-08-29 15:15 UTC, jalletto requested changes
One small change.

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +The process of building systems to deploy the models that data scientists and machine learning engineers have created is non-trivial. This is because other developers and designers are not always ava
```suggestion
The process of building systems to deploy the models that data scientists and machine learning engineers have created is non-trivial. This is because other developers and designers are not always available to create the required [APIs](https://aws.amazon.com/what-is/api/) and user interfaces. You could decide to learn to use the technologies required for this, but that takes considerable effort and could extend project completion by months. Due to this, you may just resort to leaving the models in notebooks on Github. 

But what if you could still move ahead? What if you could serve models from your notebooks and build minimal interfaces quickly?
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Deepnote sign up page]({{site.images}}{{page.slug}}/z025oRv.jpg)\
```suggestion
![Deepnote sign up page]({{site.images}}{{page.slug}}/z025oRv.jpg)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Deepnote Onboarding page]({{site.images}}{{page.slug}}/tadKsId.jpg)\
```suggestion
![Deepnote Onboarding page]({{site.images}}{{page.slug}}/tadKsId.jpg)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Deepnote new project]({{site.images}}{{page.slug}}/CTJ8sDq.png)\
```suggestion
![Deepnote new project]({{site.images}}{{page.slug}}/CTJ8sDq.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Deepnote images uploaded]({{site.images}}{{page.slug}}/TczQpPJ.png)\
```suggestion
![Deepnote images uploaded]({{site.images}}{{page.slug}}/TczQpPJ.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil dashboard]({{site.images}}{{page.slug}}/cGHHYfX.png)\
```suggestion
![Anvil dashboard]({{site.images}}{{page.slug}}/cGHHYfX.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil app default view]({{site.images}}{{page.slug}}/9Cqx0WX.png)\
```suggestion
![Anvil app default view]({{site.images}}{{page.slug}}/9Cqx0WX.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil entry point form]({{site.images}}{{page.slug}}/mTYpFfV.png)\
```suggestion
![Anvil entry point form]({{site.images}}{{page.slug}}/mTYpFfV.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil CheckForm]({{site.images}}{{page.slug}}/UKacj1U.png)\
```suggestion
![Anvil CheckForm]({{site.images}}{{page.slug}}/UKacj1U.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil remove form]({{site.images}}{{page.slug}}/lVrxmKa.png)\
```suggestion
![Anvil remove form]({{site.images}}{{page.slug}}/lVrxmKa.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![anvil-get-uplink-key]({{site.images}}{{page.slug}}/50KymOD.png)\
```suggestion
![anvil-get-uplink-key]({{site.images}}{{page.slug}}/50KymOD.png)
```

2022-08-29 15:15 UTC, jalletto commented on blog/_posts/2022-09-21-face-recog-sys-with-jupyter.md
> +![Anvil app test screenshot]({{site.images}}{{page.slug}}/GyueBhL.png)\
```suggestion
![Anvil app test screenshot]({{site.images}}{{page.slug}}/GyueBhL.png)
```

2022-08-29 20:35 UTC, jalletto approved these changes

2022-08-29 20:35 UTC, merged