Blog - How to use ReplicaSets in Kubernetes and why you should know about them
earthly/website pull request #241
Opened 2022-08-24 05:59 UTC by msali123

Done with all checks.

2022-08-25 17:05 UTC, msali123 commented
@jalletto could you re run the build?

2022-08-26 15:21 UTC, msali123 commented
@jalletto

2022-08-29 15:37 UTC, jalletto requested changes

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +title: "How to use ReplicaSets in Kubernetes and why you should know about them"
```suggestion
title: "How to use ReplicaSets in Kubernetes and Why You Should Know About Them"
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +title: "How to use ReplicaSets in Kubernetes and why you should know about them"
Can you please also update the header image so that the title is capitalized like this: How to use ReplicaSets in Kubernetes and Why You Should Know About Them

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 15:37 UTC, jalletto commented on blog/_posts/2022-09-30-use-replicasets-in-k8s.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="output"}
```

2022-08-29 20:36 UTC, jalletto approved these changes

2022-08-29 21:19 UTC, merged