Blog - How to Build A Real-Time Communication Application with Django-Channels and The WebSocket Protocol
earthly/website pull request #246
Opened 2022-09-06 20:24 UTC by msali123

Test

2022-09-06 20:24 UTC, msali123 commented
@jalletto for your reference.

2022-09-07 16:57 UTC, jalletto commented
@msali123 This is the issue as I described in my previous email. It's confusing because the syntax that Jekyll uses is the same as the one that the python code examples use. 

To fix it, you'll need to wrap all the python code that has {{ variable }} or {% some_code %} in {% raw %} and {% endraw %}. 

here is an example, but I also made some comments on the actual code. I did not fix every occurrence though. 
```
{% raw %} 
<script>
    document.querySelector('#chat-log').value = ""
    {% for message_event in message_and_event_list%}
 
   document.querySelector('#chat-log').value += ( {{message_event}}  + '\n');
{%endfor%}
</script>
{% endraw %}
```

2022-09-12 11:47 UTC, msali123 commented
@jalletto extremely stuck in this but still trying my best to do, so please bear with me.

2022-09-16 13:09 UTC, msali123 commented
Preview Link:
https://632473369eada33b360d8532--ephemeral-narwhal-3ac3b2.netlify.app/

2022-09-16 14:52 UTC, jalletto requested changes

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +>Even though the protocol you will be working with the most is the websocket protocol, you still need the Django views and the URL that handles HTTP because the user will arrive at the page via HTTP
```suggestion
Even though the protocol you will be working with the most is the websocket protocol, you still need the Django views and the URL that handles HTTP because the user will arrive at the page via HTTP and the HTML page template will be loaded by the view function associated with the URL. Also, the initial websocket handshake will be performed via HTTP.
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +]
```suggestion
urlpatterns = [
   path("", views.HomeView, name="home"),
   path("groups/<uuid:uuid>/", views.GroupChatView, name="group")
]
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +    ~~~{.bash caption=">_"}
```suggestion
    ~~~{.python caption="settings.py"}
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.bash caption="directory tree"}
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption="models.py"}
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
All the code examples for the python and html code need to have bash changed to python and the `>_` needs to be changed to the file name. The writer usually mentions the file name right before the code example, or as a comment at the top of the code example.

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption="models.py"}
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption="models.py"}
```

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
I did a few of them but there a more throughout the article.

2022-09-16 14:52 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +</wide>
```suggestion
</div>
```

2022-09-16 19:19 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +</html>
Done

2022-09-16 19:24 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +</wide>
Done

2022-09-16 19:24 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-16 19:25 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-16 19:26 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-16 19:27 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done sorry for inconvenience

2022-09-16 19:28 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +    ~~~{.bash caption=">_"}
Done

2022-09-16 19:29 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +]
Done

2022-09-16 19:29 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +>Even though the protocol you will be working with the most is the websocket protocol, you still need the Django views and the URL that handles HTTP because the user will arrive at the page via HTTP
Done

2022-09-16 19:32 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +```
Done

2022-09-16 19:39 UTC, msali123 commented
@jalletto  what to write for html code space

2022-09-20 15:28 UTC, jalletto requested changes

2022-09-20 15:28 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +In this tutorial, we'll learn how to build a real-time communication application with The [Django Channels](https://channels.readthedocs.io/en/stable/) package and The [WebSocket Protocol](https://da
```suggestion
In this tutorial, we'll learn how to build a real-time communication application with The [Django Channels](https://channels.readthedocs.io/en/stable/) package and The [WebSocket Protocol](https://datatracker.ietf.org/doc/html/rfc6455). The application we will create will be a platform where users can join multiple pre-created groups and share ideas with members of the group. [The entire project](https://github.com/DrAnonymousNet/DiscussIt) is available on my Github.
```

2022-09-20 15:28 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +Link to the code on Github and the DiscussIt app
```suggestion

```

2022-09-20 15:28 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +
```suggestion


```

2022-09-20 15:28 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +When a user join or leave a group:
```suggestion
When a user joins or leaves a group:
```

2022-09-22 17:48 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +Link to the code on Github and the DiscussIt app
```suggestion
[Here is the code for the project](https://github.com/DrAnonymousNet/DiscussIt)
```

2022-09-22 17:49 UTC, jalletto commented
@msali123 Just a few more and we can merge.

2022-09-23 06:45 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +Link to the code on Github and the DiscussIt app
Done

2022-09-23 06:45 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +In this tutorial, we'll learn how to build a real-time communication application with The [Django Channels](https://channels.readthedocs.io/en/stable/) package and The [WebSocket Protocol](https://da
Done

2022-09-23 06:47 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +When a user join or leave a group:
Done

2022-09-23 06:47 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +When a user join or leave a group:
Done

2022-09-23 06:48 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +
@jalletto do I need to remove the whole deployment heading and content

2022-09-23 07:02 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +Link to the code on Github and the DiscussIt app
@jalletto cannot use word 'here' in the link so ive modified it.

2022-09-23 18:05 UTC, msali123 commented
@jalletto please check all done from my side.

2022-09-26 15:55 UTC, msali123 commented
@jalletto 😬😬

2022-09-28 22:22 UTC, jalletto requested changes

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="base.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="home.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="groupchat.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#chat/consumers.py
```suggestion

```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#chat/routing.py
```suggestion

```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#DiscussIt/asgi.py
```suggestion

```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="home.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption=""}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="home.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption="consumers.py"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.javascript caption=""}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption=""}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.html caption="groupchat.html"}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption=""}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.python caption=""}
```

2022-09-28 22:22 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.javascript caption="groupchat.html"}
```

2022-09-29 05:45 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:46 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:46 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:47 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#chat/consumers.py
Done

2022-09-29 05:47 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#chat/routing.py
Done

2022-09-29 05:47 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +#DiscussIt/asgi.py
Done

2022-09-29 05:48 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:48 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:48 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:49 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:49 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:49 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:50 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:50 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:51 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-09-29 05:52 UTC, msali123 commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.bash caption=">_"}
Done

2022-10-04 14:44 UTC, jalletto commented on blog/_posts/2022-10-04-build-real-time-comm-app.md
> +~~~{.html caption="home.html"}
```suggestion
~~~{.javascript caption="home.html"}
```

2022-10-04 14:54 UTC, jalletto approved these changes

2022-10-04 14:54 UTC, merged