Blog - Understanding the Differences and Similarities Between K3s and K8s
earthly/website pull request #259
Opened 2022-10-03 15:55 UTC by msali123

Done with all checks.

2022-10-05 18:07 UTC, jalletto requested changes

2022-10-05 18:07 UTC, jalletto commented on blog/_posts/2022-10-23-K3s-&-K8s.md
> +
Can we add one more image here?

2022-10-05 19:16 UTC, msali123 commented on blog/_posts/2022-10-23-K3s-&-K8s.md
> +
Done

2022-10-06 14:50 UTC, jalletto approved these changes

2022-10-06 14:50 UTC, merged