Blog - How to Build GraphQL APIs Using Go
earthly/website pull request #260
Opened 2022-10-04 13:21 UTC by msali123

Done with all checks.

2022-10-05 19:19 UTC, jalletto requested changes
Hey Sameer, 

Made some changes to the code examples. In this case, the author included the code in a github repo https://github.com/Rose-stack/go-mysql-graphql-api. So in cases like this in the future, you can look to the source code to be sure you are getting the correct language and file.

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +Note: You can use the `Post` struct generated by gqlgen. However, it's good to take advantage of Gorm and describe your database structure with a few lines of code.
```suggestion
**Note**: You can use the `Post` struct generated by gqlgen. However, it's good to take advantage of Gorm and describe your database structure with a few lines of code.
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="mysql.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="mysql.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="mysql.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="mysql.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.go caption="server.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.go caption="server.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.go caption=">_"}
```suggestion
~~~{.bash caption=">_"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.go caption=">_"}
```suggestion
~~~{.bash caption=">_"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.go caption=">_"}
```suggestion
~~~{.bash caption=">_"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +go install github.com/cosmtrek/air@latest
```suggestion
$ go install github.com/cosmtrek/air@latest
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +air init
```suggestion
$ air init
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +air
```suggestion
$ air
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="graph/schema.resolvers.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{. caption=""}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="graph/schema.resolvers.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{. caption=""}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="graph/schema.resolvers.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{. caption=""}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{.go caption="graph/schema.resolvers.go"}
```

2022-10-05 19:19 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.js caption=">_"}
```suggestion
~~~{. caption=""}
```

2022-10-05 19:51 UTC, msali123 commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +
Done

2022-10-05 20:04 UTC, msali123 commented
@jalletto sorry for too much code area mistakes.

2022-10-07 13:50 UTC, msali123 commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{. caption=""}
Josh do I need to change only code blocks for output or text?

Or for the code blocks as well like this?
~~~{.go caption=">_"}

2022-10-11 19:57 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.go caption=">_"}
```suggestion
~~~{.bash caption=">_"}
```

2022-10-11 20:02 UTC, jalletto requested changes

2022-10-11 20:02 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=""}
```suggestion
~~~{.text caption=""}
```

2022-10-11 20:02 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=""}
```suggestion
~~~{.text caption=""}
```

2022-10-11 20:02 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=""}
```suggestion
~~~{.text caption=""}
```

2022-10-11 20:02 UTC, jalletto commented on blog/_posts/2022-10-19-build-GraphQL-APIs-Go.md
> +~~~{.bash caption=""}
```suggestion
~~~{.text caption=""}
```

2022-10-11 20:14 UTC, jalletto approved these changes

2022-10-11 20:14 UTC, merged