Blog - Concurrency in Go
earthly/website pull request #262
Opened 2022-10-05 17:09 UTC by msali123

Done with all checks

2022-10-06 14:48 UTC, jalletto requested changes
For this one:
- all the code examples can have a blank caption "".
- Keep the caption "Output" blocks for output, but leave the code part blank since that's just text
- I'm not sure what the cover image has to do with concurrency? Let's change it.

2022-10-06 14:48 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{.go caption=">_"}
```suggestion
~~~{.go caption=""}
```

2022-10-06 14:48 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{.go caption=">_"}
For this article, since it's just basic examples that are being run in one file, we can leave the caption off entirely.

2022-10-06 14:48 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{.go caption="Output"}
Output is not in go, just text

2022-10-06 14:48 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +     "fmt"
```suggestion
~~~{.go caption=">_"}
import (
    "Sync"
    "fmt"
```

2022-10-06 14:48 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +}
```suggestion
    defer close(channels)
    go starter(channels)
    reciever1 := <- channels
    reciever2 := <- channels
    follow(reciever1, reciever2)
}
```

2022-10-06 20:34 UTC, msali123 commented
> For this one:
> 
> * all the code examples can have a blank caption "".
> * Keep the caption "Output" blocks for output, but leave the code part blank since that's just text
> * I'm not sure what the cover image has to do with concurrency? Let's change it.

@jalletto  All done

2022-10-11 20:47 UTC, jalletto requested changes

2022-10-11 20:47 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{. caption="Output"}
```suggestion
~~~{.text caption="Output"}
```

2022-10-11 20:47 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{. caption="Output"}
```suggestion
~~~{.text caption="Output"}
```

2022-10-11 20:47 UTC, jalletto commented on blog/_posts/2022-10-26-concurrency-in-Go.md
> +~~~{. caption="Output"}
```suggestion
~~~{.text caption="Output"}
```

2022-10-11 20:58 UTC, merged