Blog - How to use Docker in VS Code
earthly/website pull request #268
Opened 2022-10-08 09:06 UTC by msali123

Done with all checks.

2022-10-12 13:00 UTC, msali123 commented
@jalletto 
Please review

2022-10-14 20:31 UTC, msali123 commented
@jalletto

2022-10-17 17:56 UTC, msali123 commented
@adamgordonbell

2022-10-21 08:02 UTC, msali123 commented
@jalletto  Done with replacement of GIF's.

2022-11-02 16:33 UTC, jalletto commented
Preview: https://6360debf35097500b2106710--ephemeral-narwhal-3ac3b2.netlify.app/blog/how-to-use-docker-in-vscode/

2022-11-02 16:36 UTC, jalletto requested changes

2022-11-02 16:38 UTC, jalletto requested changes

2022-11-02 16:38 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![container logs]({{site.images}}{{page.slug}}/Hn6x6xm.png)\
I don't see them in the images folder. Maybe you forgot to update these?

2022-11-02 18:47 UTC, msali123 commented
@jalletto my bad didn't verified .

2022-11-02 19:34 UTC, jalletto approved these changes

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![Searching for docker extension]({{site.images}}{{page.slug}}/vVdGELj.png)\
```suggestion
![Searching for docker extension]({{site.images}}{{page.slug}}/vVdGELj.png)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![containers,volumes,images and more]({{site.images}}{{page.slug}}/UQWjQRM.png)\
```suggestion
![Containers ,volumes, images and more]({{site.images}}{{page.slug}}/UQWjQRM.png)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![adding docker files]({{site.images}}{{page.slug}}/bM7WWsn.jpeg)\
```suggestion
![Adding docker files]({{site.images}}{{page.slug}}/bM7WWsn.jpeg)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![Docker build]({{site.images}}{{page.slug}}/gn9rNt4.jpeg)\
```suggestion
![Building an image]({{site.images}}{{page.slug}}/gn9rNt4.jpeg)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![our latest project]({{site.images}}{{page.slug}}/qxnlDbj.png)\
```suggestion
![Our latest project]({{site.images}}{{page.slug}}/qxnlDbj.png)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![Docker run]({{site.images}}{{page.slug}}/lDRhXAu.jpeg)\
```suggestion
![Running a container]({{site.images}}{{page.slug}}/lDRhXAu.jpeg)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![running docker inside the extension]({{site.images}}{{page.slug}}/OU6RnwE.jpeg)\
```suggestion
![Running docker inside the extension]({{site.images}}{{page.slug}}/OU6RnwE.jpeg)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![the run and debug section]({{site.images}}{{page.slug}}/WSiiCWl.png)\
```suggestion
![The run and debug section]({{site.images}}{{page.slug}}/WSiiCWl.png)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![The breakpoint]({{site.images}}{{page.slug}}/dnqMcyX.png)\
```suggestion
![Using breakpoints]({{site.images}}{{page.slug}}/dnqMcyX.png)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![view container logs]({{site.images}}{{page.slug}}/P8lZ9Fr.jpeg)\
```suggestion
![Viewing container logs]({{site.images}}{{page.slug}}/P8lZ9Fr.jpeg)
```

2022-11-02 19:34 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![Docker inspect]({{site.images}}{{page.slug}}/HMQtXXA.jpeg)\
```suggestion
![Docker inspect]({{site.images}}{{page.slug}}/HMQtXXA.jpeg)
```

2022-11-02 19:41 UTC, jalletto commented on blog/_posts/2022-10-31-how-to-use-docker-in-vscode.md
> +![Containers ,volumes, images and more]({{site.images}}{{page.slug}}/UQWjQRM.png)
```suggestion
![Containers ,volumes, images, and more]({{site.images}}{{page.slug}}/UQWjQRM.png)
```

2022-11-02 19:48 UTC, merged