Blog - Deploying Docker Containers with ECS
earthly/website pull request #273
Opened 2022-10-14 20:24 UTC by msali123

Done with all checks.

2022-10-14 20:34 UTC, msali123 commented
@jalletto

2022-10-17 18:39 UTC, jalletto requested changes
Just some small changes for this one.

2022-10-17 18:39 UTC, jalletto commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +~~~
When two separate commands are on top of each other like this, they tend to blend together. We can seperate them by adding a -
```suggestion

~~~{.bash caption=">_"}
virtualenv env
~~~

-

~~~{.bash caption=">_"}
pip install django djangorestframework
~~~
```

2022-10-17 18:39 UTC, jalletto commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +~~~
When there are two seperate code examples on back to back with nothing inbetween, they will blend together in the doc. You can put a single blank line between them by adding a `-`.

2022-10-17 18:39 UTC, jalletto commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +
```suggestion

~~~{.bash caption=">_"}
source env/bin/actviate
~~~

-

~~~{.bash caption=">_"}
django-admin startproject app .
~~~

```

2022-10-17 18:39 UTC, jalletto commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +With that, we have just successfully deployed our docker container.
```suggestion
</div>

As you can see, we got a response of `{"message": "Hello World"}`.

With that, we have just successfully deployed our docker container.
```

2022-10-17 18:48 UTC, msali123 commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +With that, we have just successfully deployed our docker container.
Done

2022-10-17 18:48 UTC, msali123 commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +
Done

2022-10-17 18:49 UTC, msali123 commented on blog/_posts/2022-11-03-deploy-DockerContainers-with-ECS.md
> +~~~
Done

2022-10-17 19:42 UTC, jalletto commented
@msali123 Never mind about the -. I put them in the other PR too, but you can ignore that and just leave it as is. I think this is something we need to change in the CSS. My mistake.

2022-10-17 20:33 UTC, jalletto approved these changes

2022-10-17 20:33 UTC, merged