Blog - CMake vs. Make: What’s the Difference?
earthly/website pull request #300
Opened 2022-12-05 16:30 UTC by msali123

Done with all checks.

2022-12-05 17:55 UTC, msali123 commented
https://638e2d2764c0215f5429c4dd--ephemeral-narwhal-3ac3b2.netlify.app/blog/cmake-vs-make-diff/

2022-12-07 19:58 UTC, jalletto requested changes

2022-12-07 19:58 UTC, jalletto commented on blog/_posts/2022-12-15-cmake-vs-make-diff.md
> +
```suggestion
~~~{ caption="Output"}
cmake version 3.10.2

```

2022-12-07 19:58 UTC, jalletto commented on blog/_posts/2022-12-15-cmake-vs-make-diff.md
> +
@msali123 for all the ones with output, we don't need to specify .bash.  If we leave it blank it will default to text, which is what we want for output. Can you update the rest in the doc?

2022-12-07 20:02 UTC, msali123 commented on blog/_posts/2022-12-15-cmake-vs-make-diff.md
> +
yes sure I'm doing it

2022-12-07 20:13 UTC, msali123 commented on blog/_posts/2022-12-15-cmake-vs-make-diff.md
> +
@jalletto done

2022-12-08 15:18 UTC, merged