Blog - How to get started with PyMongo
earthly/website pull request #307
Opened 2022-12-13 18:05 UTC by msali123

Done with all checks.

2022-12-13 18:14 UTC, msali123 commented
https://6398c0523632557db339e1cd--ephemeral-narwhal-3ac3b2.netlify.app
@jalletto this might have code area errors, please tell me so i can fix when you review

2022-12-15 20:37 UTC, jalletto requested changes

2022-12-15 20:37 UTC, jalletto commented on blog/_posts/2022-12-31-starting-with-pymongo.md
> +update=updates)
```suggestion
book_collection.update_one( filter={"_id": book_id}, 
                                                  update=updates
                                                 )
```

2022-12-15 20:37 UTC, jalletto commented on blog/_posts/2022-12-31-starting-with-pymongo.md
> +update=updates)
@msali123 For function calls in python, we can spread them over multiple lines without needing to use the \.

2022-12-15 20:37 UTC, jalletto commented on blog/_posts/2022-12-31-starting-with-pymongo.md
> +update={"$set": {"author": "Unknown Author"}})
```suggestion
book_collection.update_many(filter={}, 
                                                   update={"$set": {"author": "Unknown Author"}}
                                                   )
```

2022-12-15 20:37 UTC, jalletto approved these changes

2022-12-15 21:39 UTC, jalletto approved these changes

2022-12-15 21:39 UTC, jalletto commented on blog/_posts/2022-12-31-starting-with-pymongo.md
> +                                                   )
```suggestion
~~~{.python caption="main.py"}
book_collection.update_many(filter={}, update={"$set": {"author": "Unknown Author"}})
```

2022-12-15 21:39 UTC, jalletto commented on blog/_posts/2022-12-31-starting-with-pymongo.md
> +~~~
```suggestion
book_collection.update_one( filter={"_id": book_id}, update=updates)
~~~
```

2022-12-15 23:53 UTC, merged