Blog - How to Set Up a TypeScript Monorepo
earthly/website pull request #316
Opened 2023-01-12 20:47 UTC by msali123

Done with all checks

2023-01-12 20:55 UTC, msali123 commented
Preview URL: 
https://63c0732645aeb56ffd5c5898--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-17 18:09 UTC, jalletto requested changes

2023-01-17 18:09 UTC, jalletto commented on blog/_posts/2023-01-24-setup-typescript-monorepo.md
> +npm install eslint prettier @typescript-eslint/eslint-parser @typescript-eslint/eslint-plugin
This line is getting overlapped by the caption. Need to add a blank line above it.

2023-01-17 21:00 UTC, jalletto approved these changes

2023-01-17 21:00 UTC, merged