Blog - Deploying Docker Containers to AWS ECS Using Terraform
earthly/website pull request #321
Opened 2023-01-19 16:42 UTC by msali123

Done with all checks.

2023-01-23 21:15 UTC, jalletto requested changes

2023-01-23 21:15 UTC, jalletto commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
Captions for all of these should be "Dockerfile"

2023-01-24 16:49 UTC, msali123 commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
@jalletto done

2023-01-26 03:56 UTC, balapriyac requested changes
@jalletto I've finished reviewing this PR.

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion

~~~{.dockerfile caption="Dockerfile"}
# Pull the Node.js image
FROM node:18-alpine
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion
~~~{.dockerfile caption="Dockerfile"}
# Create a Docker working directory
WORKDIR /app
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion
~~~{.dockerfile caption="Dockerfile"}
# Copy package.json and package-lock.json dependencies files 
COPY package*.json ./

~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +
```suggestion

~~~{.dockerfile caption="Dockerfile"}
# Install dependencies inside Docker
RUN npm install
~~~

```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion

~~~{.dockerfile caption="Dockerfile"}
# Copy the application source code
COPY . .
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +
```suggestion

~~~{.dockerfile caption="Dockerfile"}
# Port number to expose the Node.js app outside of Docker
EXPOSE 5000

~~~

```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion

~~~{.dockerfile caption="Dockerfile"}
# Command to run the application
CMD ["node", "index.js"]
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.45.0"
    }
  }
}
~~~

```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
provider "aws" {
  region  = "us-east-1" #The region where the environment 
  #is going to be deployed # Use your own region here
  access_key = "enter_access_key_here" # Enter AWS IAM 
  secret_key = "enter_secret_key_here" # Enter AWS IAM 
}
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
resource "aws_ecr_repository" "app_ecr_repo" {
  name = "app-repo"
}
~~~

```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~
```suggestion
~~~{.terraform caption="main.tf"}
# main.tf
resource "aws_ecs_cluster" "my_cluster" {
  name = "app-cluster" # Name your cluster here
}
~~~
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +~~~{ caption="main.tf"}
```suggestion

~~~{.terraform caption="main.tf"}
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +resource "aws_iam_role" "ecsTaskExecutionRole" {
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
resource "aws_iam_role" "ecsTaskExecutionRole" {
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
# Provide a reference to your default VPC
resource "aws_default_vpc" "default_vpc" {
}

```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +resource "aws_alb" "application_load_balancer" {
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
resource "aws_alb" "application_load_balancer" {
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +# main.tf
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +resource "aws_lb_target_group" "target_group" {
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
resource "aws_lb_target_group" "target_group" {
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +# main.tf
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +# main.tf
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
```

2023-01-26 03:56 UTC, balapriyac commented on blog/_posts/2023-01-31-deploy-dockcontainers-to-AWSECS-using-Terraform.md
> +# main.tf
```suggestion

~~~{.terraform caption="main.tf"}
# main.tf
```

2023-01-26 07:37 UTC, msali123 commented
@balapriyac Requested changes done.

2023-01-27 16:20 UTC, merged