Blog - Building Your JavaScript Monorepo
earthly/website pull request #322
Opened 2023-01-19 17:13 UTC by msali123

Done with all checks.

2023-01-19 17:24 UTC, msali123 commented
Preview URL:
https://63c97b87909dde5ef6f597fd--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-19 18:13 UTC, msali123 commented
Preview URL:
https://63c987d1f5788d6ed2efc01d--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-23 21:19 UTC, jalletto requested changes

2023-01-23 21:19 UTC, jalletto commented on blog/_posts/2023-02-02-building-js-monorepo.md
> +title: "Building Your JavaScript Monorepo"
@msali123 This looks great but needs one change. Somehow the title got changed on the Airtable card, so this is the wrong title. 

Title should be "Navigating the Monorepo Tools Ecosystem". Sorry for the confusion. Can you please update this and the header?

2023-01-23 21:54 UTC, msali123 commented on blog/_posts/2023-02-02-building-js-monorepo.md
> +title: "Building Your JavaScript Monorepo"
Sure I'll change

2023-01-23 22:19 UTC, jalletto commented on blog/_posts/2023-02-02-building-js-monorepo.md
> +title: "Building Your JavaScript Monorepo"
@msali123 Actually never mind. My mistake it's fine the way it is.

2023-01-23 22:27 UTC, merged