Blog - Building a Real-time Stock Price Dashboard Using Python, QuestDB, and Plotlye
earthly/website pull request #327
Opened 2023-01-20 18:25 UTC by msali123

Done with all checks.

2023-01-20 19:58 UTC, msali123 commented
Hey @jalletto could you please help on this.

2023-01-25 16:54 UTC, jalletto commented
Hi @msali123. Looks like this is failing because of white space on line 133. I think it's just a blank space that needs to be deleted. 

`         ./blog+lint *failed* | ./blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md:133:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]`

2023-01-25 20:21 UTC, msali123 commented
@jalletto finally done 🤩

2023-01-31 14:19 UTC, jalletto requested changes

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +~~~{.bash caption=">_"}
```suggestion
~~~{.sql }
```

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Creating Workers Using Celery]({{site.images}}{{page.slug}}/lqv7XJ9.png)
```suggestion
![Creating Workers Using Celery]({{site.images}}{{page.slug}}/lqv7XJ9.png)\
```

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Image]({{site.images}}{{page.slug}}/p5JXM6g.png)
```suggestion
![Image]({{site.images}}{{page.slug}}/p5JXM6g.png)\
```

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Image]({{site.images}}{{page.slug}}/p5JXM6g.png)
Let's add the citation for the image if we have it.

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +~~~{.env caption=""}
```suggestion
~~~{ caption=".env"}
```

2023-01-31 14:19 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
```suggestion
![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)\
```

2023-01-31 15:59 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Image]({{site.images}}{{page.slug}}/p5JXM6g.png)
@jalletto these images were provided by author so should I remove them let them go without credit?

2023-01-31 16:00 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
provided by author
@jalletto

2023-02-01 17:25 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
@msali123 Can you email the author and ask if they have a source?

2023-02-01 19:31 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
Okay I'll do

2023-02-02 10:33 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
![image](https://user-images.githubusercontent.com/32276372/216301245-0b116ad3-7e6e-4e7d-8f06-46f8bf22c9e1.png)

Should we remove these images? @jalletto

2023-02-06 16:17 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
No we only need citations for graphics, not screen shots. I might not have been clear about that. Sorry about the confusion.

2023-02-06 16:53 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +version: "3"
```suggestion
~~~{.yaml caption="docker-compose.yml"}

version: "3"
```

2023-02-06 16:53 UTC, jalletto commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +~~~
```suggestion
~~~{.bash caption=">_"}

$ curl -o assets/style.css https://github.com/verah-tech/stock-market/blob/main/assets/style.css
~~~
```

2023-02-06 17:22 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
@jalletto so I should remove the photos & make alternate designs on canva

2023-02-08 07:28 UTC, msali123 commented on blog/_posts/2023-02-24-dashboard-with-python-questdb-plotly.md
> +![Setting Up the Application]({{site.images}}{{page.slug}}/3OFABqK.png)
??

2023-02-13 15:47 UTC, jalletto commented
@msali123 Sorry I think there was some confusion on this one. We won't ever need sources for screen shots the author took themselves. I was talking about these images:

blog/assets/images/dashboard-with-python-questdb-plotly/3OFABqK.png
blog/assets/images/dashboard-with-python-questdb-plotly/p5JXM6g.png

Which we should site. 

Also, the title needs to updated in the header image. No 'e' at then end of Plotly. Since you are editing it, let's take this opportunity to shorten the title to: Stock Price Dashboard with QuestDB and Plotly

2023-02-13 19:43 UTC, msali123 commented
So @jalletto should I remove these 2 images?

Or make my self something relevant like this on canva?

blog/assets/images/dashboard-with-python-questdb-plotly/3OFABqK.png
blog/assets/images/dashboard-with-python-questdb-plotly/p5JXM6g.png

2023-02-14 06:28 UTC, balapriyac commented
@jalletto @msali123 
This article is flagged for plagiarism. https://questdb.io/blog/2021/11/01/plotly-finnhub-realtime-dashboard/ is the original article published in Nov 2021. I've sent a message on Slack.

2023-02-14 13:52 UTC, adamgordonbell commented
Unfortunately, we won't be merging this article. Pause work on this PR.

2023-02-14 13:52 UTC, closed without merging