Blog - Build a Data Dashboard with Streamlit in Python
earthly/website pull request #328
Opened 2023-01-21 06:13 UTC by msali123

Done with all checks.

2023-01-21 06:20 UTC, msali123 commented
Preview URL:
https://63cb83e7bf022d307bcf2310--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-26 04:44 UTC, balapriyac requested changes
@jalletto I've finished reviewing this PR.

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
import streamlit as st
st.write("Hello World!")
st.write("Hello Streamlit!")

~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
#read in the file
movies_data = pd.read_csv("https://raw.githubusercontent.com/danielgrijalva/movie-stats/7c6a562377ab5c91bb80c405be50a0494ae8e582/movies.csv")
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
The author submitted a GitHub link to their code for this tutorial. All code is in the data_analysis.py file, so adding it to the caption.

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
movies_data.info()
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +#output
```suggestion
~~~{caption="Output"}
#output
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
movies_data.duplicated()
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +0       False
```suggestion

~~~{caption="Output"}
#output
0       False
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
movies_data.count()
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +#output
```suggestion

~~~{ caption="Output"}
#output
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
movies_data.dropna()
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
st.write("""
Average Movie Budget, Grouped by Genre
""")
avg_budget = movies_data.groupby('genre')['budget'].mean().round()
avg_budget = avg_budget.reset_index()
genre = avg_budget['genre']
avg_bud = avg_budget['budget']
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +
```suggestion

~~~{.python caption="data_analysis.py"}
fig = plt.figure(figsize = (19, 10))

```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +
```suggestion

~~~{.python caption="data_analysis.py"}
st.pyplot(fig)

```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
col1, col2 = st.columns(2)
col1.write('# This is Column 1')
col2.write('# This is Column 2')
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +
```suggestion

~~~{.python caption="data_analysis.py"}
st.write('### Columns of different sizes')
col1, col2, col3, col4 = st.columns([1,3,1,2])

```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
# Creating sidebar widget unique values from our movies dataset
score_rating = movies_data['score'].unique().tolist()
genre_list = movies_data['genre'].unique().tolist()
year_list = movies_data['year'].unique().tolist()

~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~{.python caption=""}
```suggestion

~~~{.python caption="data_analysis.py"}
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
#Configure and filter the slider widget for interactivity
score_info = (movies_data['score'].between(*new_score_rating))
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +~~~
```suggestion

~~~{.python caption="data_analysis.py"}
#Filter the selectbox and multiselect widget for interactivity
new_genre_year = (movies_data['genre'].isin(new_genre_list)) \
& (movies_data['year'] == year)
~~~
```

2023-01-26 04:44 UTC, balapriyac commented on blog/_posts/2023-02-19-streamlit-python-dashboard.md
> +# visualization section
```suggestion

~~~{.python caption="data_analysis.py"}
# visualization section
```

2023-01-26 07:48 UTC, msali123 commented
@balapriyac  Requested changes done.

2023-01-30 23:43 UTC, merged