Blog - Go with the Gin Framework
earthly/website pull request #330
Opened 2023-01-26 16:40 UTC by msali123

Done with all checks.

2023-01-26 20:17 UTC, msali123 commented
Preview URL:https://63d2ae6ddf9742088ba2eae3--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-31 04:39 UTC, balapriyac requested changes
Thank you, Sameer! @jalletto I've finished reviewing this PR.

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +~~~
```suggestion
~~~{.bash caption=">_"}
go get github.com/gin-gonic/gin
~~~
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +~~~
```suggestion
~~~{.bash caption=">_"}
go get gorm.io/gorm
go get gorm.io/driver/sqlite
~~~
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +~~~
We run the `go get` command at the terminal.

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +These are the imports you'll need for this tutorial.
```suggestion
These are the imports you'll need for this tutorial:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +You'll need to meet a few prerequisites to understand and follow this hands-on tutorial.
```suggestion
You'll need to meet a few prerequisites to understand and follow this hands-on tutorial:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Note: You can find the complete code for this tutorial on this [GitHub Gist](https://gist.github.com/Goodnessuc/e4fdc78b04965e991efc440f50705ece)
```suggestion
Note: You can find the complete code for this tutorial on this [GitHub Gist](https://gist.github.com/Goodnessuc/e4fdc78b04965e991efc440f50705ece).
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Run these commands in your working directory to install the [packages](/blog/setup-typescript-monorepo).
```suggestion
Run these commands in your working directory to install the packages:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Here's an example `company` struct with `gorm` and `json` tags.
```suggestion
Here's an example `company` struct with `gorm` and `json` tags:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The `POST` request handler function will accept JSON input from the client for GORM to migrate to the decoded JSON struct database.
```suggestion
The `POST` request handler function will accept JSON input from the client for GORM to migrate to the decoded JSON struct database:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The PostCompany handler function receives POST requests from the server, parses the JSON into the `newCompany` struct, and the Create method of your database instance creates a new row of the struct
```suggestion


```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The PostCompany handler function receives POST requests from the server, parses the JSON into the `newCompany` struct, and the Create method of your database instance creates a new row of the struct
Remove repeated paragraph.

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Here's a CURL request that tests the `PostCompany` handler function.
```suggestion
Here's a CURL request that tests the `PostCompany` handler function:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Here's the CURL request for the `GetCompany` handler function. The `CURL` request sends a request to the `/api/v1/:company` route with the data attached to the URL.
```suggestion
Here's the CURL request for the `GetCompany` handler function. The `CURL` request sends a request to the `/api/v1/:company` route with the data attached to the URL:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Here's the CURL request that tests the `UpdateCompany` handler function. Insert a company name in the specified field to run the CURL request effectively.
```suggestion
Here's the CURL request that tests the `UpdateCompany` handler function. Insert a company name in the specified field to run the CURL request effectively:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +Here's the CURL request for the `DeleteCompany` handler function. Insert a company name in the specified field to run the CURL request effectively.
```suggestion
Here's the CURL request for the `DeleteCompany` handler function. Insert a company name in the specified field to run the CURL request effectively:
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The CURL request sends a PUT request to the `api/v1/:company` endpoint with a JSON payload as the replacement for the update operation.
```suggestion
The CURL request sends a PUT request to the `api/v1/:company` endpoint with a [JSON](/blog/convert-to-from-json) payload as the replacement for the update operation.
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The CURL request sends a PUT request to the `api/v1/:company` endpoint with a [JSON](/blog/convert-to-from-json) payload as the replacement for the update operation.
```suggestion
The CURL request sends a DELETE request to the `api/v1/:company` endpoint to delete the matching row from the database.
```

2023-01-31 04:39 UTC, balapriyac commented on blog/_posts/2023-02-27-golang-gin-framework.md
> +The CURL request sends a PUT request to the `api/v1/:company` endpoint with a [JSON](/blog/convert-to-from-json) payload as the replacement for the update operation.
The author has pasted this explanation from _The PUT Request Handler_ section. Rewrote that sentence as this section is on _The DELETE Request Handler_.

2023-01-31 08:15 UTC, msali123 commented
@balapriyac done with the requested changes.

2023-01-31 14:22 UTC, jalletto approved these changes

2023-01-31 14:23 UTC, merged