Blog - Understanding Django Signals
earthly/website pull request #331
Opened 2023-01-26 20:17 UTC by msali123

Done with all checks.

2023-01-26 20:25 UTC, msali123 commented
Preview URL:
 https://63d2e1383d04ff0d917d6f9c--ephemeral-narwhal-3ac3b2.netlify.app

2023-01-31 08:20 UTC, msali123 commented
@balapriyac requested changes done

2023-01-31 14:28 UTC, jalletto commented on blog/_posts/2023-03-02-django-signals.md
> +#models.py
@balapriyac This has caption "pre_save.py" but then this comment that implies the file is named "models.py"?

2023-01-31 14:28 UTC, jalletto commented on blog/_posts/2023-03-02-django-signals.md
> +#models.py
Same here.

2023-01-31 14:30 UTC, jalletto commented on blog/_posts/2023-03-02-django-signals.md
> +#models.py
same here

2023-01-31 14:30 UTC, jalletto commented on blog/_posts/2023-03-02-django-signals.md
> +#views.py
Same here

2023-01-31 14:31 UTC, jalletto commented
@balapriyac Looks great, just left a few comments.

2023-01-31 14:41 UTC, balapriyac commented
> @balapriyac Looks great, just left a few comments.

@jalletto thank you. The author shared [this GitHub repo](https://github.com/Horlawhumy-dev/earthly-django-signals-article) with us when requested. I think the author mistakenly added models.py as a comment (for both the save and delete signals). Sorry for not catching this earlier.

2023-01-31 14:44 UTC, balapriyac requested changes

2023-01-31 16:13 UTC, msali123 commented
@balapriyac  @jalletto  done with the requested changes.

2023-02-01 23:21 UTC, jalletto approved these changes

2023-02-01 23:21 UTC, merged