Blog - Using a Cache to Improve Bazel Build Times
earthly/website pull request #340
Opened 2023-02-06 17:57 UTC by msali123

Done with all checks.

2023-02-09 07:55 UTC, msali123 commented
Preview URL: 
https://63e141089e57d004eb36c960--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-13 04:33 UTC, balapriyac requested changes
Thank you, Sameer. Josh, I've finished reviewing this PR.

2023-02-13 04:33 UTC, balapriyac commented on blog/_posts/2023-03-09-bazel-build-with-caching.md
> +Bazel uses a fine-grained cache by default. This means it stores individual action results (such as compiling a single file) in the cache, avoiding repeating actions. You can choose to use the coarse
```suggestion
Bazel uses a *fine-grained cache* by default. This means it stores individual action results (such as compiling a single file) in the cache, avoiding repeating actions. You can choose to use the coarser-grained cache, which stores the results of larger groups of actions together. This can be useful when dealing with large builds that have many actions because it reduces the amount of data stored in the cache and improves [cache hit rates](https://bazel.build/remote/cache-remote).
```

2023-02-13 04:33 UTC, balapriyac commented on blog/_posts/2023-03-09-bazel-build-with-caching.md
> +However, local caching can create the following limitations:
```suggestion
However, local caching has the following limitations:
```

2023-02-13 04:33 UTC, balapriyac commented on blog/_posts/2023-03-09-bazel-build-with-caching.md
> +Replace `<host>` and `<port>` with the hostname and port of your remote execution instance. Then use the build and test commands as usual, and Bazel will automatically use the remote cache and remote
```suggestion
Replace `<host>` and `<port>` with the hostname and port of your remote execution instance, respectively. Then use the build and test commands as usual, and Bazel will automatically use the remote cache and remote execution instance for your builds.
```

2023-02-13 04:33 UTC, balapriyac commented on blog/_posts/2023-03-09-bazel-build-with-caching.md
> +Disabling the Bazel cache can significantly increase your build and test time. However, all files must be rebuilt again by Bazel, even if they've already been built and are stored in the cache.
```suggestion
Disabling the Bazel cache can significantly increase your build and test times. However, all files must be rebuilt again by Bazel, even if they've already been built and are stored in the cache.
```

2023-02-13 04:33 UTC, balapriyac commented on blog/_posts/2023-03-09-bazel-build-with-caching.md
> +In this guide, you learned about the concept of [Bazel](/blog/bazel-build) cache builds. After reading, you should be able to set up the local and remote cache to improve Bazel build performance. For
```suggestion
In this guide, you learned about the concept of [Bazel](/blog/bazel-build) cache builds. After reading, you should be able to set up the local and remote cache to improve Bazel build performance. For more information, check out [this guide for any command-line reference](https://bazel.build/reference/command-line-reference) you may need.
```

2023-02-13 06:29 UTC, msali123 commented
@balapriyac  @jalletto  done with required changes.

2023-02-13 18:14 UTC, jalletto approved these changes

2023-02-13 18:14 UTC, merged