Blog - Earthly v0.7(3 blog)
earthly/website pull request #342
Opened 2023-02-11 13:50 UTC by msali123

Done with the required checks.

2023-02-11 13:58 UTC, msali123 commented
Preview URL: 
https://63e79e80c1305b33cf45a6f6--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-11 14:18 UTC, msali123 commented
https://63e79e80c1305b33cf45a6f6--ephemeral-narwhal-3ac3b2.netlify.app/blog/launching-earthly-ci/
@jalletto please let me know if I should add supporting images to this blog

2023-02-11 14:18 UTC, msali123 commented
https://63e79e80c1305b33cf45a6f6--ephemeral-narwhal-3ac3b2.netlify.app/blog/launching-earthly-ci/
@jalletto please let me know if I should add supporting images to this blog

2023-02-14 10:06 UTC, msali123 commented
@jalletto any update on it?

2023-02-16 21:38 UTC, jalletto commented
@msali123 I've given the team links to the three articles. Once they review I'll let you know.

2023-02-16 22:19 UTC, jalletto requested changes

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +Hello world! We have partnered up with some [cool people in Silicon Valley LINK](LINK) [1] to fix the world of CI. So today we are launching [Earthly CI](https://earthly.dev/signup/earthly-ci), the w
I don't think we ever covered how to do footnotes. We put footnotes at the very bottom, after the `{% include cta/cta1.html %}`. They are usually numbered and we can create links between them with [^1], [^2], [^3] and so on. 

This article has them if you want to see an example https://earthly.dev/blog/chroot/.

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +[1] Innovation Endeavors led our [$6.5M Seed+ round LINK](LINK), and were joined by 468 Capital and Uncorrelated Ventures. A number of founders of companies such as Cockroach Labs, DigitalOcean, Meso
```suggestion

[^1] Innovation Endeavors led our [$6.5M Seed+ round LINK](LINK), and were joined by 468 Capital and Uncorrelated Ventures. A number of founders of companies such as Cockroach Labs, DigitalOcean, Mesosphere, DataDog, Sentry, and Instana, plus a number of creators and maintainers of notable developer platforms, such as Docker, Elixir, VS Code, GitHub Copilot, Hashicorp, Envoy proxy, Cypress, Mesos and many others, have also previously invested in Earthly.
```

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +[1] Innovation Endeavors led our [$6.5M Seed+ round LINK](LINK), and were joined by 468 Capital and Uncorrelated Ventures. A number of founders of companies such as Cockroach Labs, DigitalOcean, Meso
Move this section to below ` {% include cta/cta1.html %}`. Then confirm that the links work. The one in the paragraph above should take you down to the bottom where the footnote is. Then there should be a small in the form of an arrow at the end of the sentence that brings you back up to the top.

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +[2] And because everything runs in containers, it is possible in the future to also distribute a single build across a compute cluster for maximum parallelization. Today, Earthly CI only runs on one
Same thing with this footnote as above. Move the actual footnote to the bottom and confirm that the links work properly.

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +~~~{.earthfile caption=""}
```suggestion
~~~{.Dockerfile caption=""}
```

2023-02-16 22:19 UTC, jalletto commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +~~~{.earthfile caption=""}
Can you change all the .earthfile to .Dockerfile?

2023-02-17 02:02 UTC, vladaionescu commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +## Problem #3: Ci/Cd Pipelines Are a Nightmare to Maintain
```suggestion
## Problem #3: CI/CD Pipelines Are a Nightmare to Maintain
```

2023-02-17 02:02 UTC, vladaionescu commented on blog/_posts/2023-02-21-launching-earthly-CI.md
> +And finally, Earthly CI was designed to work with any code layout. And more specifically, it was designed and tested with both monorepos and polyrepos in mind. For monorepos, Earthly understands the
```suggestion
And finally, Earthly CI was designed to work with any code layout. And more specifically, it was designed and tested with both monorepos and polyrepos in mind. For monorepos, Earthly understands the interdependence of build targets, and the specific source files that contribute to those targets, allowing it to cache and parallelize builds accordingly. If you're iterating on an integration test and you only change 1 out of 7 microservices, Earthly only rebuilds that 1 microservice before re-running the integration test. Similarly, Earthly has a strong understanding of setups where the build is split across many repositories. It is Git-hash-aware, and will only rebuild what has actually changed.
```

2023-02-17 09:52 UTC, msali123 commented
Preview URL:
https://63ef4dfba54be84fe721aed9--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-17 15:29 UTC, adamgordonbell commented
@msali123 This PR will probably have a lot of tweaks requested over the next few days because we want to get it right. 

Can you change the publish dates of the articles (rename the files) as follows:
2/23/2023 -> Launching Earthly CI
2/23/2023 ->Announcing Earthly's $6.5M Seed+ round
2/28/2023 -> Earthly 0.7

2023-02-17 15:34 UTC, adamgordonbell requested changes

2023-02-17 15:34 UTC, adamgordonbell commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +|--use-chmod    | Enable the SAVE IMAGE --no-manifest-list option|
```suggestion
|--use-chmod    | Allow setting the permissions of the copied files.|
```

2023-02-17 15:34 UTC, adamgordonbell commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Today, we're announcing the release of Earthly v0.7. The new version introduces changes that make Earthly work with Earthly CI, our new CI/CD platform (read more about Earthly CI in [Earthly CI](TODO
'TODO: Link to CI launch blog post' should be the other post in this PR

2023-02-17 15:34 UTC, adamgordonbell commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Earthly 0.7 is the first version compatible with [Earthly CI](https://earthly.dev/product/earthly-ci). All Earthly CI pipelines are defined in Earthfiles using Earthly's simple, familiar syntax and s
@thtmnisamnstr  I feel like sending them to the CI blog post here would be better? What do you think?

2023-02-17 15:34 UTC, adamgordonbell commented on blog/_posts/2023-02-21-new-fundings-at-earthly.md
> +The new funding will be used to improve and add more enterprise-friendly features to [Earthly CI LINK](Link to other blog post). Earthly CI is a fast, repeatable CI/CD platform that is super simple t
This should link to the CI article, in same PR

2023-02-17 15:47 UTC, jalletto commented
@msali123 For the banner images, they look low res. Are they the same dimensions we normally use? Can you try to use a higher resolution image? 

For the launching-earthly-ci, the earthly logo on the rocket isn't cropped so it looks tacked on. Can we just replace the rocket with a high resolution version of the logo? Here is a link to a png https://drive.google.com/file/d/1JHYwKTAwKoQyghgIz1Tdgq6mITLmgyO4/view?usp=sharing. 

And then for the Announcing Earthly’s $6.5M Seed+ round, can you put the logo in a white circle and then leave some room around the logo and the edge of the circle so it doesn't look like the logo is spilling out? Similar to how the f in this facebook logo sits in the circle. https://www.freeiconspng.com/img/46264.

2023-02-17 15:47 UTC, msali123 commented
> @msali123 This PR will probably have a lot of tweaks requested over the next few days because we want to get it right. 
> 
> Can you change the publish dates of the articles (rename the files) as follows:
> 2/23/2023 -> Launching Earthly CI
> 2/23/2023 ->Announcing Earthly's $6.5M Seed+ round
> 2/28/2023 -> Earthly 0.7
> 

Sure @adamgordonbell I'll change them to make this perfect.

2023-02-17 16:41 UTC, msali123 commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Today, we're announcing the release of Earthly v0.7. The new version introduces changes that make Earthly work with Earthly CI, our new CI/CD platform (read more about Earthly CI in [Earthly CI](TODO
Link to - Launching Earthly CI
@adamgordonbell ?

2023-02-21 18:19 UTC, msali123 commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Today, we're announcing the release of Earthly v0.7. The new version introduces changes that make Earthly work with Earthly CI, our new CI/CD platform (read more about Earthly CI in [Earthly CI](TODO
??

2023-02-21 18:20 UTC, msali123 commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Earthly 0.7 is the first version compatible with [Earthly CI](https://earthly.dev/product/earthly-ci). All Earthly CI pipelines are defined in Earthfiles using Earthly's simple, familiar syntax and s
?? @jalleto

2023-02-21 18:43 UTC, msali123 commented
@jalletto  
Preview URL: https://63f510917bdf8011e1a80508--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-21 22:10 UTC, jalletto commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Earthly 0.7 is the first version compatible with [Earthly CI](https://earthly.dev/product/earthly-ci). All Earthly CI pipelines are defined in Earthfiles using Earthly's simple, familiar syntax and s
@thtmnisamnstr bump

2023-02-21 22:13 UTC, jalletto commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Today, we're announcing the release of Earthly v0.7. The new version introduces changes that make Earthly work with Earthly CI, our new CI/CD platform (read more about Earthly CI in [Earthly CI](TODO
yes nice job Sameer 👍

2023-02-21 22:18 UTC, thtmnisamnstr commented on blog/_posts/2023-02-21-earthly-v0-7.md
> +Earthly 0.7 is the first version compatible with [Earthly CI](https://earthly.dev/product/earthly-ci). All Earthly CI pipelines are defined in Earthfiles using Earthly's simple, familiar syntax and s
I agree. Let's change the link to the Earthly CI launch blog post.

2023-02-22 00:29 UTC, vladaionescu commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +~~~
Is there a way to use Earthly-specific syntax highlighting here? I know @jalletto mentioned that there might be a possibility to do this.

2023-02-22 00:29 UTC, vladaionescu commented on blog/_posts/2023-02-28-earthly-v0-7.md
> +author: Vlad
I believe the author of this article is Gavin. CC @jalletto

2023-02-22 00:29 UTC, vladaionescu commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +  - Articles
All three articles should have the category set as News.

2023-02-22 08:22 UTC, msali123 commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +  - Articles
done

2023-02-22 08:24 UTC, msali123 commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +~~~
@jalletto could you help on this?

2023-02-22 08:26 UTC, msali123 commented on blog/_posts/2023-02-28-earthly-v0-7.md
> +author: Vlad
There's no info about Gavin in Author @jalletto

2023-02-22 08:36 UTC, msali123 commented
Preview URL:
https://63f5d3891f7f8c59c0b971e1--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-22 18:25 UTC, jalletto commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +~~~
@vladaionescu We don't have earthly specific highlighting. I Dockerfile is the best we can do.

2023-02-22 18:26 UTC, vladaionescu commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +~~~
Ok sounds good

2023-02-22 18:26 UTC, jalletto commented on blog/_posts/2023-02-28-earthly-v0-7.md
> +author: Vlad
@msali123 I'm reaching out to get his bio. Ill let you know when I have it.

2023-02-22 18:27 UTC, jalletto commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +  - Articles
Thanks @msali123. That was my mistake telling you to use Article.

2023-02-22 18:34 UTC, jalletto commented on blog/_posts/2023-02-28-earthly-v0-7.md
> +author: Vlad
Actually, Gavin is going to make a PR against this one with the bio.

2023-02-22 18:53 UTC, jalletto commented
@msali123 Couple of last things. (Thanks for your patience on this one!)

In [this file](https://github.com/earthly/website/blob/main/blog/_layouts/home.html#L4) can you change `hero_post: earthly-open-source` to be `hero_post: launching-earthly-ci` and then change `featured_post_a: docker-volumes` to be `featured_post_a: earthly-open-source`

2023-02-22 19:06 UTC, msali123 commented
@jalletto  no worries for the changes I'm happy to do them 😃 

I've commit this change but will push after adding the new author.

Is it okay?

2023-02-22 20:43 UTC, jalletto commented
@msali123  I think Gavin is going to push the author profile himself, so I think you are good to go. I'm not going to merge this until tomorrow morning though since we don't want it to go out before then.

2023-02-22 20:58 UTC, msali123 commented
Preview URL: https://63f6817494fd94095be90969--ephemeral-narwhal-3ac3b2.netlify.app
@jalletto

2023-02-22 23:45 UTC, jalletto commented on blog/_layouts/home.html
> +hero_post: launching-earthly-ci
```suggestion
hero_post: launching-earthly-CI
```

2023-02-23 00:41 UTC, jalletto approved these changes

2023-02-23 00:41 UTC, jalletto commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +Hello world! We have partnered up with some [cool people in Silicon Valley LINK](LINK) [^1] to fix the world of CI. So today we are launching [Earthly CI](https://earthly.dev/signup/earthly-ci), the
```suggestion
Hello world! We have partnered up with some cool people in Silicon Valley [^1] to fix the world of CI. So today we are launching [Earthly CI](https://earthly.dev/signup/earthly-ci), the world's first CI/CD solution that merges together a CI and a build system. A more fine-grained understanding of the build allows Earthly CI to run faster than a CI ever could before. And it's not an incremental improvement. It's a dramatic improvement. We're talking 100% to 2,000% faster. Here's how we did it.
```

2023-02-23 14:45 UTC, jalletto commented on blog/_posts/2023-02-28-earthly-v0-7.md
> +### Example: Push an image only if tests have passed
```suggestion
### Example: Push an Image Only if Tests Have Passed
```

2023-02-23 14:53 UTC, jalletto approved these changes

2023-02-23 14:53 UTC, jalletto commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +*Hello world! We have partnered up with some [cool people in Silicon Valley](/blog/new-fundings-at-earthly/) to fix the world of CI. So today we are launching [Earthly CI](https://earthly.dev/signup/
```suggestion
*Hello world! We have partnered up with some [cool people in Silicon Valley](/blog/new-fundings-at-earthly/) [^1] to fix the world of CI. So today we are launching [Earthly CI](https://earthly.dev/signup/earthly-ci), the world's first CI/CD solution that merges together a CI and a build system. A more fine-grained understanding of the build allows Earthly CI to run faster than a CI ever could before. And it's not an incremental improvement. It's a dramatic improvement. We're talking 100% to 2,000% faster. Here's how we did it.*
```

2023-02-23 14:53 UTC, jalletto commented on blog/_posts/2023-02-23-launching-earthly-CI.md
> +    Innovation Endeavors led our [$6.5M Seed+ round LINK](LINK), and were joined by 468 Capital and Uncorrelated Ventures. A number of founders of companies such as Cockroach Labs, DigitalOcean, Meso
```suggestion
    Innovation Endeavors led our [$6.5M Seed+ round](/blog/new-fundings-at-earthly/), and were joined by 468 Capital and Uncorrelated Ventures. A number of founders of companies such as Cockroach Labs, DigitalOcean, Mesosphere, DataDog, Sentry, and Instana, plus a number of creators and maintainers of notable developer platforms, such as Docker, Elixir, VS Code, GitHub Copilot, Hashicorp, Envoy proxy, Cypress, Mesos and many others, have also previously invested in Earthly.
```

2023-02-23 15:03 UTC, merged