Blog - An Introduction to Kubernetes Secrets
earthly/website pull request #343
Opened 2023-02-13 14:24 UTC by msali123

Done with all checks.

2023-02-14 06:00 UTC, balapriyac commented
Adding the preview link: https://63ea968da9556f27ffc8ba9d--ephemeral-narwhal-3ac3b2.netlify.app/

2023-02-14 06:01 UTC, balapriyac commented
@msali123 can you add an  image or two?

2023-02-14 08:48 UTC, msali123 commented
Preview URL:
https://63eb49db2097765e4b1a0a6a--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-15 02:47 UTC, balapriyac requested changes
Looks great, thanks Sameer. @jalletto I've finished reviewing this PR.

2023-02-15 02:47 UTC, balapriyac commented on blog/_posts/2023-03-17-kubernetes-secrets.md
> +Now that you have a good knowledge of Kubernetes secrets, you can now implement it in your application and deploy safely to Kubernetes.
```suggestion
Now that you have a good knowledge of Kubernetes secrets, you can implement it in your application and deploy safely to Kubernetes.
```

2023-02-15 02:47 UTC, balapriyac commented on blog/_posts/2023-03-17-kubernetes-secrets.md
> +In Kubernetes there are various types of secrets, we have:
```suggestion
In Kubernetes there are various types of secrets; we have:
```

2023-02-15 02:47 UTC, balapriyac commented on blog/_posts/2023-03-17-kubernetes-secrets.md
> +You should now have two secrets - *postgres-demo*  and *postgres-demo-0*, as shown below:
```suggestion
You should now have two secrets: *postgres-demo*  and *postgres-demo-0*, as shown below:
```

2023-02-15 02:47 UTC, balapriyac commented on blog/_posts/2023-03-17-kubernetes-secrets.md
> +The secret **postgres-secret* holds the credentials needed to access the PostgreSQL server, so you will use that secret as an environment variable to configure a statefulSet to deploy a PostgreSQL da
```suggestion
The secret **postgres-secret** holds the credentials needed to access the PostgreSQL server, so you will use that secret as an environment variable to configure a statefulSet to deploy a PostgreSQL database.
```

2023-02-15 02:47 UTC, balapriyac commented on blog/_posts/2023-03-17-kubernetes-secrets.md
> +
```suggestion
- Define a volume section under the statefulSet Pod specification, with a name *secret-volume*.
- Specify the type of volume (a secret volume type) and which secret it should use (*postgres-secret*).
- Include the keys Kubernetes should watch out for while creating the statefulset (*postgres_password* and *postgres_username*) alongside their paths which are required (these paths could be anything, like *my-postgres-path*).
- Define a mode **511** which is optional.
- Mount the volume inside the containers section using *volumeMounts* , specify the name of the volume we'd like to mount which is *secret-volume* and then the *mountPath* `/secret` which is where the secret will be saved.
- Add an `env` section to get the POSTGRES_USER and POSTGRES_PASSWORD value from the  */var/lib/postgresql/secret/postgres_username* and */var/lib/postgresql/secret/postgres_password* file paths in the container's file system.

```

2023-02-15 08:21 UTC, msali123 commented
@balapriyac done with changes.

2023-02-15 08:22 UTC, msali123 commented
Preview URL:
https://63ec95ea0c4f967daa4a6a7e--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-16 21:39 UTC, merged