Blog - API Testing Using Playwright With Python
earthly/website pull request #349
Opened 2023-02-14 10:05 UTC by msali123

Done with all checks.

2023-02-14 10:18 UTC, msali123 commented
Preview URL:
https://63eb5e2ad9df270287155528--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-17 07:28 UTC, balapriyac requested changes
Thanks Sameer. @jalletto I've finished reviewing this PR.

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +Using the `virtualenv` tool is a great way to create a Python virtual environment. Using a virtual environment, you can isolate the dependencies amongst different projects in the same machine, allowi
```suggestion
Using the `virtualenv` tool is a great way to create a Python virtual environment. Using a virtual environment, you can isolate the dependencies amongst different projects in the same machine, allowing you to create different versions of dependencies, and mitigating the risks of having dependency conflicts.
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +- A ready-to-use virtual environment. You can use [virtualenv](https://virtualenv.pypa.io/en/latest/installation.html#via-pip) or the [built-in venv](https://docs.python.org/3/library/venv.html).
```suggestion
- A Python virtual environment. You can use [virtualenv](https://virtualenv.pypa.io/en/latest/installation.html#via-pip) or the [built-in venv](https://docs.python.org/3/library/venv.html).
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +You also defined the asynchronous Python function for creating a new repository on GitHub using GitHub API. The asynchronous Python function starts with `async def` syntax. Inside the asynchronous Py
```suggestion
You also defined the asynchronous Python function for creating a new repository on GitHub using GitHub API. The asynchronous Python function starts with `async def` syntax. Inside the asynchronous Python function, when making API calls, you need to add the `await` keyword before the calling functions so that when you work with the responses of the functions, your return values are ready to use.
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +When implementing the test, there are times that your test will fail due to the wrong setup in the test. Let's create a failed test to demonstrate this scenario and see how we can fix the failed test
```suggestion
When implementing the test, there are times when your tests may fail. Let's take an example to demonstrate this scenario and see how we can fix a failing test.
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +## Step 10: Use `allure` To Capture The Failed Message Then Fix It
```suggestion
## Step 10: Use `allure` To Capture The Failed Message, Then Fix It
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +From the allure report, we can see one broken test. Clicking on the "Suites" menu on the left panel, we see the test that has failed is "test_create_a_new_repository
```suggestion
From the allure report, we can see one broken test. Clicking on the "Suites" menu on the left panel, we see the test that has failed is `test_create_a_new_repository`.
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +Clicking on that failed test in allure report, we see the error message is "AttributeError: 'coroutine' object has no attribute 'status'" and the line of code that caused the error is captured.
```suggestion
Clicking on that failed test in allure report, we see the error message is `"AttributeError: 'coroutine' object has no attribute 'status'"` and the line of code that caused the error is captured.
```

2023-02-17 07:28 UTC, balapriyac commented on blog/_posts/2023-03-20-playwright-python-api-testing.md
> +`pytest` complains that the coroutine object `response_create_a_repo` does not have a `status` attribute. Usually, the response of the API should always have a `status` attribute, even if the API is
```suggestion
`pytest` complains that the coroutine object `response_create_a_repo` does not have a `status` attribute. Usually, the response of the API should always have a `status` attribute, regardless of the status of the API test. 
```

2023-02-17 10:10 UTC, msali123 commented
Preview URL:
https://63ef52215ae61a572284bb1e--ephemeral-narwhal-3ac3b2.netlify.app

Done @balapriyac

2023-02-21 21:53 UTC, jalletto approved these changes

2023-02-21 21:54 UTC, merged