Blog - Apply Mutual TLS Over a Kubernetes Nginx Ingress Controller
earthly/website pull request #352
Opened 2023-02-15 18:31 UTC by msali123

Done with all checks.

2023-02-15 18:40 UTC, msali123 commented
@jalletto 
Preview URL:
https://63ed26578e402500658432db--ephemeral-narwhal-3ac3b2.netlify.app

2023-02-20 06:51 UTC, balapriyac requested changes
Thanks Sameer. @jalletto I've finished reviewing this PR.

2023-02-20 06:51 UTC, balapriyac commented on blog/_posts/2023-03-28-mutual-tls-kubernetes-nginx-ingress-controller.md
> +
```suggestion

<div class="notice--info">
  `sudo` is required here to allow incoming traffic on port 443.
Also keep that command running in a separate session as port-forwarding will be used for the rest of the article.
</div>
```

2023-02-20 06:51 UTC, balapriyac commented on blog/_posts/2023-03-28-mutual-tls-kubernetes-nginx-ingress-controller.md
> + -k is used to skip self-signed certificate verification and -v to see some logs.
```suggestion
 `-k` is used to skip self-signed certificate verification and `-v` to see some logs.
```

2023-02-20 08:44 UTC, msali123 commented
Preview URL:
https://63f3328c565a8320aaa0981a--ephemeral-narwhal-3ac3b2.netlify.app

@balapriyac @jalletto changes done

2023-02-21 21:59 UTC, jalletto approved these changes

2023-02-21 21:59 UTC, merged