Blog - A Guide to Setting Up Your Monorepo for JavaScript Projects with Lerna
earthly/website pull request #360
Opened 2023-02-27 15:43 UTC by msali123

Done with all checks.

2023-02-27 15:50 UTC, msali123 commented
Preview URL:
https://63fcd107350dd5007c6ac3a4--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-03 07:51 UTC, balapriyac requested changes
@msali123 
Thanks Sameer. 
- Just left a couple small notes.
- Also, I think Ahmad misspelled **Lerna** in the slug to use in the doc. It's currently `javascript-monorepo-setup-with-larna`. Please update the slug to `javascript-monorepo-with-lerna`.

2023-03-03 07:51 UTC, balapriyac commented on blog/_posts/2023-04-03-javascript-monorepo-setup-with-larna.md
> +If both commands are working locally, they should work in CI as well. To configure a [Github](/blog/ci-comparison Actions to use these, run the following commands to create a new workflow:
```suggestion
If both commands are working locally, they should work in CI as well. To configure a [Github Actions](/blog/ci-comparison) to use these, run the following commands to create a new workflow:
```

2023-03-03 07:51 UTC, balapriyac commented on blog/_posts/2023-04-03-javascript-monorepo-setup-with-larna.md
> +## Wrapping Up
```suggestion
## Conclusion
```

2023-03-03 07:51 UTC, balapriyac commented on blog/_posts/2023-04-03-javascript-monorepo-setup-with-larna.md
> +## Wrapping Up
For consistency, we'll use _Conclusion_ always.

2023-03-03 09:03 UTC, msali123 commented
https://6401b76238e2612bf733b540--ephemeral-narwhal-3ac3b2.netlify.app/blog/javascript-monorepo-with-lerna/

@balapriyac done

2023-03-03 12:35 UTC, balapriyac commented
> https://6401b76238e2612bf733b540--ephemeral-narwhal-3ac3b2.netlify.app/blog/javascript-monorepo-with-lerna/
> 
> @balapriyac done

Thanks, Sameer. @jalletto this is ready to merge!

2023-03-06 19:33 UTC, jalletto approved these changes

2023-03-06 19:33 UTC, merged