Blog - Introduction to Netlify Cloud Functions
earthly/website pull request #362
Opened 2023-02-28 08:13 UTC by msali123

Done with all checks.

2023-02-28 09:01 UTC, msali123 commented
Preview URL:
https://63fdc1ed1b74a2007cd5590e--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-03 08:02 UTC, balapriyac requested changes
Thanks Sameer. Left a couple small notes.

2023-03-03 08:02 UTC, balapriyac commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +
```suggestion
For example, if you want to access the cloud function to process the pictures uploaded by the user, the HTTP request would look like this,
 `http://localhost:8888/.netlify/functions/processPictures`. This would allow your cloud function to be accessed and used to process the pictures uploaded by the user.

```

2023-03-03 08:02 UTC, balapriyac commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
@msali123 Sameer, can you please request the author to provide a high resolution image?

2023-03-03 09:07 UTC, msali123 commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
okay I've emailed author to send one.

2023-03-03 12:36 UTC, balapriyac commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
> okay I've emailed author to send one.

Thank you.

2023-03-03 14:53 UTC, msali123 commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
The author says this is the highest res he has

2023-03-03 15:53 UTC, balapriyac commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
@msali123 oh, okay. Can you please wait till Monday? I can create one (similar image) on Monday morning, and share it with you. You can then update the image.

2023-03-03 21:42 UTC, msali123 commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
https://640268cddccd42282cb12972--ephemeral-narwhal-3ac3b2.netlify.app/blog/netlify-cloud-functions/

@balapriyac  I've added one let me know if its okay

2023-03-06 03:25 UTC, balapriyac commented on blog/_posts/2023-04-06-netlify-cloud-functions.md
> +</div>
This looks great, Sameer! Thank you.

2023-03-06 03:25 UTC, balapriyac commented
@jalletto this is ready to merge, too.

2023-03-06 19:40 UTC, jalletto approved these changes

2023-03-06 19:45 UTC, merged