Blog - How to Use Django Template Filters
earthly/website pull request #370
Opened 2023-03-08 12:26 UTC by msali123

2023-03-08 13:37 UTC, jalletto commented on blog/_posts/2023-04-17-django-template-filters.md
> +~~~{.{{ caption=""}
```suggestion
~~~{caption=""}
```

2023-03-08 13:38 UTC, jalletto commented on blog/_posts/2023-04-17-django-template-filters.md
> +~~~{.{{ caption=""}
I think the problem is the "{{" here. Does it work if you delete that?

2023-03-08 15:15 UTC, msali123 commented
@jalletto here's a clear picture.

2023-03-08 15:56 UTC, jalletto commented on blog/_posts/2023-04-17-django-template-filters.md
> +Here's the syntax to use the date filter: `{{ value|date:"D d M Y" }}`
I think the error is coming from here, or some other place where we have `{{...date...}}`. I would just go to every code block or inline code where there is `{{}}` or {%%}` and try wrapping it in the raw/endRaw.

2023-03-08 15:59 UTC, jalletto commented on blog/_posts/2023-04-17-django-template-filters.md
> +Here's the syntax to use the date filter: `{{ value|date:"D d M Y" }}`
essentially when Jekyll sees {{ }} or {%%} it thinks it should run some code because normally that is how you tell it to run code. The problem is that Django also uses the same format to run code in its HTML files. So when we try to show Django code doesn't know we don't want it to run.

2023-03-08 17:37 UTC, msali123 commented
Preview URL:
https://6408c749085b7370e538dbf5--ephemeral-narwhal-3ac3b2.netlify.app/blog/django-template-filters/

Hey @jalletto thanks for the help!

2023-03-14 05:27 UTC, balapriyac requested changes
Thanks Sameer. Just a couple small changes in h3 elements.

2023-03-14 05:27 UTC, balapriyac commented on blog/_posts/2023-04-17-django-template-filters.md
> +### Summing Up
```suggestion
### Reviewing What We've Learned So Far
```

2023-03-14 05:27 UTC, balapriyac commented on blog/_posts/2023-04-17-django-template-filters.md
> +### Summing Up
```suggestion
### Summing Up With a Quick Example
```

2023-03-14 08:57 UTC, msali123 commented
Preview URL: https://641036345aa97b5d74599437--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-14 10:27 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-03-15 16:42 UTC, jalletto approved these changes

2023-03-15 16:42 UTC, merged