Blog - Securing Kubernetes Secrets Effectively
earthly/website pull request #371
Opened 2023-03-08 18:35 UTC by msali123

Done with all checks.

2023-03-08 18:44 UTC, msali123 commented
Preview URL: https://6408d70e29a7fb0c5f407cdb--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-14 05:21 UTC, balapriyac requested changes
Thanks, Sameer. Looks great. Requested for one small change.

2023-03-14 05:21 UTC, balapriyac commented on blog/_posts/2023-04-19-securing-kubernetes-secrets.md
> +Copy the **ca.crt* and *ca.key* securely (SCP) from the `/etc/kubernetes/pki` directory from your master node using the below command, you will need the *ca.crt* and *ca.key* on your local machine to
```suggestion
Copy the *ca.crt* and *ca.key* securely (SCP) from the `/etc/kubernetes/pki` directory from your master node using the below command, you will need the *ca.crt* and *ca.key* on your local machine to sign John's certificate:
```

2023-03-14 08:53 UTC, msali123 commented
Thanks Bala, changes done

Preview URL: https://6410358d9a3699619906c385--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-14 10:27 UTC, balapriyac commented
@jalletto this is ready to merge, too.

2023-03-15 16:46 UTC, jalletto approved these changes

2023-03-15 17:34 UTC, merged