Blog - Caching Dependencies on GitHub Actions
earthly/website pull request #376
Opened 2023-03-17 19:30 UTC by msali123

Done with all checks.

2023-03-17 19:37 UTC, msali123 commented
Preview URL: https://6414c12765f55019fd2045df--ephemeral-narwhal-3ac3b2.netlify.app

2023-03-21 03:35 UTC, balapriyac requested changes
Thanks, Sameer!

2023-03-21 03:35 UTC, balapriyac commented on blog/_posts/2023-04-28-caching-dependencies-github-actions.md
> +
```suggestion

Another thing you need to know prior to starting this tutorial is how access restrictions work for caches. Generally speaking, a workflow run will only be able to access a cache that was created in the current branch, the base branch of a pull request, or the default branch of the repository (or the repository it was forked from). 

In practice, this means that if you have a branch called `feature-b` that is based on another branch, `feature-a`, which in turn was based on the default branch `main`, a workflow run in `feature-b` will be able to access caches created in `feature-b`, `feature-a`, and `main`. Whereas a workflow run in `feature-a` will only be able to access caches created in `feature-a` and `main`. You can see a visual representation of this below:

```

2023-03-21 07:04 UTC, msali123 commented
Thanks @balapriyac 

Changes done: https://641956774638565bdcbc7711--ephemeral-narwhal-3ac3b2.netlify.app/blog/caching-dependencies-github-actions/

2023-03-21 07:56 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-03-23 14:29 UTC, jalletto approved these changes

2023-03-23 14:29 UTC, merged