Blog - Working With Zip Files in Go
earthly/website pull request #378
Opened 2023-03-20 15:27 UTC by msali123

Done with all checks.

2023-03-20 15:34 UTC, msali123 commented
Preview URL:
https://64187ca2df97a65dc82dfe59--ephemeral-narwhal-3ac3b2.netlify.app

@jalletto

2023-03-21 03:42 UTC, balapriyac commented
https://64187ca2df97a65dc82dfe59--ephemeral-narwhal-3ac3b2.netlify.app/blog/golang-zip-files/

2023-03-23 04:17 UTC, balapriyac requested changes
Thanks, Sameer.

2023-03-23 04:17 UTC, balapriyac commented on blog/_posts/2023-04-30-golang-zip-files.md
> +~~~{.bash caption="Output"}
```suggestion
~~~{ caption="Output"}
```

2023-03-23 04:17 UTC, balapriyac commented on blog/_posts/2023-04-30-golang-zip-files.md
> +Before running the code, create a new file named `*newfile.txt*` in the same directory as `*main.go*`. To check the output go to the terminal and run the following:
```suggestion
Before running the code, create a new file named `newfile.txt` in the same directory as `main3.go`. To check the output go to the terminal and run the following:
```

2023-03-23 09:15 UTC, msali123 commented
Thanks Bala, all changes done.

https://641c18256b738b10329ad233--ephemeral-narwhal-3ac3b2.netlify.app/blog/golang-zip-files/

2023-03-23 14:42 UTC, jalletto approved these changes

2023-03-23 14:42 UTC, merged