Blog - Working with GitHub Actions Environment Variables and Secrets
earthly/website pull request #379
Opened 2023-03-22 11:29 UTC by msali123

Done with all checks.

2023-03-22 11:37 UTC, msali123 commented
Preview URL: https://641ae7fd0df1570087554ee9--ephemeral-narwhal-3ac3b2.netlify.app/blog/github-actions-environment-variables-and-secrets/

2023-03-23 04:21 UTC, balapriyac requested changes
Looks great!

2023-03-23 04:21 UTC, balapriyac commented on blog/_posts/2023-05-02-github-actions-environment-variables-and-secrets.md
> +## What Are GitHub Actions Environment Variables and Secrets
```suggestion
## What Are GitHub Actions Environment Variables and Secrets?
```

2023-03-23 11:05 UTC, balapriyac commented
@jalletto this is ready to merge, too.

2023-03-23 14:44 UTC, jalletto approved these changes

2023-03-23 14:44 UTC, merged