Blog - Managing Dependencies using Poetry in Python
earthly/website pull request #388
Opened 2023-03-30 11:42 UTC by msali123

Done with all checks.

2023-03-30 13:50 UTC, balapriyac commented
Thanks, Sameer. Will review this tomorrow morning.

2023-03-31 03:03 UTC, balapriyac requested changes
As always, looks great! Just requested a couple small changes.

2023-03-31 03:03 UTC, balapriyac commented on blog/_posts/2023-05-08-python-poetry.md
> +~~~{ caption="file-hirarechy"}
```suggestion
~~~{ caption=" "}
```

2023-03-31 03:03 UTC, balapriyac commented on blog/_posts/2023-05-08-python-poetry.md
> +> The default dependencies for a project in Poetry consist of two types of dependencies: the dependencies specified in the `tool.poetry.dependencies` table of the `pyproject.toml` file and the depend
```suggestion
The default dependencies for a project in Poetry consist of two types of dependencies: the dependencies specified in the `tool.poetry.dependencies` table of the `pyproject.toml` file and the dependencies specified in the non-optional groups.
```

2023-03-31 06:23 UTC, balapriyac requested changes

2023-03-31 06:23 UTC, balapriyac commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
```suggestion
{% include cta/cta2.html %}
```

2023-03-31 06:23 UTC, balapriyac commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
There's an enhanced CTA, cta2. Let's use that going forward. :)

2023-03-31 13:47 UTC, msali123 commented
https://6426e4002bba3e25582c0adf--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/
Changes done

2023-03-31 13:48 UTC, msali123 commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
@balapriyac this isnt working

2023-03-31 14:06 UTC, balapriyac commented
Oh, okay, Sameer. Please ignore that suggestion. I saw {% include_html
cta/cta2.html %} in the updated posts. So I thought it'd work.

On Fri, Mar 31, 2023 at 7:18 PM Muhammad Sameer Ali <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In blog/_posts/2023-05-08-python-poetry.md
> <https://github.com/earthly/website/pull/388#discussion_r1154500222>:
>
> > +Once you have packaged your library, you can publish it using the `publish` command:
> +
> +~~~{.bash caption=">_"}
> +poetry publish
> +~~~
> +
> +The command will publish the package to the Python Package Index (PyPI), making them available for installation through Poetry.
> +After publishing the package, you can search for it on PyPI. For example, you can find the `weather-update` library [PYPI](https://pypi.org/project/weather-update/). You can then install it on your system and try using it.
> +
> +## Conclusion
> +
> +Managing dependencies in Python development is crucial for ensuring the stability and [reliability](/blog/achieving-repeatability) of your projects. Poetry offers a convenient and efficient solution for handling dependencies, making it a popular choice among Python developers.
> +
> +In this tutorial, you have explored the steps involved in using Poetry for managing dependencies in Python projects, from installation to publishing a package. Specifically, you have learned the creation of virtual environments, managing dependencies, including adding, removing, and synchronizing them, and publishing a Python project as a package. You can explore much more about Poetry in its [official documentation](https://python-poetry.org/).
> +
> +{% include cta/cta1.html %}
>
> @balapriyac <https://github.com/balapriyac> this isnt working
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/earthly/website/pull/388#discussion_r1154500222>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALIW4EZZPKVMWJC6QSJ4BTDW63ODDANCNFSM6AAAAAAWNFOZWA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-31 14:11 UTC, msali123 commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
![image](https://user-images.githubusercontent.com/32276372/229144397-540d0ce6-9a67-4c73-ac9c-9b3a10397ca0.png)

2023-03-31 14:32 UTC, balapriyac commented
@jalletto The updated CTA isn't appearing. Besides that, the article is ready to merge.

> https://6426e4002bba3e25582c0adf--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/ Changes done

Hi Sameer, can you please add the most recent preview?

2023-03-31 15:16 UTC, msali123 commented
https://6426e4002bba3e25582c0adf--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/


This is the most recent preview @balapriyac

2023-03-31 15:33 UTC, msali123 commented
https://6426fc4c4aa11702f4b1dc19--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/

@balapriyac Preview the old CTA

2023-03-31 15:50 UTC, jalletto commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
```suggestion
{% include_html cta/cta1.html %}
```

2023-03-31 15:51 UTC, jalletto requested changes

2023-03-31 15:51 UTC, jalletto commented on blog/_posts/2023-05-08-python-poetry.md
> +{% include cta/cta1.html %}
I don't know the reason for this exactly, but now you need to do include_html for this to work.

2023-04-01 00:05 UTC, msali123 commented
@balapriyac @jalletto updated Preview [Link](https://64277437a714791625aeef3f--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/) with {% include_html cta/cta2.html %}

2023-04-03 05:00 UTC, balapriyac requested changes
@msali123 there's one code block caption that I missed in the previous round of review.

2023-04-03 05:00 UTC, balapriyac commented on blog/_posts/2023-05-08-python-poetry.md
> +~~~{.python caption="weather.py"}
```suggestion
~~~{.python caption="main.py"}
```

2023-04-03 09:05 UTC, msali123 commented
Done @balapriyac 
[Link](https://642a9632ab8bc450333e3e8e--ephemeral-narwhal-3ac3b2.netlify.app/blog/python-poetry/)

2023-04-03 09:32 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-04 16:38 UTC, jalletto approved these changes

2023-04-04 16:39 UTC, merged