Blog - Using Bazel to Improve Your Automated Test Suite
earthly/website pull request #398
Opened 2023-04-03 11:48 UTC by msali123

Done with all checks.

2023-04-03 11:59 UTC, msali123 commented
[Link](https://642abe7136db807d99e41245--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-and-automated-tests/)
@balapriyac

2023-04-03 12:02 UTC, msali123 commented
![image](https://user-images.githubusercontent.com/32276372/229502850-0091447e-cd8b-4149-b154-e332df25a0c6.png)
![image](https://user-images.githubusercontent.com/32276372/229502986-d919f751-0f13-415f-99de-bc0401f8e259.png)

@jalletto there's an issue when I use "$0" it doesnt recognizes the code block due to error but as I use '$0' its working

The Preview link up is with  '$0'

2023-04-05 05:31 UTC, balapriyac requested changes
Thanks, Sameer. I've suggested a few changes.

2023-04-05 05:31 UTC, balapriyac commented on blog/_posts/2023-05-17-bazel-and-automated-tests.md
> +~~~
```suggestion
~~~{ caption = "Output"}
```

2023-04-05 05:31 UTC, balapriyac commented on blog/_posts/2023-05-17-bazel-and-automated-tests.md
> +~~~{ caption="WORKSPACE.bazel"}
```suggestion
~~~{ caption="WORKSPACE"}
```

2023-04-05 05:31 UTC, balapriyac commented on blog/_posts/2023-05-17-bazel-and-automated-tests.md
> +~~~{ caption="WORKSPACE.bazel"}
`WORKSPACE` file is a text file containing the dependencies and the like.

2023-04-05 05:31 UTC, balapriyac commented on blog/_posts/2023-05-17-bazel-and-automated-tests.md
> +![success]({{site.images}}{{page.slug}}/success.png)\
Nice image!

2023-04-05 05:31 UTC, balapriyac commented on blog/_posts/2023-05-17-bazel-and-automated-tests.md
> +~~~{ caption="Output}
```suggestion
~~~{ caption="Output"}
```

2023-04-05 11:20 UTC, msali123 commented
@balapriyac 
[Changes done](https://642d58cd106c02196d3b07fe--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-and-automated-tests/)

2023-04-05 13:16 UTC, balapriyac commented
@jalletto Sameer faced a problem with " in the test run output, so he used ' instead. This is ready to merge otherwise.

2023-04-07 14:07 UTC, jalletto approved these changes

2023-04-07 14:07 UTC, merged