Blog - Load Testing Backend Services Using K6
earthly/website pull request #399
Opened 2023-04-03 13:27 UTC by msali123

Done with all checks.

2023-04-03 13:43 UTC, msali123 commented
@balapriyac  @jalletto 

[Preview Link](https://642ad78788895510a66a413d--ephemeral-narwhal-3ac3b2.netlify.app/blog/load-testing-using-k6/)

2023-04-05 04:35 UTC, balapriyac requested changes
Thanks Sameer. Suggested a few formatting edits.

2023-04-05 04:35 UTC, balapriyac commented on blog/_posts/2023-05-20-load-testing-using-k6.md
> +~~~
```suggestion

~~~{.bash caption=">_"}
CREATE DATABASE blogFastAPI;
~~~
```

2023-04-05 04:35 UTC, balapriyac commented on blog/_posts/2023-05-20-load-testing-using-k6.md
> +
```suggestion

~~~{.bash caption=">_"}
CREATE TABLE blog (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  content VARCHAR(5000) NOT NULL
);


CREATE TABLE user_info(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(500) NOT NULL,
  fullname VARCHAR(50) NOT NULL
);

~~~

```

2023-04-05 04:35 UTC, balapriyac commented on blog/_posts/2023-05-20-load-testing-using-k6.md
> +
```suggestion

~~~{.bash caption=">_"}
USER = os.getenv('DB_USER')
PASSWORD = os.getenv('DB_PASSWORD')

SQLALCHEMY_DATABASE_URL = (f"mysql+mysqlconnector://{USER}:{PASSWORD}@localhost:3306/blogFastAPI")
~~~

```

2023-04-05 11:07 UTC, msali123 commented
Changes done @balapriyac 
[Preview Link](https://642d55f521493d1559909d6b--ephemeral-narwhal-3ac3b2.netlify.app/blog/load-testing-using-k6/)

2023-04-05 13:18 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-07 14:09 UTC, jalletto approved these changes

2023-04-07 14:21 UTC, merged