Blog - External Secret Operators (ESO) with HashiCorp Vault
earthly/website pull request #401
Opened 2023-04-04 00:07 UTC by msali123

Done with all checks.

2023-04-04 01:03 UTC, msali123 commented
[Preview Link](https://642b767dab8bc42cee3e3da5--ephemeral-narwhal-3ac3b2.netlify.app/blog/eso-with-hashicorp-vault/)

@balapriyac

2023-04-05 04:45 UTC, balapriyac requested changes
Thanks, Sameer.

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +![how eso works with vault]({{site.images}}{{page.slug}}/7Qinp9m.png)
```suggestion
![How ESO Works with Vault]({{site.images}}{{page.slug}}/7Qinp9m.png)
```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion

Create a [`hcl` file](https://hub.packtpub.com/what-is-hcl-hashicorp-configuration-language-how-does-it-relate-to-terraform-and-why-is-it-growing-in-popularity/) and paste in the following configuration settings, you can name this file what you want, this tutorial uses `vault-config.hcl`.

```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion

Create the `vault` directory that vault will use to store the data when running in server mode with the [`raft` storage backend](https://developer.hashicorp.com/vault/docs/configuration/storage/raft):

```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion

To use the External Secret operator, you need to first install it in your Kubernetes cluster. We will install it via [Helm](https://earthly.dev/blog/helm-k8s-mngr/). You can check for other means of [installation guide](https://external-secrets.io/v0.7.2/introduction/getting-started/).

```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion
This command installs the *external-secrets* package using the Helm package manager. The package is sourced from the *external-secrets* repository and the installation process creates a new namespace named *external-secrets* and sets the *installCRDs* option to *true* so the Custom Resource Definitions for External Secrets Operator are installed with it (the *ClusterSecretStore*, *SecretStore* and *ExternalSecret* CRDs).
```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion



```

2023-04-05 04:45 UTC, balapriyac commented on blog/_posts/2023-05-23-eso-with-hashicorp-vault.md
> +
```suggestion

- The **`ExternalSecret`** resource specifies the interval at which to refresh the target secret, the name of the **`ClusterSecretStore`** that contains the secret, the target secret to be updated and the properties in the remote secret that will be mapped to the target secret.
- The **`target`** field specifies the name of the target Kubernetes secret that the external secret data will be written to and the policy for creating it if it does not already exist.
- The **`data`** field maps the properties in the remote secret to the target secret.

```

2023-04-05 11:34 UTC, msali123 commented
@balapriyac 
[Done](https://642d5c5e7b8e351bfdf7064f--ephemeral-narwhal-3ac3b2.netlify.app/blog/eso-with-hashicorp-vault/)

2023-04-05 13:20 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-07 14:30 UTC, jalletto approved these changes

2023-04-07 14:31 UTC, merged