Blog - Deploy Applications to AWS ECR with a GitHub Actions CI/CD Pipeline
earthly/website pull request #404
Opened 2023-04-05 15:10 UTC by msali123

2023-04-05 15:23 UTC, msali123 commented
[Preview Link](https://642d91f2106c0251973b0c71--ephemeral-narwhal-3ac3b2.netlify.app/blog/aws-ecr-github-actions/)
@balapriyac

2023-04-06 03:05 UTC, balapriyac requested changes
Thanks, Sameer. Just a couple small changes.

2023-04-06 03:05 UTC, balapriyac commented on blog/_posts/2023-05-25-aws-ecr-github-actions.md
> +Before proceeding with this guide, you require the following:
```suggestion
To follow along with this guide, you require the following:
```

2023-04-06 03:05 UTC, balapriyac commented on blog/_posts/2023-05-25-aws-ecr-github-actions.md
> +
```suggestion

Deploying applications to AWS ECR with a GitHub Actions CI/CD creates a reliable pipeline that automates Docker builds and [deployment](/blog/deployment-strategies) cycles. This guide helped you learn how to deploy an application to AWS ECR using a GitHub Actions CI/CD pipeline. I hope you found the GitHub Actions workflow useful while leveraging automation to AWS resources.

To further improve your [CI/CD pipelines](https://earthly.dev/blog/ci-vs-cd/), leverage other AWS services, such as [CodePipeline](https://aws.amazon.com/codedeploy/) and [CodeDeploy](https://aws.amazon.com/codepipeline/), and streamline your pipeline infrastructure.

```

2023-04-07 11:57 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-07 14:44 UTC, jalletto approved these changes

2023-04-07 14:44 UTC, merged