Blog - Error Handling in Python
earthly/website pull request #409
Opened 2023-04-06 11:06 UTC by msali123

Done with all checks.

2023-04-06 11:16 UTC, msali123 commented
[Preview Link](https://642ea8f20a8d0d21449ef959--ephemeral-narwhal-3ac3b2.netlify.app/blog/error-handling-in-python/)

@balapriyac

2023-04-07 03:29 UTC, balapriyac requested changes

2023-04-07 03:29 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +
```suggestion
      This is shown in the code below:

      ~~~{.python caption="error-handling-in-python.ipynb"}
      try:
          with open('example.txt') as f:
              data = f.read()
      except (FileNotFoundError, PermissionError) as e:
          print(f"Error: {e}")
      ~~~

```

2023-04-07 03:29 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +
```suggestion

~~~{.python caption="error-handling-in-python.ipynb"}
try:
    with open("file.txt") as f:
        content = f.read()
    num = int("abc")
except FileNotFoundError:
    print("File not found!")
except ValueError:
    print("Invalid value!")
~~~

```

2023-04-07 03:29 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +    num = 10 / value
```suggestion
~~~{.python caption="error-handling-in-python.ipynb"}
try:
    with open("example.txt", "r") as file:
        contents = file.read()
    value = int(input("enter a number: "))
    num = 10 / value
```

2023-04-07 03:37 UTC, balapriyac requested changes
Thanks, Sameer. Suggested a few changes.

2023-04-07 03:37 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +~~~
```suggestion
~~~{.python caption="error-handling-in-python.ipynb"}
def get_element(data, index):
    if index >= len(data):
        raise IndexError("Index out of range")
    return data[index]
~~~
```

2023-04-07 03:37 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +~~~
```suggestion
finally:
    if file:
         file.close()
~~~
```

2023-04-07 03:37 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +           os.remove("file.txt")
```suggestion
    if file:
          file.close()
    if os.path.exists("file.txt"):
          os.remove("file.txt")
```

2023-04-07 03:37 UTC, balapriyac commented on blog/_posts/2023-05-28-error-handling-in-python.md
> +The code for this article can be found on [GitHub](https://github.com/Boadzie/error-handling-in-python)
```suggestion
The code for this article can be found on [GitHub](https://github.com/Boadzie/error-handling-in-python).
```

2023-04-07 10:51 UTC, msali123 commented
@balapriyac 
[Changes Done](https://642ff5352eb8b01bbcdb303d--ephemeral-narwhal-3ac3b2.netlify.app/blog/error-handling-in-python/)

2023-04-07 11:58 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-07 15:46 UTC, jalletto approved these changes

2023-04-07 15:46 UTC, merged