Blog - How the Docker Image Is Stored on the Host Machine
earthly/website pull request #410
Opened 2023-04-06 20:25 UTC by msali123

2023-04-06 21:06 UTC, msali123 commented
@balapriyac 

[Preview Link](https://642f3387ae0432063a6df2c0--ephemeral-narwhal-3ac3b2.netlify.app/blog/docker-image-storage-on-host/)

Also please have a look at **ChainID Calculation** if it content looks right?

2023-04-07 03:45 UTC, balapriyac commented
> @balapriyac
> 
> [Preview Link](https://642f3387ae0432063a6df2c0--ephemeral-narwhal-3ac3b2.netlify.app/blog/docker-image-storage-on-host/)
> 
> Also please have a look at **ChainID Calculation** if it content looks right?

Yeah, the ChainID part is correct in terms of the content. The ID is of length 64 so it'll anyways extend to the next line. I'll suggest some formatting edits. Let's see if it makes it look better.

2023-04-07 03:52 UTC, balapriyac requested changes
Looks great. Suggested a few formatting edits.

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +DiffID = chainID if the layer is the lowest layer among other layers.
```suggestion
**DiffID = ChainID** if the layer is the lowest layer among other layers.
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +If not, chainID(n) = sha256sum [diffID(n-1), diffID(n)]
```suggestion
If not, **ChainID(n) = sha256sum [DiffID(n-1), DiffID(n)]**
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +**Let's calculate the ChainID for Layer-1:**
```suggestion
**Let's calculate the ChainID for Layer 1:**
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +ChainID(Layer-1) = diffID(Layer-1)
```suggestion
ChainID(Layer 1) = DiffID(Layer 1)
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +ChainID(Layer-1) = d3cc7b6aa7bc15725c1a856ce06fe436da3fbccf0c9c06b04e45f79b3439c154
```suggestion
ChainID(Layer 1) = d3cc7b6aa7bc15725c1a856ce06fe436da3fbccf0c9c06b04e45f79b3439c154
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +ChainID(Layer-2) = sha256sum [diffID(Layer-1), diffID(Layer-2)
```suggestion
ChainID(Layer 2) = sha256sum [DiffID(Layer 1), DiffID(Layer 2)
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +diffID(Layer-1) = d3cc7b6aa7bc15725c1a856ce06fe436da3fbccf0c9c06b04e45f79b3439c154
```suggestion
DiffID(Layer 1) = d3cc7b6aa7bc15725c1a856ce06fe436da3fbccf0c9c06b04e45f79b3439c154
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +diffID(Layer-2) = a7f421510691bf6a7b344d1efb738b3d343e252e7dde114a0dd86d432ef6000c
```suggestion
DiffID(Layer 2) = a7f421510691bf6a7b344d1efb738b3d343e252e7dde114a0dd86d432ef6000c
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +ChainID(Layer-3) = 9b3abbf0ab6402c9bcb9cce411268ffe24573d790f0333d8ae06794313295dbd
```suggestion
ChainID(Layer 3) = 9b3abbf0ab6402c9bcb9cce411268ffe24573d790f0333d8ae06794313295dbd
```

2023-04-07 03:52 UTC, balapriyac commented on blog/_posts/2023-05-31-docker-image-storage-on-host.md
> +
```suggestion
~~~

ChainID(Layer 2) = 29bd3d7c6e1683e422776b9d3285e8a3f1272f07656fc63a941cb7729a169100

**Next, let's calculate the ChainID for Layer 3:**

ChainID(Layer 3) = sha256sum [DiffID(Layer 2), DiffID(Layer 3)

DiffID(Layer 2) = a7f421510691bf6a7b344d1efb738b3d343e252e7dde114a0dd86d432ef6000c
DiffID(Layer 3) = 6ac2db160c6cf3dcf1aff0ced069aa98da28c50cff5cd3c8881c04f42e3ef1fe

```

2023-04-07 11:07 UTC, msali123 commented
@balapriyac 
[Changes done](https://642ff8dfb8a2f621e7d34dd5--ephemeral-narwhal-3ac3b2.netlify.app/blog/docker-image-storage-on-host/)

2023-04-07 11:59 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-07 15:57 UTC, jalletto approved these changes

2023-04-07 15:57 UTC, merged