Blog -Docker Image Optimization Strategies: How to Minimize Docker Images
earthly/website pull request #417
Opened 2023-04-13 10:16 UTC by msali123

Done with all checks.

2023-04-13 18:30 UTC, jalletto requested changes
@msali123 Great job! Just a couple things.

2023-04-13 18:30 UTC, jalletto commented on blog/_posts/2023-06-07-minimize-docker-images-size.md
> +Dockerfiles form the foundation for building Docker images. They specify the necessary instructions for Docker to package your application. Traditionally, applications follow the [build pattern](http
```suggestion
Dockerfiles form the foundation for building Docker images. They specify the necessary instructions for Docker to package your application. Traditionally, applications follow the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) to bundle their assets, meaning that you need to build the application code to determine how it will be served in the production environment.
```

2023-04-13 18:30 UTC, jalletto commented on blog/_posts/2023-06-07-minimize-docker-images-size.md
> +The base image is the starting point for creating a Docker image, and it typically includes the underlying operating system as well as any necessary software and [packages](/blog/setup-typescript-mon
```suggestion
The base image is the starting point for creating a Docker image, and it typically includes the underlying operating system as well as any necessary software and packages. Common base images for Docker include Alpine Linux, Ubuntu, Debian, CentOS, and Fedora. When running a Node.js application in Docker, one common base image is the [official Node.js](https://hub.docker.com/_/node)  image available on Docker Hub. However, Node.js provides other variant image distributions with different tags that result in slimmer Docker base images. These tags include:
```

2023-04-13 18:30 UTC, jalletto commented on blog/_posts/2023-06-07-minimize-docker-images-size.md
> +The base image is the starting point for creating a Docker image, and it typically includes the underlying operating system as well as any necessary software and [packages](/blog/setup-typescript-mon
A lot of times the `link`function suggests links that don't make sense to include. It's not the smartest function. I just offers suggestions. In this case, the link to the monorepo blog isn't really relevant to what we are talking about, so we can remove it.

2023-04-13 18:30 UTC, jalletto commented on blog/_posts/2023-06-07-minimize-docker-images-size.md
> +- Using the .dockerignore file
```suggestion
- Using the `.dockerignore` file
```

2023-04-13 20:50 UTC, msali123 commented on blog/_posts/2023-06-07-minimize-docker-images-size.md
> +The base image is the starting point for creating a Docker image, and it typically includes the underlying operating system as well as any necessary software and [packages](/blog/setup-typescript-mon
Okay sure @jalletto noted. Same many time this happens with work `make`

2023-04-14 15:41 UTC, jalletto approved these changes

2023-04-14 15:42 UTC, merged