Blog - Using Terraform with GitHub Actions
earthly/website pull request #418
Opened 2023-04-13 12:49 UTC by msali123

Done with all checks.

2023-04-13 18:40 UTC, jalletto requested changes
@msali123 just a few changes

2023-04-13 18:40 UTC, jalletto commented on blog/_posts/2023-06-12-terraform-with-github-actions.md
> +[GitHub Actions](https://github.com/features/actions) is a powerful tool that allows software developers to automate almost everything inside a [GitHub](/blog/ci-comparison) repository. From running
```suggestion
[GitHub Actions](https://github.com/features/actions) is a powerful tool that allows software developers to automate almost everything inside a GitHub repository. From running tests to linting your code, to automatically commenting on pull requests and issues, it's a complete solution that helps projects of all kinds to operate more efficiently.
```

2023-04-13 18:40 UTC, jalletto commented on blog/_posts/2023-06-12-terraform-with-github-actions.md
> +[GitHub Actions](https://github.com/features/actions) is a powerful tool that allows software developers to automate almost everything inside a [GitHub](/blog/ci-comparison) repository. From running
Again, we need to watch what we link out to. It should be related to what we are talking about. This article does talk about GA, but unless we are talking about speed or how it compares to other CI, this is a stretch.

2023-04-13 18:40 UTC, jalletto commented on blog/_posts/2023-06-12-terraform-with-github-actions.md
> +In this article, you'll learn how GitHub Actions and [Terraform](/blog/kubernetes-terraform) work together so that you can benefit from this powerful combination.
```suggestion
In this article, you'll learn how GitHub Actions and Terraform work together so that you can benefit from this powerful combination.
```

2023-04-13 18:40 UTC, jalletto commented on blog/_posts/2023-06-12-terraform-with-github-actions.md
> +Once you have all that configured, head over to the [**Tokens** page](https://app.terraform.io/app/settings/tokens) and generate an API token. This is what you'll use to connect GitHub Actions to [Te
```suggestion
Once you have all that configured, head over to the [**Tokens** page](https://app.terraform.io/app/settings/tokens) and generate an API token. This is what you'll use to connect GitHub Actions to Terraform Cloud, so make sure you store this information in a safe place.
```

2023-04-13 20:54 UTC, msali123 commented on blog/_posts/2023-06-12-terraform-with-github-actions.md
> +[GitHub Actions](https://github.com/features/actions) is a powerful tool that allows software developers to automate almost everything inside a [GitHub](/blog/ci-comparison) repository. From running
Noted @jalletto

2023-04-13 21:14 UTC, msali123 commented
[Changes done](https://64386f8965d06f271b915d4c--ephemeral-narwhal-3ac3b2.netlify.app/blog/terraform-with-github-actions/)

2023-04-14 16:50 UTC, jalletto approved these changes

2023-04-14 16:50 UTC, merged