Blog - Linux Text Processing Command
earthly/website pull request #419
Opened 2023-04-13 13:00 UTC by msali123

Done with all checks.

2023-04-13 19:36 UTC, jalletto requested changes

2023-04-13 19:36 UTC, jalletto commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +Let's take another example of installing [docker](/blog/rails-with-docker) on our system with the easy endpoint that Docker provide:
```suggestion
Let's take another example of installing docker on our system with the easy endpoint that Docker provide:
```

2023-04-13 19:36 UTC, jalletto commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +
```suggestion
<div class="notice--info">
We have a whole post on [Understanding Awk](/blog/awk-examples/) if you'd like to learn more.
</div>
```

2023-04-13 19:36 UTC, jalletto commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +
Can you add this and confirm it looks ok locally?

2023-04-13 19:36 UTC, jalletto commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +
```suggestion
<div class="notice--info">
We have a whole post on [Using sed for Find and Replace](/blog/sed-find-replace/) if you'd like to learn more.
</div>
```

2023-04-13 19:36 UTC, jalletto commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +A use case can be in inspecting your [container](/blog/docker-slim) image:
```suggestion
A use case can be in inspecting your container image:
```

2023-04-13 21:09 UTC, msali123 commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +
![image](https://user-images.githubusercontent.com/32276372/231883371-55f93375-1651-4bcc-b377-b42b5cb80f73.png)

@jalletto seems good

2023-04-13 21:12 UTC, msali123 commented on blog/_posts/2023-06-10-linux-text-processing-commands.md
> +
![image](https://user-images.githubusercontent.com/32276372/231883784-06131a8d-c3c4-42e2-aa13-473c609f8d72.png)

Preview image

2023-04-13 21:26 UTC, msali123 commented
@jalletto [Preview Link](https://6438725ca4c56128a20d5d85--ephemeral-narwhal-3ac3b2.netlify.app/blog/linux-text-processing-commands/)

2023-04-14 17:13 UTC, jalletto approved these changes

2023-04-14 17:15 UTC, merged