Blog - Using GitHub Actions to Run, Test, Build, and Deploy Docker Containers
earthly/website pull request #420
Opened 2023-04-13 14:45 UTC by msali123

Done with all checks.

2023-04-13 15:01 UTC, msali123 commented
@balapriyac 

[Preview Link](https://643818d060ad1b0606b6009c--ephemeral-narwhal-3ac3b2.netlify.app/blog/github-actions-and-docker/)

2023-04-13 20:33 UTC, jalletto requested changes

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +In this article, you'll learn how to use [Github Actions](/blog/continuous-integration) to run, test, build, and deploy Docker containers using GitHub Actions.
```suggestion
In this article, you'll learn how to use Github Actions to run, test, build, and deploy Docker containers using GitHub Actions.
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +Once these prerequisites are met, it's time to begin. You'll start by creating a sample workflow, and then set a runner for the workflow. After that, you'll learn how to set up [GitHub](/blog/ci-comp
```suggestion
Once these prerequisites are met, it's time to begin. You'll start by creating a sample workflow, and then set a runner for the workflow. After that, you'll learn how to set up GitHub Actions locally and then how to set up the build and test stage. Finally, you'll execute the workflow by running the action.
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +The first thing you need to do is create a workflow using GitHub Actions. This workflow defines the steps that GitHub Actions should take when triggered, including checking out the code, building a D
```suggestion
The first thing you need to do is create a workflow using GitHub Actions. This workflow defines the steps that GitHub Actions should take when triggered, including checking out the code, building a Docker container, running tests, and deploying the application.
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +Once you're done setting up the build stage, the next thing you need to do is set up the test stage. Because the **Deploy to Amazon ECS** workflow template is primarily a [deployment](/blog/deploymen
```suggestion
Once you're done setting up the build stage, the next thing you need to do is set up the test stage. Because the **Deploy to Amazon ECS** workflow template is primarily a deployment template, the test stage isn't factored into it. However, the test stage is the recommended phase since it helps you verify the functionality and connections of your applications (including the workflow file) before pushing to GitHub to run the workflow actions.
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +The purpose of this network is to provide a Docker network for the containers defined in the `docker-compose` file, allowing them to communicate with each other and with the host system. Containers i
```suggestion
The purpose of this network is to provide a Docker network for the containers defined in the `docker-compose` file, allowing them to communicate with each other and with the host system. Containers in separate networks cannot communicate, which means that API test cases won't be able to get a response from the services in other networks. You can learn more about creating a `docker-compose` file with a network [in this article](/blog/docker-networking).
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +When you're done adding the test cases folder to the same [container](/blog/docker-slim) network, you need to add a new value to the `steps` key of your workflow file. The new value will contain a `n
```suggestion
When you're done adding the test cases folder to the same container network, you need to add a new value to the `steps` key of your workflow file. The new value will contain a `name`, `id`, and `run` key:
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +In this tutorial, you learned how to create a new workflow, edit an existing workflow, set up the runner for your workflow, and locally set up and work with GitHub Actions. At this point, you should
```suggestion
In this tutorial, you learned how to create a new workflow, edit an existing workflow, set up the runner for your workflow, and locally set up and work with GitHub Actions. At this point, you should be confident that you can build Github Actions for your projects and speed up the development processes.
```

2023-04-13 20:33 UTC, jalletto commented on blog/_posts/2023-06-15-github-actions-and-docker.md
> +
```suggestion
If you want to see how Github Actions stacks up against other CI services, check out our comparison of [CI Free Tiers](/blog/ci-comparison).
```

2023-04-13 21:44 UTC, msali123 commented
[Changes done](https://6438772171151a2d8adafe92--ephemeral-narwhal-3ac3b2.netlify.app/blog/github-actions-and-docker/)

2023-04-14 17:19 UTC, jalletto approved these changes

2023-04-14 17:35 UTC, merged