Blog - AWS ECS Tutorial: Running Your Containers on Amazon
earthly/website pull request #422
Opened 2023-04-17 21:23 UTC by msali123

Done with all checks.

2023-04-17 21:43 UTC, msali123 commented
@balapriyac  [Preview Link](https://643dbcc3ff47f5085c4ce708--ephemeral-narwhal-3ac3b2.netlify.app/blog/aws-ecs-tutorial/)

2023-04-18 05:43 UTC, balapriyac requested changes
Thanks, Sameer. Suggested some minor changes.

2023-04-18 05:43 UTC, balapriyac commented on blog/_posts/2023-06-17-aws-ecs-tutorial.md
> +[Docker](https://www.docker.com) is a popular containerization solution because it allows you to build, test, deploy, and run applications within containers quickly. In combination with [Amazon Elast
```suggestion
Docker is a popular containerization solution because it allows you to build, test, deploy, and run applications within containers quickly. In combination with [Amazon Elastic Container Service (Amazon ECS)](https://aws.amazon.com/ecs/), which allows you to deploy, manage, and scale containerized applications, you can efficiently coordinate and manage your containers.
```

2023-04-18 05:43 UTC, balapriyac commented on blog/_posts/2023-06-17-aws-ecs-tutorial.md
> +An [ECS](/blog/how-to-setup-and-use-amazons-elastic-container-registry)  Service is a way to define and run a group of related Docker containers on an Amazon Elastic Compute Cloud (EC2) or Fargate cl
```suggestion
An [ECS](/blog/how-to-setup-and-use-amazons-elastic-container-registry) Service is a way to define and run a group of related Docker containers on an Amazon Elastic Compute Cloud (EC2) or Fargate cluster.
```

2023-04-18 05:43 UTC, balapriyac commented on blog/_posts/2023-06-17-aws-ecs-tutorial.md
> +If the service [deployment](/blog/deployment-strategies) goes through successfully, it will notify you and run the task:
```suggestion
If the service deployment goes through successfully, it will notify you and run the task:
```

2023-04-18 05:43 UTC, balapriyac commented on blog/_posts/2023-06-17-aws-ecs-tutorial.md
> +To optimize your container environment and improve your development workflow, you may want to explore other [CI/CD](/blog/ci-vs-cd) tools such as [Earthly](https://earthly.dev/). One of the primary b
```suggestion
To optimize your container environment and improve your development workflow, you may want to explore other CI/CD tools such as [Earthly](https://earthly.dev/). One of the primary benefits of Earthly is that it focuses on developer productivity—which means developers can focus on core development instead of orchestration. This, ultimately, streamlines the development process and reduces the time and effort required to build and deploy containerized applications.
```

2023-04-18 17:51 UTC, msali123 commented
@balapriyac [changes done](https://643ed8473b8c18005b135568--ephemeral-narwhal-3ac3b2.netlify.app)

I was facing unsuccessful builds so needed to do some extra commits.

2023-04-19 02:14 UTC, balapriyac commented
@jalletto this PR is ready to merge.

2023-04-21 20:05 UTC, jalletto approved these changes

2023-04-21 20:06 UTC, merged