Blog - Using Bazel with Rust to Build and Deploy an Application
earthly/website pull request #424
Opened 2023-04-17 23:33 UTC by msali123

Done with all checks.

2023-04-17 23:46 UTC, msali123 commented
@balapriyac [Preview Link](https://643dd9dccdb7092557fa4d4e--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-with-rust/)

2023-04-18 05:50 UTC, balapriyac requested changes
Thanks, Sameer. Suggested a few changes.

2023-04-18 05:50 UTC, balapriyac commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +Building and deploying software can be a complicated and time-consuming process, especially as applications grow in size and complexity. One tool that can help simplify this process is [Bazel](https:
```suggestion
Building and deploying software can be a complicated and time-consuming process, especially as applications grow in size and complexity. One tool that can help simplify this process is [Bazel](https://bazel.build), an open-source build tool developed by Google. Bazel is designed to make it easy to build and test large and complex codebases and is particularly well-suited for monorepos, which are codebases that contain multiple projects or components.
```

2023-04-18 05:50 UTC, balapriyac commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +One of the key features of Bazel is its ability to speed up builds and tests. Bazel's caching and dependency analysis features facilitate fast, incremental builds. This makes it possible to quickly i
```suggestion
One of the key features of Bazel is its ability to speed up builds and tests. Bazel's caching and dependency analysis features facilitate fast, incremental builds. This makes it possible to quickly iterate on code changes, which can be especially useful for large teams working on a codebase. Additionally, Bazel supports multiple languages and platforms, including Rust, and can be extended to support new languages.
```

2023-04-18 05:50 UTC, balapriyac commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +title: "Using Bazel with Rust to Build and Deploy an Application"
Hi Sameer,
Could you please change the header image? Maybe we can have Bazel and Rust logos or something like that?

2023-04-18 05:50 UTC, balapriyac commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +When building a Rust project with [Bazel](/blog/bazel-build), the following command is used for building and running build targets. Try running this command in the terminal inside your current direct
```suggestion
When building a Rust project with [Bazel](/blog/bazel-build), the following command is used for building and running build targets. Try running this command in the terminal inside your current directory:
```
```suggestion
When building a Rust project with Bazel, the following command is used for building and running build targets. Try running this command in the terminal inside your current directory:
```

2023-04-18 05:50 UTC, balapriyac commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +> **Please note:** It's important to keep the Rust version in sync across all the developers working on the project, as different versions of Rust can cause compatibility issues and build errors.
```suggestion
<div class="notice--info">
It's important to keep the Rust version in sync across all the developers working on the project, as different versions of Rust can cause compatibility issues and build errors.
</div>
```

2023-04-18 18:04 UTC, msali123 commented on blog/_posts/2023-06-19-bazel-with-rust.md
> +title: "Using Bazel with Rust to Build and Deploy an Application"
done Bala.

2023-04-18 18:29 UTC, msali123 commented
@balapriyac [Changes Done](https://643edd3c133173027429f752--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-with-rust/)

2023-04-19 02:13 UTC, balapriyac commented
@jalletto this PR is ready to merge!

2023-04-21 20:08 UTC, jalletto approved these changes

2023-04-21 20:08 UTC, merged