Blog - How to set up a Reverse Proxy in Kubernetes
earthly/website pull request #427
Opened 2023-04-19 12:35 UTC by msali123

Draft

2023-04-20 02:21 UTC, msali123 commented
@balapriyac 
You can review the blog just one image is missing ill as I get from the author

[Preview Link](https://643fe19ac427180f7380fb27--ephemeral-narwhal-3ac3b2.netlify.app/blog/setup-reverse-proxy-kubernetes-nginx/)

2023-04-20 04:50 UTC, balapriyac requested changes
Thanks, Sameer. Please go through the requested changes.

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +title: "How to set up a Reverse Proxy in Kubernetes"
```suggestion
title: "How to Set Up a Reverse Proxy in Kubernetes"
```

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +In this article, I will walk you through the steps to set up a reverse proxy in Kubernetes. We will cover how to configure the Nginx server, create a Kubernetes [deployment](/blog/deployment-strategi
```suggestion
In this article, I will walk you through the steps to set up a reverse proxy in Kubernetes. We will cover how to configure the Nginx server, create a Kubernetes deployment, and set up a service to expose the deployment to the outside world.
```

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +## What Are Reverse Proxies
```suggestion
## What Are Reverse Proxies?
```

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +![Setup]]({{site.images}}{{page.slug}}/setup.png)\
@msali123 is this the image you're waiting for?

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +Next, Create a new file called **nginx.conf** in the **custome_nginx folder. This file will hold the custom configurations for your reverse proxy server.
```suggestion
Next, Create a new file called **nginx.conf** in the **custome_nginx** folder. This file will hold the custom configurations for your reverse proxy server.
```

2023-04-20 04:50 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +[Flask Homepage](https://i.imgur.io/iaQtJtX_d.webp)
@msali123 this Flask homepage should be an image. It's a markdown formatting error by the author that the editor also failed to spot. Please update.

2023-04-20 05:02 UTC, msali123 commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +[Flask Homepage](https://i.imgur.io/iaQtJtX_d.webp)
Yes Yes @balapriyac I am waiting for this image.

2023-04-20 05:44 UTC, balapriyac commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +[Flask Homepage](https://i.imgur.io/iaQtJtX_d.webp)
@msali123 there's one more image that's missing then? Please refer to my previous comment on setup.png.

2023-04-20 10:50 UTC, msali123 commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +[Flask Homepage](https://i.imgur.io/iaQtJtX_d.webp)
there was an extra bracket there 😬

2023-04-20 10:51 UTC, msali123 commented on blog/_posts/2023-06-21-setup-reverse-proxy-kubernetes-nginx.md
> +[Flask Homepage](https://i.imgur.io/iaQtJtX_d.webp)
Changes done but still I'll push once I get the image from author

2023-04-20 11:07 UTC, msali123 commented
@balapriyac [Changes done](https://64411c0ab0a8720fabfc34d7--ephemeral-narwhal-3ac3b2.netlify.app/blog/setup-reverse-proxy-kubernetes-nginx/)

2023-04-20 11:15 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-21 20:09 UTC, jalletto approved these changes

2023-04-21 20:09 UTC, merged