Blog - Create Automated CI/CD Builds using GitHub Actions and DockerHub
earthly/website pull request #428
Opened 2023-04-19 14:33 UTC by msali123

Done with all checks

2023-04-19 14:44 UTC, msali123 commented
[Preview Link](https://643ffda032ff9d309e15d21b--ephemeral-narwhal-3ac3b2.netlify.app/blog/cicd-build-github-action-dockerhub/)
@balapriyac

2023-04-20 05:36 UTC, balapriyac requested changes
Thanks, Sameer

2023-04-20 05:36 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +[Continuous integration (CI) and continuous delivery (CD)](https://about.gitlab.com/topics/ci-cd/); (CI/CD) incorporate the operating principles used by application development teams to deliver the a
```suggestion
Continuous integration (CI) and continuous delivery (CD) incorporate the operating principles used by application development teams to deliver the application code changes through built-in automation, testing, and collaboration workflows. It eliminates the manual development workflows to create automated processes that are predictable and repeatable.
```

2023-04-20 05:36 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +[DockerHub](https://hub.docker.com/) is a [container registry](/blog/how-to-setup-and-use-amazons-elastic-container-registry) service for storing and distributing Docker images. A Docker image packag
```suggestion
[DockerHub](https://hub.docker.com/) is a [container registry](/blog/how-to-setup-and-use-amazons-elastic-container-registry) service for storing and distributing Docker images. A Docker image packages the application setting, dependencies, and codebase to create a portable artifact that is easier to integrate between different CI/CD pipeline phases.
```

2023-04-20 05:36 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +- Open [GitHub](/blog/ci-comparison) Desktop and log in using your GitHub account
```suggestion
- Open GitHub Desktop and log in using your GitHub account
```

2023-04-20 05:36 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +You can streamline your workflow using [GitHub Action](https://github.com/features/actions) and automate CI/CD Builds. This guide will teach you how to leverage GitHub Action to automate Docker build
```suggestion
You can streamline your workflow using GitHub Actions and automate CI/CD Builds. This guide will teach you how to leverage GitHub Action to automate Docker builds to DockerHub. You will build an automated CI/CD builds using GitHub Actions and DockerHub.
```

2023-04-20 05:36 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +[DockerHub](https://hub.docker.com/) is a [container registry](/blog/how-to-setup-and-use-amazons-elastic-container-registry) service for storing and distributing Docker images. A Docker image packag
```suggestion
[DockerHub](https://hub.docker.com/) is a container registry service for storing and distributing Docker images. A Docker image packages the application setting, dependencies, and codebase to create a portable [artifact](https://www.jetbrains.com/teamcity/ci-cd-guide/concepts/artifact-repository/#:~:text=Build%20artifacts%20are%20the%20files,available%20to%20your%20CI%20server.) that is easier to integrate between different CI/CD pipeline phases.
```

2023-04-20 05:42 UTC, balapriyac requested changes

2023-04-20 05:42 UTC, balapriyac commented on blog/_posts/2023-05-18-cicd-build-github-action-dockerhub.md
> +title: "Create Automated CI/CD Builds using GitHub Actions and DockerHub"
```suggestion
title: "Create Automated CI/CD Builds Using GitHub Actions and DockerHub"
```

2023-04-20 10:56 UTC, msali123 commented
@balapriyac [Changes done](https://644119174a3a2c11b8987912--ephemeral-narwhal-3ac3b2.netlify.app/blog/cicd-build-github-action-dockerhub/)

2023-04-20 11:16 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-21 20:20 UTC, jalletto approved these changes

2023-04-21 20:23 UTC, merged