Blog - Querying Relational Databases With SQLAlchemy in Python
earthly/website pull request #435
Opened 2023-04-21 19:29 UTC by msali123

Done with all checks.

2023-04-21 19:39 UTC, msali123 commented
@balapriyac Preview [Link](https://6442e5a581424b0cfa128269--ephemeral-narwhal-3ac3b2.netlify.app/blog/query-database-sqlalchemy-python/)

2023-04-21 21:23 UTC, jalletto requested changes
Hey @msali123 Just a few changes. Thanks.

2023-04-21 21:23 UTC, jalletto commented on blog/_posts/2023-05-18-query-database-sqlalchemy-python.md
> +Create a file named `[main.py](http://main.py)` (you can of course name this file whatever you want) and import the following from the SQLAlchemy library:
```suggestion
Create a file named `main.py` (you can of course name this file whatever you want) and import the following from the SQLAlchemy library:
```

2023-04-21 21:23 UTC, jalletto commented on blog/_posts/2023-05-18-query-database-sqlalchemy-python.md
> +</aside>
```suggestion
<div class="notice--big--primary">

💡 The **`declarative_base`** function is used to create a base class that is used to define the database schema. This base class allows us to define the database schema in a way that is more like defining regular Python classes, and it makes it easy to create new database tables and columns.

After creating the base class by using the **`declarative_base`** function, we can define classes that inherit from the base class, and each of these classes represents a table in the database. We can define the columns of the table as attributes of the class, and we can define relationships between tables using attributes as well. Once we have defined all of our classes, we can use SQLAlchemy to create the database schema and interact with the database using the classes we have defined.

</div>
```

2023-04-21 21:23 UTC, jalletto commented on blog/_posts/2023-05-18-query-database-sqlalchemy-python.md
> +First, we'll define an SQLAlchemy model class **`User`** that represents a table called *users* in a database, this could be any class of your choice (a **`Persons`** class or a **`Students`** class)
```suggestion
First, we'll define an SQLAlchemy model class **`User`** that represents a table called *users* in a database. This could be any class of your choice (a **`Persons`** class or a **`Students`** class):
```

2023-04-21 21:23 UTC, jalletto commented on blog/_posts/2023-05-18-query-database-sqlalchemy-python.md
> +Up until now, you are expected to have the following snippets in your *main.py*  file:
```suggestion
Up until now, you are expected to have the following snippets in your `main.py`  file:
```

2023-04-21 21:23 UTC, jalletto commented on blog/_posts/2023-05-18-query-database-sqlalchemy-python.md
> +Finally, you can retrieve all the users whose country starts with the letter "M" from the ***`users`** table using the following command:
```suggestion
Finally, you can retrieve all the users whose country starts with the letter "M" from the `users` table using the following command:
```

2023-04-21 22:00 UTC, msali123 commented
@jalletto [Changes done](https://644306d4092a2507a328c7ee--ephemeral-narwhal-3ac3b2.netlify.app/blog/query-database-sqlalchemy-python/)

2023-04-23 23:56 UTC, msali123 commented
[Preview Link](https://6445c4efb6144836089c4434--ephemeral-narwhal-3ac3b2.netlify.app/blog/query-database-sqlalchemy-python/)

2023-04-28 15:44 UTC, jalletto approved these changes

2023-04-28 15:44 UTC, merged