Blog - CI/CD Security: Challenges and Best Practices
earthly/website pull request #437
Opened 2023-04-23 10:38 UTC by msali123

Done with all checks.

2023-04-23 10:46 UTC, msali123 commented
@balapriyac [Preview link](https://64450be115a2690fcf879a8e--ephemeral-narwhal-3ac3b2.netlify.app/blog/ci-cd-security-challenges-best-practices/)

2023-04-24 00:02 UTC, msali123 commented
[Updated link](https://6445c66fdac83e3cf2cc9389--ephemeral-narwhal-3ac3b2.netlify.app/blog/ci-cd-security-challenges-best-practices/)

2023-04-24 06:52 UTC, balapriyac requested changes
Thanks, Sameer! Requested a few minor changes.

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +![Image]({{site.images}}{{page.slug}}/HOd6Gcu.png)\
```suggestion

```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +
```suggestion

![Image]({{site.images}}{{page.slug}}/HOd6Gcu.png)\

```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +
Moved the image here from the beginning of the article.

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +In today's fast-paced world of software development, speed, and agility are important to stay ahead of the competition. [Continuous Integration](/blog/continuous-integration) and Continuous Deploymen
```suggestion
In today's fast-paced world of software development, speed, and agility are important to stay ahead of the competition. Continuous Integration and Continuous Deployment (CI/CD) have emerged as the go-to methodologies to achieve this goal. CI/CD is a practice that allows developers to continuously integrate and deploy their code changes into production, enabling them to rapidly deliver features and updates to their users.
```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +![Tools]({{site.images}}{{page.slug}}/toolbox.png)\
```suggestion

```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +
```suggestion

By implementing access controls and cryptographic features in your code repository, you can help ensure the security and integrity of your codebase, and reduce the risk of unauthorized access or tampering.

<div class="notice--info">
To learn more about GitHub access controls, check out the [documentation](https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github).
</div>

```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +The logger instance is configured to log messages to the console and to a file called pipeline.log. In the example, the logger is used to log the starting and completion of the pipeline, but it can b
```suggestion
The logger instance is configured to log messages to the console and to a file called `pipeline.log`. In the example, the logger is used to log the starting and completion of the pipeline, but it can be used to log any activity that needs to be monitored for security breaches.
```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +To enforce access control policies in the infrastructure, an example of best practice is to use role-based access control (RBAC). This involves defining roles with specific sets of permissions and as
```suggestion
To enforce access control policies in the infrastructure, an example of best practice is to use [role-based access control (RBAC)](https://earthly.dev/blog/guide-rolebased-ctrl/). This involves defining roles with specific sets of permissions and assigning those roles to users or groups.
```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +1. Download the SonarQube package from the official website: <https://www.sonarqube.org/downloads/>
```suggestion
1. [Download the SonarQube package](https://www.sonarqube.org/downloads/) from the official website.
```

2023-04-24 06:52 UTC, balapriyac commented on blog/_posts/2023-05-26-ci-cd-security-challenges-best-practices.md
> +Note that these are general steps and may vary depending on your specific setup and requirements. It is recommended to refer to the official SonarQube documentation for detailed installation instruct
```suggestion
Note that these are general steps and may vary depending on your specific setup and requirements. It is recommended to refer to the [official SonarQube documentation](https://docs.sonarqube.org/latest/) for detailed installation instructions.
```

2023-04-24 09:39 UTC, msali123 commented
@balapriyac [Changes done](https://64464c51586029291dad1352--ephemeral-narwhal-3ac3b2.netlify.app/blog/ci-cd-security-challenges-best-practices/)

2023-04-24 11:49 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-28 15:47 UTC, jalletto requested changes

2023-04-28 15:50 UTC, msali123 commented on blog/_posts/2023-05-19-grafana-loki-log-aggregation-k8s.md
> -![Overview Of Grafana Loki]({{site.images}}{{page.slug}}/pVl3qaE.jpeg)
May be yes i'm looking into it

2023-04-28 16:06 UTC, msali123 commented
@jalletto  done

2023-04-28 18:36 UTC, jalletto approved these changes

2023-04-28 19:08 UTC, merged