Blog - Automating Data Pipelines and Workflows Using Apache Airflow
earthly/website pull request #438
Opened 2023-04-23 14:16 UTC by msali123

Done with all checks

2023-04-23 14:25 UTC, msali123 commented
@balapriyac  [Preview](https://64453f24f368c539b8284b64--ephemeral-narwhal-3ac3b2.netlify.app/blog/data-pipelines-with-airflow/)

2023-04-24 00:15 UTC, msali123 commented
[Updated link](https://6445c8407ba8f93bd304f44d--ephemeral-narwhal-3ac3b2.netlify.app/blog/data-pipelines-with-airflow/)

2023-04-24 07:15 UTC, balapriyac requested changes
Thanks, Sameer.

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +It is possible to verify the installation of Docker by executing the following command in the command prompt:
```suggestion
You can verify the installation of Docker by executing the following command in the command prompt:
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +To deploy Airflow on Docker Compose, We should fetch docker-compose.yaml by executing the following command in the command prompt.
```suggestion
To deploy Airflow on Docker Compose, We should fetch `docker-compose.yaml` by executing the following command in the command prompt.
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +The resulting output should be as shown below
```suggestion
The resulting output should be as shown below:
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> + The resulting output should be as shown below. Exited with code 0 means it's deployed successfully. You may get a warning that AIRFLOW_UID is not set, but you can ignore it.
```suggestion
 The resulting output should be as shown below. Exited with code 0 means it's deployed successfully. You may get a warning that `AIRFLOW_UID` is not set, but you can ignore it.
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +To check if the airflow service is running, Execute the following command in the command prompt
```suggestion
To check if the Airflow service is running, execute the following command in the command prompt:
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +Open a web browser and enter the following localhost URL: <http://localhost:8080>. Set the username "airflow" and the password "airflow"
```suggestion
Open a web browser and enter the following localhost URL: <http://localhost:8080>. Set the username "airflow" and the password "airflow":
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +You can get the full DAG Python code through this [GitHub link](https://github.com/ansamAY/airflow/blob/main/ETL_DAG_Code.py)
```suggestion
You can get the full DAG Python code at this [GitHub link](https://github.com/ansamAY/airflow/blob/main/ETL_DAG_Code.py)
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +Import the necessary modules and packages, including the `DAG` class from Airflow, the `BashOperator` class, and the days_ago and timedelta functions from Airflow's dates module.
```suggestion
Import the necessary modules and packages, including the `DAG` class from Airflow, the `BashOperator` class, and the `days_ago` and `timedelta` functions from Airflow's `dates` module.
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +
```suggestion
In the above snippet:

- `owner`: Specifies the owner of the DAG. This is typically the name of the person or team responsible for maintaining the DAG.
- `depends_on_past`: Specifies whether a task instance should depend on the success of the previous task instance.
- `start_date`: Specifies the date and time when the DAG should start running.
- `email_on_failure`: Specifies whether to send an email notification when a task fails.
- `email_on_retry`: Specifies whether to send an email notification when a task is retried.
- `schedule_interval`: The frequency with which the task should run. In this case, it is set to run once per day.
- `retries`: Specifies the number of times to retry a failed task.
- `retry_delay`: Specifies the delay between retries. In this case, we're using a delay of 5 seconds.

```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +- A task_id string that uniquely identifies the task.
```suggestion
- A `task_id` string that uniquely identifies the task.
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +As you can see below, `web_server_log.txt` file has been downloaded
```suggestion
As you can see below, `web_server_log.txt` file has been downloaded:
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +We will extract two columns (timestamp,visitorId) from the file downloaded. So we will use the bash command to extract the two columns and create a new file with the name `web_server_log_extracted.tx
```suggestion
We will extract two columns (`timestamp`,`visitorId`) from the file downloaded. So we will use the bash command to extract the two columns and create a new file with the name `web_server_log_extracted.txt`
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +The last step is to compress the transformed and extracted data
```suggestion
The last step is to compress the transformed and extracted data.
```

2023-04-24 07:15 UTC, balapriyac commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +The three download tasks can be executed in parallel since they don't have any dependencies on each other. The merge_task is downstream of all three download tasks, and can only be executed after the
```suggestion
The three download tasks can be executed in parallel since they don't have any dependencies on each other. The `merge_task` is downstream of all three download tasks, and can only be executed after they have all been completed successfully.
```

2023-04-24 09:35 UTC, msali123 commented on blog/_posts/2023-05-29-data-pipelines-with-airflow.md
> +
@balapriyac by doing the first letter small it gives a lint error.

2023-04-24 10:00 UTC, msali123 commented
@balapriyac [Changes](https://644652ca996f92006fc1d46b--ephemeral-narwhal-3ac3b2.netlify.app/blog/data-pipelines-with-airflow/)

2023-04-24 11:51 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-28 16:16 UTC, merged