Blog - Using and Pushing Docker Images with Bazel
earthly/website pull request #440
Opened 2023-04-24 00:58 UTC by msali123

Draft

2023-04-24 01:08 UTC, msali123 commented
[Link](https://6445d5c3297faf40ca285992--ephemeral-narwhal-3ac3b2.netlify.app/blog/using-docker-images-bazel/)

2023-04-24 10:11 UTC, msali123 commented
@balapriyac [Preview Link](https://64465547ba112f0090661cce--ephemeral-narwhal-3ac3b2.netlify.app/blog/push-docker-image-bazel/)

2023-04-27 03:57 UTC, balapriyac requested changes

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +title: "Using and Pushing Docker Images with Bazel"
```suggestion
title: "Using and Pushing Docker Images With Bazel"
```

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +title: "Using and Pushing Docker Images with Bazel"
Title case, AP Style recommends capitalizing `with` as well.

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +Using [Docker](https://www.docker.com/) images with Bazel allows for even more scalability than what Docker or Bazel could offer you alone. This is because different parts of the project can be run i
```suggestion
Using Docker images with Bazel allows for even more scalability than what Docker or Bazel could offer you alone. This is because different parts of the project can be run in lightweight, portable, and isolated containers and can be executed in parallel across multiple machines or clusters. Moreover, Bazel offers easy compatibility with [rules_docker](https://github.com/bazelbuild/rules_docker), which are premade rules for carrying out Docker tasks. What's great about these rules is that you don't need to write Docker commands for pulling, building, or pushing images as the rules will take care of all these, thereby simplifying the development process. This can be particularly useful for large-scale projects that require the use of multiple Docker images, as it streamlines the process of building and deploying those images
```

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +* **Bazel:** This is available for installation across Linux, macOS, and Windows systems. You can follow the instructions in their [installation guide](https://bazel.build/install) to download the ve
```suggestion
* **Bazel**: This is available for installation across Linux, macOS, and Windows systems. You can follow the instructions in their [installation guide](https://bazel.build/install) to download the version of Bazel that you need.
```

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +* **Docker:** You'll need active Docker credentials to pull and push images to Docker Hub. You can define your [custom Docker configuration](https://github.com/bazelbuild/rules_docker#container_pull-
```suggestion
* **Docker**: You'll need active Docker credentials to pull and push images to Docker Hub. You can define your [custom Docker configuration](https://github.com/bazelbuild/rules_docker#container_pull-custom-client-configuration) in Bazel or run the following command in your terminal to grant access to your subsequent commands:
```

2023-04-27 03:57 UTC, balapriyac commented on blog/_posts/2023-05-30-push-docker-image-bazel.md
> +Overall, Bazel provides a robust and extensive set of functionality for dealing with Docker, making it a great choice for developers who wish to automate their containerization process. Whether you'r
```suggestion
Overall, [Bazel](/blog/bazel-build/) provides a robust and extensive set of functionality for dealing with Docker, making it a great choice for developers who wish to automate their containerization process. Whether you're looking to design, test, or deploy software, Bazel's efficient and dependable methodology will help you optimize your development process and accomplish your objectives more quickly.
```

2023-04-27 06:34 UTC, msali123 commented
@balapriyac [Changes Done](https://644a16b141346547e5bb9fff--ephemeral-narwhal-3ac3b2.netlify.app/blog/push-docker-image-bazel/)

2023-04-27 14:01 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-28 16:32 UTC, jalletto approved these changes

2023-04-28 16:33 UTC, merged