Blog - Improving Django Performance using Caching
earthly/website pull request #442
Opened 2023-04-24 11:56 UTC by msali123

Done with all checks.

2023-04-24 12:04 UTC, msali123 commented
@balapriyac [Preview Link](https://64466fe13051eb1371d97822--ephemeral-narwhal-3ac3b2.netlify.app/blog/improve-django-performance-caching/)

2023-04-27 04:33 UTC, balapriyac requested changes
@jalletto I've suggested changes (formatting edits, missing inline code, and a couple grammatical errors). There are a lot of instances where terms like Caching strategies, Cache, Caching Backend, and the like are capitalized (when they don't need to be). But I did not suggest edits for those as it'd require too many changes. Could you please advice?

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +
```suggestion

- **Time-Based Invalidation**: Time-Based cache invalidation is when the cache is cleared after a certain amount of time has passed. This is great for content that doesn't change frequently, as it reduces the load on the server by serving the same data from the cache.

- **Key-Based Invalidation**: In key-based invalidation, a unique identifier is assigned to each cached item or set of items. When changes are made to the data that corresponds to a specific key, the cache item associated with that key can be invalidated or deleted, ensuring that the next request for that data will result in a fresh retrieval from the original source. This approach offers more granular control over cache invalidation compared to time-based invalidation, which relies solely on time limits to determine when cached data should be cleared.

```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +Take a look at your project directory, you will see a cache directory which contains all the cache for your application. Since these files are binary you cannot read their content they are meant to b
```suggestion
Take a look at your project directory, you will see a cache directory that contains all the cache for your application. Since these files are binary you cannot read their content. They are meant to be used by Django Caching Backend.
```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +The File System Caching Backend is suitable for small projects where integrating with an external service like Redis is a bit of overkill. File System Caching stores cached data in a specified direct
```suggestion
The File System Caching Backend is suitable for small projects where integrating with an external service like Redis is a bit of overkill. File System Caching stores cached data in a specified directory in your system. You can implement this backend by making the following changes in your CACHES setting in your `settings.py` file:
```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +Django is a powerful web framework that makes building web applications in Python a breeze. However, as your application grows, you might encounter performance issues. Caching is a technique that can
```suggestion
Django is a powerful web framework that makes building web applications in Python a breeze. However, as your application grows, you might encounter performance issues. **Caching** is a technique that can help optimize your application's performance by reducing the amount of time it takes to retrieve data. It is a way of storing frequently accessed data in memory for quick access. Properly implementing caching in your Django application can lead to faster response times and a better user experience. Caching can also help reduce the load on the database server. This can help free up database resources and improve the overall performance of the application. Django's caching framework provides a flexible and configurable way to implement caching in an application.
```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +
```suggestion

The Caching implementation in Django can be divided into two steps:

- **Cache Backend**: A cache backend in Django is a critical component that serves as an intermediary between the database and the application. Its primary function is to temporarily store frequently accessed data in a specified location, which can include memory, disk, or other external storage systems, for rapid retrieval. In Django, there are mainly three important backends - Database, File System Caching, and Local Memory Cache.

- **Target**: The target for caching refers to the specific block of code that is marked for caching, which can range from the entire website to individual views or templates. To specify the target for caching, developers can use decorators or middleware to identify the code block. Depending on the cache backend chosen, the cache can be stored in memory, disk, or other external storage systems.

```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +The per-view caching strategy uses a built-in [`cache_page`](https://docs.djangoproject.com/en/4.2/topics/cache/#django.views.decorators.cache.cache_page) decorator on the view. Open the views.py fil
```suggestion
The per-view caching strategy uses a built-in [`cache_page`](https://docs.djangoproject.com/en/4.2/topics/cache/#django.views.decorators.cache.cache_page) decorator on the view. Open the `views.py` file and apply the decorator on the `all` view as shown in the following code:
```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +The File System Caching Backend is suitable for small projects where integrating with an external service like Redis is a bit of overkill. File System Caching stores cached data in a specified direct
```suggestion
The File System Caching Backend is suitable for small projects where integrating with an external service like Redis is a bit of overkill. File System Caching stores cached data in a specified directory in your system. You can implement this backend by making the following changes in your `CACHES` setting in your `settings.py` file:
```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +
```suggestion

Django comes with a full set of caching framework out of the box which lets the developers build robust applications which are easier to scale. Caching is an essential aspect of optimizing web application performance, and Django provides excellent support for caching. In this article, we discussed the various caching strategies available in Django and explored how they can be used to improve application performance. We also discussed the benefits of caching, such as reducing the number of database queries and improving response times for users. 

Additionally, we looked at the importance of cache invalidation and explored strategies for optimizing cache performance. Overall, caching is a powerful tool that can significantly improve the performance of Django applications, and developers should leverage it to ensure their applications deliver the best possible user experience.

```

2023-04-27 04:33 UTC, balapriyac commented on blog/_posts/2023-06-01-improve-django-performance-caching.md
> +In the code snippet above, the `BACKEND` setting specifies the in-built caching backend(DatabaseCache) and the `LOCATION` setting specifies the name of the cache table as `cache_table` where all the
```suggestion
In the code snippet above, the `BACKEND` setting specifies the in-built caching backend (DatabaseCache) and the `LOCATION` setting specifies the name of the cache table as `cache_table` where all the cache data will be stored and retrieved. You can modify this setting to use a different table name.
```

2023-04-27 05:20 UTC, balapriyac commented
Also, @msali123 could you please update the header image? Behind the image text, we can just have Django logo maybe? Please let me know what you think.

2023-04-27 06:51 UTC, msali123 commented
> Also, @msali123 could you please update the header image? Behind the image text, we can just have Django logo maybe? Please let me know what you think.

@balapriyac logo behind wasn't looking good so I just changed the bg.

2023-04-27 07:05 UTC, msali123 commented
@balapriyac [Changes done](https://644a1bfe20e42b5358c497c3--ephemeral-narwhal-3ac3b2.netlify.app/blog/improve-django-performance-caching/)

2023-04-27 14:02 UTC, balapriyac commented
> > Also, @msali123 could you please update the header image? Behind the image text, we can just have Django logo maybe? Please let me know what you think.
> 
> @balapriyac logo behind wasn't looking good so I just changed the bg.

Looks great now, thank you.

2023-04-28 19:13 UTC, jalletto commented
> There are a lot of instances where terms like Caching strategies, Cache, Caching Backend, and the like are capitalized (when they don't need to be). Could you please advise if we could leave them as is for this article?

@balapriyac @msali123 I think we should correct these. I'll let Ahmad know to be aware of this in the future; looks like he edited this one. For now, Bala, if there aren't that many you can mark them for Sameer. If there a lot, let me know, I don't mind pulling down the branch and just updating them myself, but won't have time to do it until next week.

2023-05-12 20:10 UTC, jalletto approved these changes

2023-05-12 20:10 UTC, merged