Blog - How to Deploy a Kubernetes Cluster Using the CRI-O Container Runtime
earthly/website pull request #445
Opened 2023-04-26 16:41 UTC by msali123

Done with all checks.

2023-04-26 16:51 UTC, msali123 commented
@balapriyac [Preview Link](https://644955e20f582f22e0b19b06--ephemeral-narwhal-3ac3b2.netlify.app/blog/deploy-kubernetes-cri-o-container-runtime/)

2023-04-27 05:30 UTC, balapriyac requested changes
Thanks Sameer. Just a few suggestions.

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +## What Is CRI-O
```suggestion
## What Is CRI-O?
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +So, the swapoff -a command disables all swap devices or files on a Linux system, ensuring that Kubernetes can manage the host system's memory resources accurately.
```suggestion
So, the `swapoff -a` command disables all swap devices or files on a Linux system, ensuring that Kubernetes can manage the host system's memory resources accurately.
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +Since the release of **[CRI-O v1.18.0](https://cri-o.github.io/cri-o/v1.18.0.html)**, The **CRI-O** container runtime now runs containers without the NET_RAW capability by default. This change was ma
```suggestion
Since the release of **[CRI-O v1.18.0](https://cri-o.github.io/cri-o/v1.18.0.html)**, The **CRI-O** container runtime now runs containers without the `NET_RAW` capability by default. This change was made for security reasons to reduce the attack surface of containerized applications.
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +The NET_RAW capability is used to create and manipulate raw network packets, which could potentially be used to launch a variety of network-based attacks.
```suggestion
The `NET_RAW` capability is used to create and manipulate raw network packets, which could potentially be used to launch a variety of network-based attacks.
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +## **Configuring Kernel Modules, Sysctl Settings, and Swap**
```suggestion
## Configuring Kernel Modules, Sysctl Settings, and Swap
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +## **Installing the CRI-O Container Runtime**
```suggestion
## Installing the CRI-O Container Runtime
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +Save the file and run the **`systemctl restart crio`** command to restart cri-o.
```suggestion
Save the file and run the **`systemctl restart crio`** command to restart CRI-O.
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +Now from your local machine execute the following command again `kubectl run -it --rm busybox --image busybox` and try the `ping MASTER_NODE_IP` command:
```suggestion
Now from your local machine execute the `kubectl run -it --rm busybox --image busybox` command again and try running the `ping MASTER_NODE_IP` command:
```

2023-04-27 05:30 UTC, balapriyac commented on blog/_posts/2023-06-02-deploy-kubernetes-cri-o-container-runtime.md
> +title: "How to Deploy a Kubernetes Cluster Using the CRI-O Container Runtime"
```suggestion
title: "How To Deploy a Kubernetes Cluster Using the CRI-O Container Runtime"
```

2023-04-27 07:22 UTC, msali123 commented
@balapriyac [Changes done](https://644a22324134654ea2bba0a2--ephemeral-narwhal-3ac3b2.netlify.app/blog/deploy-kubernetes-cri-o-container-runtime/)

2023-04-27 14:04 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-28 17:56 UTC, jalletto approved these changes

2023-04-28 17:56 UTC, merged