Blog - Building Golang with Bazel and Gazelle
earthly/website pull request #446
Opened 2023-04-26 17:41 UTC by msali123

Done with all checks

2023-04-26 17:58 UTC, msali123 commented
@balapriyac [Preview Link](https://6449643093b20535eb478b57--ephemeral-narwhal-3ac3b2.netlify.app/blog/build-golang-bazel-gazelle/)

2023-04-27 05:36 UTC, balapriyac requested changes
Thanks, Sameer!

2023-04-27 05:36 UTC, balapriyac commented on blog/_posts/2023-06-05-build-golang-bazel-gazelle.md
> +title: "Building Golang with Bazel and Gazelle"
```suggestion
title: "Building Golang With Bazel and Gazelle"
```

2023-04-27 05:36 UTC, balapriyac commented on blog/_posts/2023-06-05-build-golang-bazel-gazelle.md
> +Bazel can be used to build a Go project of any size, and the [`Go build`](https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies) command is often sufficient for small applications. However,
```suggestion
Bazel can be used to build a Go project of any size, and the [`go build`](https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies) command is often sufficient for small applications. However, if your Go project is considerably large, supports code generation, or is in the same repository as code written in other languages, these variables can add multiple layers of complexity to your build process and the `go build` command might not be sufficient.
```

2023-04-27 05:36 UTC, balapriyac commented on blog/_posts/2023-06-05-build-golang-bazel-gazelle.md
> +You should receive this error:
```suggestion
You should get this error:
```

2023-04-27 07:55 UTC, msali123 commented
@balapriyac [Changes done](https://644a23d1fb679257f02e5191--ephemeral-narwhal-3ac3b2.netlify.app/blog/build-golang-bazel-gazelle/)

2023-04-27 14:05 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-04-28 18:09 UTC, merged