Blog - How To Work With CSV Files In Go
earthly/website pull request #447
Opened 2023-04-26 21:04 UTC by msali123

Done with all checks.

2023-04-26 21:17 UTC, msali123 commented
@balapriyac [Preview Link](https://64499452a49cb17434bd0005--ephemeral-narwhal-3ac3b2.netlify.app/blog/golang-csv-files/)

2023-04-27 04:40 UTC, balapriyac requested changes
Thanks, Sameer. Suggested a few minor edits.

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +![Mastering]({{site.images}}{{page.slug}}/mastering.png)\
```suggestion

```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +## Converting CSV File Into JSON File
```suggestion
## Converting a CSV File To JSON
```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +## Converting JSON File Into CSV
```suggestion
## Converting a JSON File To CSV
```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +</div>
```suggestion

<div class="notice--info">
### Maps and Slice of Maps in Golang

In Go, **maps** are a built-in data structure that associates data in key-value pairs. A map provides constant-time access to its elements, based on their keys. A slice provides a way to reference a subset of an array or map without getting the whole map.

A **slice of maps** in Go is a data structure that combines the features of slices and maps. It is a dynamic sequence of maps, where each map represents a collection of key-value pairs. In other words, it is a slice where each element is a map.
</div>
```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +You can find the code used in this article on [GitHub](https://github.com/khabdrick/go-csv).
```suggestion

```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +
```suggestion
### Prerequisites

To follow along with this tutorial, be sure you have the following:

1. Basic knowledge of Golang
2. Golang is set up on your local machine

You can find the code used in this article on [GitHub](https://github.com/khabdrick/go-csv).
```

2023-04-27 04:40 UTC, balapriyac commented on blog/_posts/2023-06-06-golang-csv-files.md
> +
```suggestion
<div class="notice--info">
Marshaling is the process of converting Go data structures (such as structs, maps, and slices) to a serialized format, typically JSON, XML, or YAML while unmarshaling is the process of decoding data in serialized format into Go data structure. 
</div>

```

2023-04-27 07:15 UTC, msali123 commented
@balapriyac [CHanges DOne](https://644a20b4b909075380cdc6db--ephemeral-narwhal-3ac3b2.netlify.app/blog/golang-csv-files/)

2023-04-28 18:14 UTC, jalletto approved these changes

2023-04-28 18:24 UTC, merged