Blog - Securing Kubernetes with Network Policies
earthly/website pull request #448
Opened 2023-04-26 22:02 UTC by msali123

Done with all checks.

2023-04-26 22:12 UTC, msali123 commented
@balapriyac [Preview Link](https://6449a0f76cee190474ea11ca--ephemeral-narwhal-3ac3b2.netlify.app/blog/kubernetes-network-policies/)

2023-04-27 05:45 UTC, balapriyac requested changes
Thank you, @msali123, just a couple of small changes.

2023-04-27 05:45 UTC, balapriyac commented on blog/_posts/2023-06-07-kubernetes-network-policies.md
> +title: "Securing Kubernetes with Network Policies"
```suggestion
title: "Securing Kubernetes With Network Policies"
```

2023-04-27 05:45 UTC, balapriyac commented on blog/_posts/2023-06-07-kubernetes-network-policies.md
> +This is to be able to communicate with the applications running on pods through Kubernetes services. Because in real life scenarios, pods are not communicating directly but through service resources.
```suggestion
Communication with the applications running on pods is facilitated by [Kubernetes services](/blog/kubernetes-services/). Because in real-world applications, pods are not communicating directly but through service resources.
```

2023-04-27 05:45 UTC, balapriyac commented on blog/_posts/2023-06-07-kubernetes-network-policies.md
> +Now let's execute different commands to make sure the network policies are working as expected.
```suggestion
Now let's execute different commands to make sure the network policies are working as expected:
```

2023-04-28 18:27 UTC, jalletto approved these changes

2023-04-28 18:28 UTC, merged