Blog - How to Set Up a Private Docker Registry on Linux
earthly/website pull request #472
Opened 2023-05-09 11:05 UTC by msali123

Done with all checks.

2023-05-09 13:20 UTC, msali123 commented
@balapriyac  [Preview Link](https://645a480303d3df1f64c21746--ephemeral-narwhal-3ac3b2.netlify.app/blog/private-docker-registry/)

2023-05-15 02:11 UTC, balapriyac requested changes
@msali123 Great work, Sameer. Just suggested a couple of minor changes.

2023-05-15 02:11 UTC, balapriyac commented on blog/_posts/2023-06-13-private-docker-registry.md
> +Then, run the `certbot` command followed by your domain name to download the SSL certificates, and configure NGINX to use the downloaded certificates for your domain..
```suggestion
Then, run the `certbot` command followed by your domain name to download the SSL certificates, and configure NGINX to use the downloaded certificates for your domain.
```

2023-05-15 02:11 UTC, balapriyac commented on blog/_posts/2023-06-13-private-docker-registry.md
> +Run the following command to verify the NGINX running status
```suggestion
Run the following command to verify the NGINX running status.
```

2023-05-15 02:11 UTC, balapriyac commented on blog/_posts/2023-06-13-private-docker-registry.md
> +Next, we'll need to define two more settings for NGINX..
```suggestion
Next, we'll need to define two more settings for NGINX.
```

2023-05-15 08:27 UTC, msali123 commented
Thanks Bala [Changes done](https://6461ec64db1c4527db9b7c8b--ephemeral-narwhal-3ac3b2.netlify.app/blog/private-docker-registry/)

2023-05-16 04:10 UTC, balapriyac requested changes
@msali123 added Earthly tie-in.

2023-05-16 04:10 UTC, balapriyac commented on blog/_posts/2023-06-13-private-docker-registry.md
> +
```suggestion
**We're [Earthly.dev](https://earthly.dev/). We make building software simpler and therefore faster using containerization. This article covers setting up a private Docker registry on Linux. If you want to know more about building in containers then [check us out](/).**
```

2023-05-16 08:04 UTC, msali123 commented
@balapriyac [Added Earthly tie-in](https://6463386fb9a39160cf76bd50--ephemeral-narwhal-3ac3b2.netlify.app/blog/private-docker-registry/)

2023-05-18 03:49 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-05-22 19:27 UTC, merged