Blog - Jobs and Cron Jobs in Kubernetes
earthly/website pull request #473
Opened 2023-05-09 14:07 UTC by msali123

Done with all checks.

2023-05-09 14:28 UTC, msali123 commented
@balapriyac [Preview Link](https://645a56e1dff760313075e6d8--ephemeral-narwhal-3ac3b2.netlify.app/blog/kubernetes-jobs-cron-jobs/)

2023-05-10 11:19 UTC, msali123 commented
[Updated Link](https://645b7d08b058f8113176f19c--ephemeral-narwhal-3ac3b2.netlify.app/blog/kubernetes-jobs-cron-jobs/)

2023-05-15 02:17 UTC, balapriyac requested changes
Thanks, Sameer.

2023-05-15 02:17 UTC, balapriyac commented on blog/_posts/2023-06-14-kubernetes-jobs-cron-jobs.md
> +Kubernetes provides two critical resources to manage these tasks: Jobs and CronJobs. Jobs are ideal for running one-off or batch tasks, while a CronJob is perfect for scheduling recurring tasks. By u
```suggestion
Kubernetes provides two critical resources to manage these tasks: **Jobs** and **CronJobs**. Jobs are ideal for running one-off or batch tasks, while a CronJob is perfect for scheduling recurring tasks. By using these resources, developers, DevOps engineers, and cluster administrators can focus on more critical tasks and ensure the reliability and efficiency of Kubernetes deployments.
```

2023-05-15 02:17 UTC, balapriyac commented on blog/_posts/2023-06-14-kubernetes-jobs-cron-jobs.md
> +💡The *`restartPolicy: Never`* specifies that the container should not be restarted if it fails or exits.
```suggestion
💡 The `restartPolicy: Never` specifies that the container should not be restarted if it fails or exits.
```

2023-05-15 02:17 UTC, balapriyac commented on blog/_posts/2023-06-14-kubernetes-jobs-cron-jobs.md
> +- This tutorial uses a Linux machine with the Ubuntu 22.04LTS distro (Any other OS will work fine as long as you have Kubernetes set up).
```suggestion
- This tutorial uses a Linux machine with the Ubuntu 22.04 LTS distro (Any other OS will work fine as long as you have [Kubernetes set up](/blog/k8s-dev-solutions/)).
```

2023-05-15 08:16 UTC, msali123 commented
Thanks Bala [Changes Done](https://6461e84ff630b321a5c388bd--ephemeral-narwhal-3ac3b2.netlify.app/blog/kubernetes-jobs-cron-jobs/)

2023-05-16 04:14 UTC, balapriyac requested changes
@msali123 added Earthly tie-in.

2023-05-16 04:14 UTC, balapriyac commented on blog/_posts/2023-06-14-kubernetes-jobs-cron-jobs.md
> +
```suggestion

**We're [Earthly.dev](https://earthly.dev/). We make building software simpler and therefore faster using containerization. This article covers jobs and cron jobs in Kubernetes. If you want to know more about building in containers then [check us out](/).**
```

2023-05-16 07:57 UTC, msali123 commented
@balapriyac [Added Earthly tie-in](https://6463363139c2565b8418b856--ephemeral-narwhal-3ac3b2.netlify.app/blog/kubernetes-jobs-cron-jobs/)

2023-05-18 03:50 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-05-22 19:28 UTC, merged