Blog - chown: Changing File and Directory File in Linux
earthly/website pull request #474
Opened 2023-05-09 16:03 UTC by msali123

done with all checks.

2023-05-09 16:47 UTC, msali123 commented
@balapriyac [Preview](https://645a78a19bb5210581960f4c--ephemeral-narwhal-3ac3b2.netlify.app/blog/chown-permissions-chmod/)

2023-05-16 04:48 UTC, balapriyac requested changes
@msali123 Nice work! Suggested a couple of formatting edits.

2023-05-16 04:48 UTC, balapriyac commented on blog/_posts/2023-06-15-chown-permissions-chmod.md
> +**We're [Earthly](https://earthly.dev/). We make building software simpler and, therefore, faster. This article is about Linux file permissions and ownership If you enjoy doing things at command line
```suggestion
**We're [Earthly](https://earthly.dev/). We make building software simpler and, therefore, faster. This article is about Linux file permissions and ownership. If you enjoy doing things at the command line you might like [Earthly](https://earthly.dev/). It's a pretty great open-source build tool.**
```

2023-05-16 04:48 UTC, balapriyac commented on blog/_posts/2023-06-15-chown-permissions-chmod.md
> +> **Please note:** Your Linux configuration or distribution may have a different method for interacting with or becoming the `root` user. Consult with your specific online documentation on how to use
```suggestion
<div class="notice--info">
Your Linux configuration or distribution may have a different method for interacting with or becoming the `root` user. Consult with your specific online documentation on how to use the [`sudo`](https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/c6239.htm) command properly.
</div>
```

2023-05-16 08:12 UTC, msali123 commented
Thanks Bala [changes done](https://64633a63c756155f9b4663af--ephemeral-narwhal-3ac3b2.netlify.app/blog/chown-permissions-chmod/)

2023-05-18 03:52 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-05-22 19:43 UTC, jalletto approved these changes

2023-05-22 19:43 UTC, merged