Blog - Using CMake and GCC to Cross-Compile Binaries
earthly/website pull request #475
Opened 2023-05-09 17:53 UTC by msali123

Done with all checks.

2023-05-09 18:07 UTC, msali123 commented
@balapriyac [Preview Link](https://645a8aed0cf584157701cb79--ephemeral-narwhal-3ac3b2.netlify.app/blog/cmake-gcc-cross-compile/)

2023-05-10 11:10 UTC, msali123 commented
[Updated link](https://645b7af49f2beb0fd99c5414--ephemeral-narwhal-3ac3b2.netlify.app/blog/cmake-gcc-cross-compile/)

2023-05-16 05:09 UTC, balapriyac requested changes
Thanks, Sameer. Requested a few minor changes.

2023-05-16 05:09 UTC, balapriyac commented on blog/_posts/2023-06-16-cmake-gcc-cross-compile.md
> +**We're [Earthly](https://earthly.dev/). We make building software simpler—and faster—using containerization. This article covers cross-compiling binaries using CMake and GCC. If you want to see what
```suggestion
**We're [Earthly](https://earthly.dev/). We make building software simpler—and faster—using containerization. This article covers cross-compiling binaries using CMake and GCC. If you want to see what can be done by combining ideas from a `Makefile` and a `Dockerfile`, then [check us out](/).**
```

2023-05-16 05:09 UTC, balapriyac commented on blog/_posts/2023-06-16-cmake-gcc-cross-compile.md
> +If [make](/blog/makefiles-on-windows) is not installed, use the following command to install it on Debian/Ubuntu:
```suggestion
If make is not installed, use the following command to install it on Debian/Ubuntu:
```

2023-05-16 05:09 UTC, balapriyac commented on blog/_posts/2023-06-16-cmake-gcc-cross-compile.md
> +![Make diagram]({{site.images}}{{page.slug}}/SshQwn3.png)
```suggestion
![Make diagram]({{site.images}}{{page.slug}}/SshQwn3.png)\
```

2023-05-16 05:09 UTC, balapriyac commented on blog/_posts/2023-06-16-cmake-gcc-cross-compile.md
> +Now that you have a simple C++ program running, it's time to cross-compile it to run on a different architecture using CMake. CMake is a popular tool for managing the build process of C and C++ proje
```suggestion
Now that you have a simple C++ program running, it's time to cross-compile it to run on a different architecture using CMake. [CMake](/blog/using-cmake/) is a popular tool for managing the build process of C and C++ projects, and it has built-in support for cross-compiling.
```

2023-05-16 05:09 UTC, balapriyac commented on blog/_posts/2023-06-16-cmake-gcc-cross-compile.md
> +
```suggestion

Even with the help of tools like CMake and GCC, cross-compiling C++ programs can be challenging. 

During cross-compiling, common issues you may encounter include compiler incompatibility, lack of readily available libraries, and toolchain conflicts. If you're facing some of these issues, here are a few tips:

```

2023-05-16 08:23 UTC, msali123 commented
Thanks Bala [Changes done](https://64633c783349905e47f86906--ephemeral-narwhal-3ac3b2.netlify.app/blog/cmake-gcc-cross-compile/)

2023-05-18 03:53 UTC, balapriyac commented
@jalletto this is ready to merge.

2023-05-22 19:44 UTC, jalletto approved these changes

2023-05-22 19:59 UTC, merged