Blog - Everything You Need to Know about Bazel Query
earthly/website pull request #485
Opened 2023-05-13 10:17 UTC by msali123

Done with all checks

2023-05-13 10:38 UTC, msali123 commented
https://645f678f0459692e578525bb--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-query/

2023-05-14 10:30 UTC, msali123 commented
@balapriyac @jalletto [Preview Link](https://6460b75222a1e16d73ab9309--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-query/)

2023-05-22 05:51 UTC, balapriyac requested changes
Thanks, Sameer.

2023-05-22 05:51 UTC, balapriyac commented on blog/_posts/2023-06-20-bazel-query.md
> +
```suggestion
<div class="notice--info">
Targets that `//apps/node_web` depend on are part of the result of this query, even though you didn't include their labels in your build query. It explains the Bazel query soundness concept.
</div>
```

2023-05-22 07:34 UTC, msali123 commented
@balapriyac [Updated Link](https://646b1a1b49813427cbd8410a--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-query/)

2023-06-05 14:47 UTC, msali123 commented
@jalletto [Updated Preview Link](https://647df4a3537e291b43f9bf66--ephemeral-narwhal-3ac3b2.netlify.app/blog/bazel-query/)

2023-06-09 21:24 UTC, msali123 commented
@jalletto

2023-06-28 14:45 UTC, merged