Blog - How to Build Java Projects with
earthly/website pull request #489
Opened 2023-05-18 10:17 UTC by msali123

Done with all checks.

2023-05-18 10:31 UTC, msali123 commented
@balapriyac {preview link](https://6465fc9d22467a147fdc7570--ephemeral-narwhal-3ac3b2.netlify.app/blog/build-java-projects-with-bazel)

2023-05-22 07:36 UTC, balapriyac requested changes
Thanks, Sameer.

2023-05-22 07:36 UTC, balapriyac commented on blog/_posts/2023-06-22-build-java-projects-with-bazel.md
> +> That's how you add external dependencies, but what about local dependencies? The best way to add a local dependency is to split your project and create separate targets for your local libraries or
```suggestion
<div class="notice--big--primary">
**That's how you add external dependencies, but what about local dependencies?** The best way to add a local dependency is to split your project and create separate targets for your local libraries or class files.
</div>
```

2023-05-22 07:58 UTC, msali123 commented
@balapriyac  [Changes Done](https://646b1f4e4981342b34d83f8f--ephemeral-narwhal-3ac3b2.netlify.ap)

2023-05-22 20:28 UTC, jalletto approved these changes

2023-05-22 20:28 UTC, merged