Blog - How to Automate Common Tasks with Shell Scripts
earthly/website pull request #499
Opened 2023-05-24 13:42 UTC by msali123

Done with all checks.

2023-05-24 14:02 UTC, msali123 commented
@jalletto build failing

2023-05-26 09:21 UTC, msali123 commented
@balapriyac [Preview Link](https://6470797ce782c0710ef47d33--ephemeral-narwhal-3ac3b2.netlify.app/blog/automate-tasks-shell-scripts/)

2023-06-01 18:40 UTC, jalletto requested changes

2023-06-01 18:40 UTC, jalletto commented on blog/_posts/2023-06-23-automate-tasks-shell-scripts.md
> +   ~~~{ caption="backup.sh"}
```suggestion
   ~~~{.bash caption="backup.sh"}
```

2023-06-01 18:40 UTC, jalletto commented on blog/_posts/2023-06-23-automate-tasks-shell-scripts.md
> +   ~~~{ caption="backup.sh"}
all these bash ones needs to have `.bash`

2023-06-01 18:40 UTC, jalletto commented on blog/_posts/2023-06-23-automate-tasks-shell-scripts.md
> +**We're [Earthly.dev](https://earthly.dev/). We make building software simpler and therefore faster using containerization. This article is about how to automate common tasks with shell scripts but i
```suggestion
**We're [Earthly.dev](https://earthly.dev/). We make building software simpler and therefore faster using containerization. This article is about how to automate common tasks with shell scripts. If you're interested in a different approach to building and packaging software then [check us out](/).**
```

2023-06-01 20:22 UTC, msali123 commented
@jalletto [Changes Done](https://6478fd70f69d8c0fd493590a--ephemeral-narwhal-3ac3b2.netlify.app/blog/automate-tasks-shell-scripts/)

2023-06-09 20:32 UTC, jalletto approved these changes

2023-06-09 20:32 UTC, merged