Blog - A Practical Guide to the Linux Uniq Command
earthly/website pull request #503
Opened 2023-05-26 06:25 UTC by msali123

Done with allchecks.

2023-05-26 06:34 UTC, msali123 commented
@balapriyac [Preview Link](https://6470526912128c5073aa0d6c--ephemeral-narwhal-3ac3b2.netlify.app/blog/linux-uniq-command/)

2023-05-26 08:46 UTC, balapriyac requested changes
@msali123 Just one small formatting edit.

2023-05-26 08:46 UTC, balapriyac commented on blog/_posts/2023-06-26-linux-uniq-command.md
> +
```suggestion
Suppose you only want to display the country names and their distinct value counts. You're going to need the help of the [`cut`](https://www.tutorialspoint.com/unix_commands/cut.htm) command. The `cut` command in Linux allows you to extract specific sections or columns of text from files or command output:

```

2023-05-26 09:14 UTC, msali123 commented
@balapriyac thank, [changes done](https://647077912d38c16ced66c99d--ephemeral-narwhal-3ac3b2.netlify.app/blog/linux-uniq-command/)

2023-06-01 18:42 UTC, jalletto approved these changes

2023-06-01 18:42 UTC, merged