Blog - Mastering Terraform Variables: A Comprehensive Guide for Defining and Utilizing Variable Types
earthly/website pull request #537
Opened 2023-06-21 08:37 UTC by msali123

Done with all checks

2023-06-30 15:33 UTC, jalletto commented on blog/_posts/2023-07-12-terraform-variables-guide.md
> +~~~
```suggestion
~~~{.tf caption=""}
variable "region" {
     description = "The AWS region where resources will be created"
     type  = string
     default  = "us-west-2"
}
~~~
```

2023-06-30 15:35 UTC, jalletto requested changes

2023-06-30 15:35 UTC, jalletto commented on blog/_posts/2023-07-12-terraform-variables-guide.md
> +~~~
everything in the code blocks that's in {} should be indented.

2023-06-30 15:35 UTC, jalletto commented on blog/_posts/2023-07-12-terraform-variables-guide.md
> +
Can you just take the content of this image and turn it into a code block?

2023-06-30 16:47 UTC, msali123 commented
@jalletto Changes done

2023-06-30 17:13 UTC, msali123 commented
[Preview Link](https://649f0c780103a82a4a499330--ephemeral-narwhal-3ac3b2.netlify.app/blog/terraform-variables-guide/)

2023-07-03 16:08 UTC, jalletto approved these changes

2023-07-03 16:28 UTC, merged