Blog - Better Together - Earthly + Github Actions
earthly/website pull request #540
Opened 2023-06-23 12:02 UTC by msali123

Draft

2023-06-23 12:57 UTC, msali123 commented
@adamgordonbell @ezeev [Preview Link](https://649595f72741e32d34c35b0e--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-github-actions/)

2023-06-23 13:17 UTC, adamgordonbell requested changes
I left a few pieces of feedback. Great turn around time!

Can you also try to make a nice header? Maybe no words but just the Github logo and the Earthly logo working together somehow? Use your judgment on what you think would look good.

2023-06-23 13:17 UTC, adamgordonbell commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +~~~
Can we make this yaml, for syntax highlighting?

2023-06-23 13:17 UTC, adamgordonbell commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +    <td>~~~
These tables look pretty good. Can we have yaml and dockerfile on the code blocks to get some syntax highlighting?

2023-06-23 13:17 UTC, adamgordonbell commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +~~~
```suggestion
~~~{.dockerfile caption=""}
```

2023-06-23 13:17 UTC, adamgordonbell commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +## Outside Article Checklist
remove check list

2023-06-23 13:54 UTC, msali123 commented
Yes Yes Adam this was just draft version for you guys to see that side by side code thing

2023-06-23 17:48 UTC, adamgordonbell commented
@ezeev you'll need to provide author details and a picture for the article bio at the bottom of the page.

2023-06-23 18:58 UTC, msali123 commented
Option 1
![EarthlyCoverImageTemplate](https://github.com/earthly/website/assets/32276372/0b057cdc-01dd-4418-b4d4-fd2d30e7657d)

Option 2
![EarthlyCoverImageTemplate (1)](https://github.com/earthly/website/assets/32276372/79b4310c-e20c-44b2-bd74-0fcb981f1095)

2023-06-23 19:40 UTC, msali123 commented
[Updated draft preview link](https://6495eecee0a65f0708f05e1e--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-github-actions/)

2023-06-24 20:48 UTC, msali123 commented
[Preview Link 1](https://649755f4ce5f6e1b82760ddd--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-github-actions/)

2023-06-26 17:16 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +After joining Earthly, I set out to build a project that I could use to highlight Earthly's strengths as a Continuous Integration (CI) solution. Namely that it enables consistent, repeatable builds,
Change "... monorepo support. . I've used Github Actions ..." to "... monorepo support. I've used Github Actions ..."

2023-06-26 17:19 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +And here is what the front-end looks like with everything is running:
Change to "And here is what the front-end looks like with everything running:"

2023-06-26 17:21 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +Let's dive into each of the main aspects of Earthly and see how they compared to Github Actions for this project.
@ezeev I feel like aspects isn't the right word here. Is it features? benefits?

2023-06-26 17:31 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +Developer speed is also an important dimension to consider. As I mentioned earlier in this article, the lag time in between iterations is a drag on developer productivity. And it just takes more line
This paragraph and the next paragraph should be joined into a single paragraph.

2023-06-26 17:33 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +With Earthly, executing the same pipeline locally completes in 7 seconds consistently. With [](https://earthly.dev/earthly-ci)[Earthly Satellites](https://earthly.dev/earthly-satellites), it also com
@ezeev When you mention Earthly Satellites here, it's the first mention of it in the post. Expect nobody to know what it is. You should add "– our managed remote build runners –".

2023-06-26 17:34 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +When it comes to developer speed. There really is no comparison. Composing my CI pipeline in Earthly felt natural and elegant compared to writing it out in YAML. If you've ever written Dockerfiles or
Change "... Dockerfiles or Makefiles, Earthly language ..." to "... Dockerfiles or Makefiles, Earthly's language ..."

2023-06-26 17:37 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +- [Earthly website](https://earthly.dev)
Remove these 3 bullet points.

2023-06-26 17:39 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +
@ezeev You should add a 1-2 sentence intro of yourself so readers have context before launching into the article.

2023-06-26 18:23 UTC, msali123 commented
@ezeev Once you review the suggestions by @thtmnisamnstr then I'll fix the changes.

2023-06-26 20:04 UTC, ezeev approved these changes
LGTM

2023-06-26 20:05 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +After joining Earthly, I set out to build a project that I could use to highlight Earthly's strengths as a Continuous Integration (CI) solution. Namely that it enables consistent, repeatable builds,
LGTM

2023-06-26 20:05 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +And here is what the front-end looks like with everything is running:
LGTM

2023-06-26 20:06 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +With Earthly, executing the same pipeline locally completes in 7 seconds consistently. With [](https://earthly.dev/earthly-ci)[Earthly Satellites](https://earthly.dev/earthly-satellites), it also com
Agree, @msali123 - can you add?

2023-06-26 20:07 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +When it comes to developer speed. There really is no comparison. Composing my CI pipeline in Earthly felt natural and elegant compared to writing it out in YAML. If you've ever written Dockerfiles or
LGTM

2023-06-26 20:07 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +- [Earthly website](https://earthly.dev)
LGTM

2023-06-26 20:22 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +Let's dive into each of the main aspects of Earthly and see how they compared to Github Actions for this project.
Yeah this is was originally something like "the key value propositions of Earthly" but it was too salesy. How is this?

```
Let's take a look at the project the following lenses: build consistency, simplicity, Monorepo support, and speed. 
```

2023-06-26 22:31 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +
Maybe mention what you do here. "I joined Earthly at the beginning of 2023. I lead solution architecture. That means I help potential customers figure out how they can best use Earthly and how they would implement it. One major part of my job is creating the demo that we show to potential customers. So when I first started at Earthly, I set out to build a project that I could use to highlight Earthly's strengths as a Continuous Integration (CI) solution..."

Or something like that.

2023-06-26 22:51 UTC, adamgordonbell commented
> @ezeev @adamgordonbell The difference b/w the 2 links is the header image if both of these don't looks good, let me know i'll change it.

I think option 2 will work

2023-06-27 17:54 UTC, ezeev commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +
How about this?

```
I joined Earthly at the beginning of 2023. I lead solution architecture. One of my primary roles is helping potential customers figure out how they can best leverage Earthly. That often requires building demonstrations that show the "art of the possible". So when I first started at Earthly, I set out to build a project that I could use to highlight Earthly's strengths as a Continuous Integration (CI) solution.
```

2023-06-27 17:58 UTC, thtmnisamnstr commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +
I'd drop the "art of the possible part" maybe:
I joined Earthly at the beginning of 2023. I lead solution architecture. One of my primary roles is helping potential customers figure out how they can best leverage Earthly. That often requires building demonstrations that show an example of how they would use Earthly in their projects. So when I first started at Earthly, I set out to build a project that I could use to highlight Earthly's strengths as a Continuous Integration (CI) solution.

2023-06-27 18:10 UTC, msali123 commented on blog/_posts/2023-07-17-earthly-github-actions.md
> +
Sure I'll do in a while.

2023-06-27 20:59 UTC, msali123 commented
@ezeev @adamgordonbell @thtmnisamnstr [Preview Link](https://649b4b4f9fced108275be0d5--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-github-actions/) after all changes.

2023-06-27 21:18 UTC, thtmnisamnstr commented
I'm good with this. @ezeev Any changes you want? If not, merge it, and I'll try to get the banner on the GHA landing page today.

2023-06-28 03:32 UTC, ezeev approved these changes

2023-06-28 09:59 UTC, adamgordonbell approved these changes

2023-06-28 09:59 UTC, merged