Blog - Database Operations in Go using GORM
earthly/website pull request #563
Opened 2023-07-11 07:46 UTC by msali123

Done with all checks.

2023-07-11 08:01 UTC, msali123 commented
@jalletto [Preview Link](https://64ad0baf1211294f9d277787--ephemeral-narwhal-3ac3b2.netlify.app/blog/using-gorm-go/)

2023-07-17 19:19 UTC, jalletto requested changes

2023-07-17 19:19 UTC, jalletto commented on blog/_posts/2023-07-25-using-gorm-go.md
> +
```suggestion
**Note**: You can find the code snippets used in this tutorial [on github](https://github.com/mercybassey/gorm).

```

2023-07-17 19:19 UTC, jalletto commented on blog/_posts/2023-07-25-using-gorm-go.md
> +# main.go
We don't need the file as a comment since we have the file name in the caption. This can be deleted in all examples.

2023-07-17 19:19 UTC, jalletto commented on blog/_posts/2023-07-25-using-gorm-go.md
> +Add the following code to your main function:
```suggestion

```

2023-07-17 20:58 UTC, msali123 commented
@jalletto [CHanges made](https://64b5aafcb493090088d41c4b--ephemeral-narwhal-3ac3b2.netlify.app/blog/using-gorm-go/)

2023-07-24 18:58 UTC, jalletto commented
@msali123 @Ubaydah reached out to the author. The author has replaced the bad images with some text output. They should be in the original doc. Can you please replace the blurry images with these outputs?

2023-07-24 20:12 UTC, msali123 commented
@jalletto [Done](https://64beda715b34bf17b2af0bf7--ephemeral-narwhal-3ac3b2.netlify.app/blog/using-gorm-go/)

2023-07-27 16:20 UTC, jalletto commented
@msali123 For the image replacement, there should be text (like code snippets) instead of images. example:

```text
 id | 	created_at            	|   	updated_at          	| deleted_at | first_name | last_name | email          	|country | role | age
----+-------------------------------+-------------------------------+------------+------------+-----------+-------------------+---------+------+-----
  1 | 2023-07-21 08:11:49.017357+01 | 2023-07-21 08:11:49.017357+01 |        	| Jane   	| Doe   	| janedoe@gmail.com | Spain   | Chef |  30
(1 row)


```

2023-07-27 16:49 UTC, jalletto requested changes

2023-07-27 16:49 UTC, jalletto commented on blog/_posts/2023-07-25-using-gorm-go.md
> +To update records with the GORM library, you typically retrieve the record, modify the record, save the changes, and handle errors. Here's an example:
```suggestion
```

2023-07-28 09:00 UTC, msali123 commented
Okay @jalletto i'll do all the changes once I get the new images.

Thanks

2023-07-28 16:46 UTC, jalletto commented
@msali123 There are no new images. We are replacing them with text output. I put a note in the document.

2023-07-28 18:39 UTC, msali123 commented
@jalletto [Preview Link](https://64c4086ec33bb039087b26b6--ephemeral-narwhal-3ac3b2.netlify.app/blog/using-gorm-go/)

2023-07-28 18:41 UTC, msali123 commented
Also @jalletto do I need to label the filename as Output?

2023-08-10 18:03 UTC, jalletto approved these changes

2023-08-10 18:20 UTC, jalletto commented on blog/_posts/2023-07-25-using-gorm-go.md
> +---
```suggestion
 - database operations
 - go using gorm
 - database operations in go
 - database operations using gorm
excerpt: |
    In Go, one library stands out when simplifying database interactions. This library is called GORM. This article will dive deep into using the GORM library to perform database operations in Go.
---
```

2023-08-10 19:25 UTC, merged