Blog - Building a CLI Application With Argparse
earthly/website pull request #566
Opened 2023-07-12 09:13 UTC by msali123

Done with all checks.

2023-07-12 09:23 UTC, msali123 commented
[Preview Link](https://64ae700982983507c2d0a03c--ephemeral-narwhal-3ac3b2.netlify.app/blog/cli-with-argparse/)

@jalletto

2023-07-17 19:30 UTC, jalletto requested changes

2023-07-17 19:30 UTC, jalletto commented on blog/_posts/2023-07-27-cli-with-argparse.md
> +# todo_cli.py
We can delete all of these since the caption has the file name

2023-07-17 19:30 UTC, jalletto commented on blog/_posts/2023-07-27-cli-with-argparse.md
> +By following this tutorial, you should have understood how to develop command-line applications in Python using `argparse` and how to add various features and options to make your CLI applications mo
```suggestion
 In this article, we covered the essential aspects of using `argparse` in Python CLI applications. We began by introducing `argparse` and its basic usage, including defining and parsing command-line arguments. Then, we built a ToDo CLI application, gradually adding features such as task storage, advanced arguments, error handling, and help messages.

We explored advanced argument concepts like choices, enabling us to enforce valid values for arguments. By leveraging `argparse`, we enhanced our ToDo CLI with features like sorting, such as marking tasks as done and removing tasks.

```

2023-07-18 20:58 UTC, jalletto approved these changes

2023-07-18 20:58 UTC, merged