Blog - Designing Extensible Software with Go Interfaces
earthly/website pull request #569
Opened 2023-07-13 08:35 UTC by msali123

Done with all checks.

2023-07-13 08:44 UTC, msali123 commented
@jalletto [Preview Link](https://64afb8b16b7aa435b918a7da--ephemeral-narwhal-3ac3b2.netlify.app/blog/software-design-go-interfaces/)

2023-07-17 19:48 UTC, jalletto requested changes

2023-07-17 19:48 UTC, jalletto commented on blog/_posts/2023-07-28-software-design-go-interfaces.md
> +[Go](https://go.dev/), also known as Golang, is a simple and efficient programming language that's been adopted by many tech companies, including Uber, Twitch, and Microsoft. Similar to other program
```suggestion
[Go](https://go.dev/), also known as Golang, is a simple and efficient programming language that's been adopted by many tech companies, including Uber, Twitch, and Microsoft. Similar to other programming languages such as Java and C++, Go supports interfaces, which provide a powerful mechanism for ensuring that class objects inherit a defined set of properties.
```
```suggestion
Go, also known as Golang, is a simple and efficient programming language that's been adopted by many tech companies, including Uber, Twitch, and Microsoft. Similar to other programming languages such as Java and C++, Go supports interfaces, which provide a powerful mechanism for ensuring that class objects inherit a defined set of properties.
```

2023-07-17 19:48 UTC, jalletto commented on blog/_posts/2023-07-28-software-design-go-interfaces.md
> +> **Please note:** Familiarity with object-oriented programming concepts is a prerequisite to walking through the article.
```suggestion
**Please note:** Familiarity with object-oriented programming concepts is a prerequisite to walking through the article.
```

2023-07-17 19:48 UTC, jalletto commented on blog/_posts/2023-07-28-software-design-go-interfaces.md
> +Interfaces have played a fundamental role in programming since the need to abstract the definition of a function from the implementation arose in [object-oriented programming](https://www.geeksforgee
```suggestion
A great example of why you need interfaces can be found in Eric Freeman and Elisabeth Robson's book [*Head First Design Patterns*](https://a.co/d/bCjS9z5). In it, Freeman and Robson mention a scenario in which a software engineer, Joe, creates a `Duck` superclass that can `quack()`, `swim()`, and `display()`, something all ducks can do. A `MallardDuck` and a `RedheadDuck` class can, therefore, be created that inherits the `Duck` superclass. Although these two classes must have the `quack()`, `swim()`, and `display()` functions since they inherit the `Duck` superclass, they can customize how these functions work according to their class.
```

2023-07-17 19:48 UTC, jalletto commented on blog/_posts/2023-07-28-software-design-go-interfaces.md
> +~~~
```suggestion
func requiresBath(d dog) bool {
    fmt.Printf("%s, needs a bath!", d.name)
    return true
}

func (d dog) walk() {
    fmt.Println("The dog is walking")
}

func (c cat) walk() {
    fmt.Println("The cat is walking")
}
~~~
```

2023-07-17 19:48 UTC, jalletto commented on blog/_posts/2023-07-28-software-design-go-interfaces.md
> +~~~
There are some other places where the code is not indented. Please fix those.

2023-07-17 21:19 UTC, msali123 commented
@jalletto [Changes done](https://64b5afc1ed27860094f4f147--ephemeral-narwhal-3ac3b2.netlify.app/blog/software-design-go-interfaces/)

2023-07-18 21:06 UTC, jalletto approved these changes

2023-07-18 21:07 UTC, merged