Blog - Exploring the Magic Methods in Python
earthly/website pull request #571
Opened 2023-07-14 15:25 UTC by msali123

Done with all checks.

2023-07-14 17:39 UTC, msali123 commented
@jalletto [Preview Link](https://64b16b4bde707a335fab0418--ephemeral-narwhal-3ac3b2.netlify.app/blog/magic-methods-python/)

2023-07-17 20:13 UTC, jalletto requested changes

2023-07-17 20:13 UTC, jalletto commented on blog/_posts/2023-07-31-magic-methods-python.md
> +#example1.py
Remove file name if it appears in the caption

2023-07-17 20:13 UTC, jalletto commented on blog/_posts/2023-07-31-magic-methods-python.md
> +> Note: If you try to assign a new song that doesn't have an index in the songs attribute using `__setitem__`, it may not work as expected. By default, if the index doesn't exist, `__setitem__` will
```suggestion
<div class="notice">
If you try to assign a new song that doesn't have an index in the songs attribute using `__setitem__`, it may not work as expected. By default, if the index doesn't exist, `__setitem__` will raise an `IndexError` indicating that the specified index is not found.
</div>
```

2023-07-17 21:27 UTC, msali123 commented
@jalletto [changes done](https://64b5b1d1cbd70e00bd92ccd7--ephemeral-narwhal-3ac3b2.netlify.app/blog/magic-methods-python/)

2023-07-18 21:13 UTC, jalletto approved these changes

2023-07-18 21:13 UTC, merged