Blog - How to Use `ripgrep` to Improve Your Search Efficiency
earthly/website pull request #586
Opened 2023-07-24 11:38 UTC by msali123

Done with all checks.

2023-07-24 12:19 UTC, msali123 commented
@jalletto  [Preview link](https://64be6bc58130e80ac055a8b7--ephemeral-narwhal-3ac3b2.netlify.app/blog/ripgrep-for-efficient-search/)

2023-08-10 21:09 UTC, jalletto requested changes

2023-08-10 21:09 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
@DrAnonymousNet I've tried to use this `--colors` command a few different ways and it keeps getting me errors. Can you please double-check that it works correctly?

I did a quick search and I'm not sure its a thing.

2023-08-10 21:09 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
@msali123 Please check in with Ahmad about this section, we may just delete it.

2023-08-10 21:09 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +To learn more about the `ripgrep` command line too, you can check out the following links:
```suggestion
To learn more about the `ripgrep` command line tool, you can check out the following links:
```

2023-08-10 21:32 UTC, msali123 commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +~~~
Okay @jalletto im removing from all outputs

2023-08-10 21:35 UTC, msali123 commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
@DrAnonymousNet I'll wait for your input on this

2023-08-10 23:15 UTC, DrAnonymousNet commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
![](https://files.slack.com/files-pri/T01DL290UJ3-F05MQENCVUH/screenshot_2023-08-11_at_00.10.08.png)

![](https://files.slack.com/files-pri/T01DL290UJ3-F05N1GJFDT2/screenshot_2023-08-11_at_00.11.42.png)

Hello @jalletto @msali123 , here is the documentation of the `--colors` flag and the output of using it on my laptop

2023-08-11 14:59 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
Thanks Ahmad! I have no idea what I was doing wrong.

2023-08-11 15:17 UTC, msali123 commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +
So @jalleto will it be as it is?

2023-08-11 17:58 UTC, jalletto commented
@msali123 Yes, I don't know why that build go stuck for 2hrs. You should be good to push now.

2023-08-11 18:19 UTC, msali123 commented
@jalletto this is the error. Can I do this - `.lzma`
![image](https://github.com/earthly/website/assets/32276372/675621e2-d2a8-4d9f-a335-43d21ef75ff8)

2023-08-11 18:30 UTC, msali123 commented
@jalletto also will it be `it supports the follow file formats:` or `it supports the following file formats:`

2023-08-11 20:34 UTC, jalletto commented
> @jalletto also will it be `it supports the follow file formats:` or `it supports the following file formats:`

Yes this should be "supports the following file formats:". Good catch!

For the `.lzma`. I'm not sure what error you are getting? But yes, you can do `.lzma`, but if you do please but the `.` before all the other extensions in the list.

2023-08-11 20:56 UTC, msali123 commented
@jalletto done.

2023-08-14 15:40 UTC, jalletto requested changes
@msali123 Great work on this. Just one last thing to take care of and we can merge it.

2023-08-14 15:40 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +3874:Apr  2 12:10:49 ubuntu-2204 kernel: [   15.040728] EXT4-fs (sda3): mounted filesystem with ordered data mode. Quota mode: none.
```suggestion
~~~{ caption="Output"}

3874:Apr  2 12:10:49 ubuntu-2204 kernel: [   15.040728] EXT4-fs (sda3): mounted filesystem with ordered data mode. Quota mode: none.
```

2023-08-14 15:40 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +3874:Apr  2 12:10:49 ubuntu-2204 kernel: [   15.040728] EXT4-fs (sda3): mounted filesystem with ordered data mode. Quota mode: none.
For some of the output sections where the content goes off screen it ends up overlapping with the caption. In these cases we should put a blank line at the top of the section so that there's no overlap.

2023-08-14 15:40 UTC, jalletto commented on blog/_posts/2023-08-09-ripgrep-for-efficient-search.md
> +3874:Apr  2 12:10:49 ubuntu-2204 kernel: [   15.040728] EXT4-fs (sda3): mounted filesystem with ordered data mode. Quota mode: none.
![Screen Shot 2023-08-14 at 10 35 27 AM](https://github.com/earthly/website/assets/27295314/a17bc6a4-0492-4b2a-ad21-f2ad3b96be15)

2023-08-14 18:11 UTC, msali123 commented
@jalletto sorry my bad I overlooked

[Preview Link](https://64da6c623dc70213194be468--ephemeral-narwhal-3ac3b2.netlify.app/blog/ripgrep-for-efficient-search/)

2023-08-15 17:36 UTC, jalletto approved these changes

2023-08-15 17:37 UTC, merged