Blog - Building a Monorepo with Rust
earthly/website pull request #744
Opened 2024-01-04 10:13 UTC by msali123

Done with all checks.

2024-01-04 10:31 UTC, msali123 commented
@adamgordonbell [Preview link](https://659688702f611e5fbda9d4a1--ephemeral-narwhal-3ac3b2.netlify.app/blog/rust-monorepo/)

[Airtable link](https://airtable.com/appbtxxY2KaPio7dV/tblsY8AOw3qPBIUdZ/viwBflqOY7OlQqiNg/recSIIWrtbhxA4ecR?blocks=hide)

2024-01-05 14:25 UTC, adamgordonbell requested changes
A couple small changes, otherwise good.

2024-01-05 14:25 UTC, adamgordonbell commented on blog/_posts/2024-01-11-rust-monorepo.md
> +~~~{.earthfile caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2024-01-05 14:25 UTC, adamgordonbell commented on blog/_posts/2024-01-11-rust-monorepo.md
> +~~~{.earthfile caption="Earthfile"}
The blog doesn't know Earthly, but docker is closest

2024-01-05 14:25 UTC, adamgordonbell commented on blog/_posts/2024-01-11-rust-monorepo.md
> +~~~{.earthfile caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2024-01-05 14:25 UTC, adamgordonbell commented on blog/_posts/2024-01-11-rust-monorepo.md
> +~~~{.earthfile caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2024-01-05 14:25 UTC, adamgordonbell commented on blog/_posts/2024-01-11-rust-monorepo.md
> +~~~{.earthfile caption="Earthfile"}
```suggestion
~~~{.dockerfile caption="Earthfile"}
```

2024-01-05 14:49 UTC, msali123 commented
@adamgordonbell [Updated link](https://659815bd6247541408c2e0e6--ephemeral-narwhal-3ac3b2.netlify.app/blog/rust-monorepo/)

2024-01-05 15:02 UTC, merged